module.exports = {
   data: {
      "Alicia Blakely (01)": {
         "Name": "Alicia Blakely",
         "ID": "OI",
         "Image URL": "https://i.ibb.co/YXVW5S3/generic-7.png",
         "Clone": "Mo Vaughn",
         "Variant": "01",
         "Lock Pos": "1B",
         "Stamina": 100,
         "Intelligence": 72,
         "Coordination": 71,
         "Speed": 45,
         "Arm Strength": 60,
         "Throwing": 51,
         "Bat Power": 86,
         "Bat Contact": 58,
         "Eye": 84,
         "Attention": 54,
         "Appearance": 7,
         "Aggression": 65,
         "Bats": "Left",
         "Throws": "Right",
         "Heat": 12,
         "Slowball": 40,
         "Left Hook": 58,
         "Right Hook": 50,
         "Corkscrew": 0,
         "Zig-Zag": 50,
         "Big Freeze": 79,
         "Fireball": 0,
         "Spitball": 0,
         "Crazyball": 0,
         "Slo-mo": 54,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 4,
         "Gender": "Girl",
         "B-Day Month": "Dec",
         "B-Day Day": 15,
         "Nickname": "",
         "B": 8,
         "R": 5,
         "P": 7,
         "F": 8
      },
      "Barbara Jones (01)": {
         "Name": "Barbara Jones",
         "ID": "OL",
         "Image URL": "https://i.ibb.co/SdfQWNw/generic-10.png",
         "Clone": "Cal Ripken Jr.",
         "Variant": "01",
         "Lock Pos": "3B",
         "Stamina": 100,
         "Intelligence": 100,
         "Coordination": 86,
         "Speed": 69,
         "Arm Strength": 80,
         "Throwing": 96,
         "Bat Power": 74,
         "Bat Contact": 68,
         "Eye": 48,
         "Attention": 82,
         "Appearance": 10,
         "Aggression": 56,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 10,
         "Slowball": 25,
         "Left Hook": 70,
         "Right Hook": 29,
         "Corkscrew": 0,
         "Zig-Zag": 73,
         "Big Freeze": 0,
         "Fireball": 44,
         "Spitball": 0,
         "Crazyball": 0,
         "Slo-mo": 26,
         "Elevator": 72,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Aug",
         "B-Day Day": 24,
         "Nickname": "",
         "B": 8,
         "R": 7,
         "P": 5,
         "F": 10
      },
      "Claudia Villarta (01)": {
         "Name": "Claudia Villarta",
         "ID": "OP",
         "Image URL": "https://i.ibb.co/nbmCr91/generic-8.png",
         "Clone": "Barry Larkin",
         "Variant": "01",
         "Lock Pos": "SS",
         "Stamina": 24,
         "Intelligence": 20,
         "Coordination": 84,
         "Speed": 89,
         "Arm Strength": 89,
         "Throwing": 66,
         "Bat Power": 76,
         "Bat Contact": 58,
         "Eye": 69,
         "Attention": 74,
         "Appearance": 8,
         "Aggression": 81,
         "Bats": "Left",
         "Throws": "Left",
         "Heat": 60,
         "Slowball": 57,
         "Left Hook": 37,
         "Right Hook": 0,
         "Corkscrew": 33,
         "Zig-Zag": 47,
         "Big Freeze": 0,
         "Fireball": 0,
         "Spitball": 57,
         "Crazyball": 100,
         "Slo-mo": 59,
         "Elevator": 64,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Apr",
         "B-Day Day": 28,
         "Nickname": "",
         "B": 7,
         "R": 9,
         "P": 2,
         "F": 9
      },
      "Dawn Cozart (01)": {
         "Name": "Dawn Cozart",
         "ID": "PA",
         "Image URL": "https://i.ibb.co/ZL29Rqg/generic-9.png",
         "Clone": "Kenny Lofton",
         "Variant": "01",
         "Lock Pos": "CF",
         "Stamina": 65,
         "Intelligence": 65,
         "Coordination": 76,
         "Speed": 99,
         "Arm Strength": 83,
         "Throwing": 78,
         "Bat Power": 76,
         "Bat Contact": 48,
         "Eye": 53,
         "Attention": 47,
         "Appearance": 9,
         "Aggression": 87,
         "Bats": "Left",
         "Throws": "Left",
         "Heat": 0,
         "Slowball": 52,
         "Left Hook": 60,
         "Right Hook": 86,
         "Corkscrew": 0,
         "Zig-Zag": 89,
         "Big Freeze": 0,
         "Fireball": 31,
         "Spitball": 0,
         "Crazyball": 41,
         "Slo-mo": 0,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "May",
         "B-Day Day": 31,
         "Nickname": "",
         "B": 7,
         "R": 10,
         "P": 6,
         "F": 8
      },
      "Emily Lewbel (01)": {
         "Name": "Emily Lewbel",
         "ID": "PB",
         "Image URL": "https://i.ibb.co/SdfQWNw/generic-10.png",
         "Clone": "Larry Walker",
         "Variant": "01",
         "Lock Pos": "RF",
         "Stamina": 26,
         "Intelligence": 59,
         "Coordination": 55,
         "Speed": 75,
         "Arm Strength": 92,
         "Throwing": 96,
         "Bat Power": 85,
         "Bat Contact": 73,
         "Eye": 98,
         "Attention": 72,
         "Appearance": 10,
         "Aggression": 63,
         "Bats": "Left",
         "Throws": "Right",
         "Heat": 10,
         "Slowball": 68,
         "Left Hook": 27,
         "Right Hook": 25,
         "Corkscrew": 18,
         "Zig-Zag": 0,
         "Big Freeze": 38,
         "Fireball": 76,
         "Spitball": 0,
         "Crazyball": 78,
         "Slo-mo": 57,
         "Elevator": 21,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Dec",
         "B-Day Day": 1,
         "Nickname": "",
         "B": 9,
         "R": 8,
         "P": 2,
         "F": 9
      },
      "Fay Dawson (01)": {
         "Name": "Fay Dawson",
         "ID": "PC",
         "Image URL": "https://i.ibb.co/4j2Pwwz/generic-11.png",
         "Clone": "Juan Gonzalez",
         "Variant": "01",
         "Lock Pos": "RF",
         "Stamina": 45,
         "Intelligence": 55,
         "Coordination": 78,
         "Speed": 64,
         "Arm Strength": 95,
         "Throwing": 46,
         "Bat Power": 83,
         "Bat Contact": 69,
         "Eye": 72,
         "Attention": 51,
         "Appearance": 11,
         "Aggression": 58,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 62,
         "Slowball": 37,
         "Left Hook": 47,
         "Right Hook": 29,
         "Corkscrew": 0,
         "Zig-Zag": 60,
         "Big Freeze": 44,
         "Fireball": 0,
         "Spitball": 86,
         "Crazyball": 39,
         "Slo-mo": 0,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Oct",
         "B-Day Day": 16,
         "Nickname": "",
         "B": 9,
         "R": 8,
         "P": 4,
         "F": 9
      },
      "Gwen Sears (01)": {
         "Name": "Gwen Sears",
         "ID": "PD",
         "Image URL": "https://i.ibb.co/djnk7t3/generic-12.png",
         "Clone": "Alex Gonzalez",
         "Variant": "01",
         "Lock Pos": "SS",
         "Stamina": 75,
         "Intelligence": 91,
         "Coordination": 71,
         "Speed": 85,
         "Arm Strength": 77,
         "Throwing": 54,
         "Bat Power": 69,
         "Bat Contact": 10,
         "Eye": 14,
         "Attention": 35,
         "Appearance": 12,
         "Aggression": 81,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 23,
         "Slowball": 0,
         "Left Hook": 74,
         "Right Hook": 6,
         "Corkscrew": 100,
         "Zig-Zag": 0,
         "Big Freeze": 0,
         "Fireball": 0,
         "Spitball": 43,
         "Crazyball": 64,
         "Slo-mo": 86,
         "Elevator": 66,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Feb",
         "B-Day Day": 15,
         "Nickname": "",
         "B": 5,
         "R": 9,
         "P": 3,
         "F": 6
      },
      "Jessica Wassersas (01)": {
         "Name": "Jessica Wassersas",
         "ID": "PG",
         "Image URL": "https://i.ibb.co/ZL29Rqg/generic-9.png",
         "Clone": "Raul Mondesi",
         "Variant": "01",
         "Lock Pos": "RF",
         "Stamina": 100,
         "Intelligence": 78,
         "Coordination": 52,
         "Speed": 87,
         "Arm Strength": 100,
         "Throwing": 79,
         "Bat Power": 82,
         "Bat Contact": 48,
         "Eye": 53,
         "Attention": 25,
         "Appearance": 9,
         "Aggression": 63,
         "Bats": "Left",
         "Throws": "Left",
         "Heat": 30,
         "Slowball": 30,
         "Left Hook": 0,
         "Right Hook": 68,
         "Corkscrew": 25,
         "Zig-Zag": 0,
         "Big Freeze": 18,
         "Fireball": 96,
         "Spitball": 0,
         "Crazyball": 0,
         "Slo-mo": 0,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Mar",
         "B-Day Day": 12,
         "Nickname": "",
         "B": 8,
         "R": 9,
         "P": 5,
         "F": 7
      },
      "Jillian Paine (01)": {
         "Name": "Jillian Paine",
         "ID": "PH",
         "Image URL": "https://i.ibb.co/SdfQWNw/generic-10.png",
         "Clone": "Jeromy Burnitz",
         "Variant": "01",
         "Lock Pos": "RF",
         "Stamina": 50,
         "Intelligence": 54,
         "Coordination": 81,
         "Speed": 57,
         "Arm Strength": 80,
         "Throwing": 31,
         "Bat Power": 83,
         "Bat Contact": 35,
         "Eye": 45,
         "Attention": 51,
         "Appearance": 10,
         "Aggression": 72,
         "Bats": "Left",
         "Throws": "Right",
         "Heat": 38,
         "Slowball": 82,
         "Left Hook": 0,
         "Right Hook": 28,
         "Corkscrew": 0,
         "Zig-Zag": 50,
         "Big Freeze": 79,
         "Fireball": 0,
         "Spitball": 0,
         "Crazyball": 0,
         "Slo-mo": 54,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Apr",
         "B-Day Day": 15,
         "Nickname": "",
         "B": 7,
         "R": 6,
         "P": 4,
         "F": 7
      },
      "Kristen Sullivan (01)": {
         "Name": "Kristen Sullivan",
         "ID": "PI",
         "Image URL": "https://i.ibb.co/4j2Pwwz/generic-11.png",
         "Clone": "Marty Cordova",
         "Variant": "01",
         "Lock Pos": "LF",
         "Stamina": 45,
         "Intelligence": 76,
         "Coordination": 30,
         "Speed": 63,
         "Arm Strength": 95,
         "Throwing": 76,
         "Bat Power": 69,
         "Bat Contact": 46,
         "Eye": 36,
         "Attention": 74,
         "Appearance": 11,
         "Aggression": 56,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 32,
         "Slowball": 45,
         "Left Hook": 89,
         "Right Hook": 85,
         "Corkscrew": 78,
         "Zig-Zag": 86,
         "Big Freeze": 81,
         "Fireball": 0,
         "Spitball": 0,
         "Crazyball": 91,
         "Slo-mo": 70,
         "Elevator": 100,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Jul",
         "B-Day Day": 10,
         "Nickname": "",
         "B": 6,
         "R": 7,
         "P": 7,
         "F": 4
      },
      "Melissa Waters (01)": {
         "Name": "Melissa Waters",
         "ID": "PM",
         "Image URL": "https://i.ibb.co/ZL29Rqg/generic-9.png",
         "Clone": "Jason Giambi",
         "Variant": "01",
         "Lock Pos": "1B",
         "Stamina": 62,
         "Intelligence": 87,
         "Coordination": 100,
         "Speed": 37,
         "Arm Strength": 24,
         "Throwing": 45,
         "Bat Power": 81,
         "Bat Contact": 41,
         "Eye": 60,
         "Attention": 52,
         "Appearance": 9,
         "Aggression": 81,
         "Bats": "Left",
         "Throws": "Right",
         "Heat": 70,
         "Slowball": 29,
         "Left Hook": 66,
         "Right Hook": 74,
         "Corkscrew": 32,
         "Zig-Zag": 62,
         "Big Freeze": 0,
         "Fireball": 46,
         "Spitball": 56,
         "Crazyball": 66,
         "Slo-mo": 0,
         "Elevator": 87,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Jan",
         "B-Day Day": 8,
         "Nickname": "",
         "B": 7,
         "R": 4,
         "P": 7,
         "F": 8
      },
      "Nan Porter (01)": {
         "Name": "Nan Porter",
         "ID": "PN",
         "Image URL": "https://i.ibb.co/SdfQWNw/generic-10.png",
         "Clone": "Curt Schilling",
         "Variant": "01",
         "Lock Pos": "P",
         "Stamina": 57,
         "Intelligence": 95,
         "Coordination": 62,
         "Speed": 58,
         "Arm Strength": 97,
         "Throwing": 55,
         "Bat Power": 15,
         "Bat Contact": 66,
         "Eye": 75,
         "Attention": 52,
         "Appearance": 10,
         "Aggression": 46,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 88,
         "Slowball": 74,
         "Left Hook": 70,
         "Right Hook": 79,
         "Corkscrew": 75,
         "Zig-Zag": 64,
         "Big Freeze": 57,
         "Fireball": 40,
         "Spitball": 100,
         "Crazyball": 74,
         "Slo-mo": 60,
         "Elevator": 100,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Nov",
         "B-Day Day": 14,
         "Nickname": "",
         "B": 5,
         "R": 6,
         "P": 10,
         "F": 8
      },
      "Raquel Cullen (01)": {
         "Name": "Raquel Cullen",
         "ID": "PP",
         "Image URL": "https://i.ibb.co/djnk7t3/generic-12.png",
         "Clone": "Tony Gwynn",
         "Variant": "01",
         "Lock Pos": "RF",
         "Stamina": 21,
         "Intelligence": 98,
         "Coordination": 63,
         "Speed": 57,
         "Arm Strength": 58,
         "Throwing": 85,
         "Bat Power": 65,
         "Bat Contact": 84,
         "Eye": 82,
         "Attention": 93,
         "Appearance": 12,
         "Aggression": 46,
         "Bats": "Left",
         "Throws": "Left",
         "Heat": 6,
         "Slowball": 80,
         "Left Hook": 43,
         "Right Hook": 47,
         "Corkscrew": 62,
         "Zig-Zag": 0,
         "Big Freeze": 0,
         "Fireball": 0,
         "Spitball": 0,
         "Crazyball": 0,
         "Slo-mo": 0,
         "Elevator": 85,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "May",
         "B-Day Day": 9,
         "Nickname": "",
         "B": 9,
         "R": 6,
         "P": 3,
         "F": 8
      },
      "Susan Gore (01)": {
         "Name": "Susan Gore",
         "ID": "QB",
         "Image URL": "https://i.ibb.co/nbmCr91/generic-8.png",
         "Clone": "Ken Griffey Jr.",
         "Variant": "01",
         "Lock Pos": "CF",
         "Stamina": 70,
         "Intelligence": 93,
         "Coordination": 95,
         "Speed": 73,
         "Arm Strength": 75,
         "Throwing": 76,
         "Bat Power": 100,
         "Bat Contact": 37,
         "Eye": 55,
         "Attention": 53,
         "Appearance": 8,
         "Aggression": 79,
         "Bats": "Left",
         "Throws": "Left",
         "Heat": 48,
         "Slowball": 45,
         "Left Hook": 73,
         "Right Hook": 0,
         "Corkscrew": 0,
         "Zig-Zag": 81,
         "Big Freeze": 0,
         "Fireball": 58,
         "Spitball": 70,
         "Crazyball": 0,
         "Slo-mo": 0,
         "Elevator": 71,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Nov",
         "B-Day Day": 21,
         "Nickname": "",
         "B": 9,
         "R": 8,
         "P": 5,
         "F": 10
      },
      "Sophie Meyer (01)": {
         "Name": "Sophie Meyer",
         "ID": "QC",
         "Image URL": "https://i.ibb.co/ZL29Rqg/generic-9.png",
         "Clone": "Mark McGwire",
         "Variant": "01",
         "Lock Pos": "1B",
         "Stamina": 40,
         "Intelligence": 66,
         "Coordination": 76,
         "Speed": 31,
         "Arm Strength": 63,
         "Throwing": 50,
         "Bat Power": 100,
         "Bat Contact": 50,
         "Eye": 63,
         "Attention": 68,
         "Appearance": 9,
         "Aggression": 34,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 68,
         "Slowball": 40,
         "Left Hook": 75,
         "Right Hook": 50,
         "Corkscrew": 46,
         "Zig-Zag": 19,
         "Big Freeze": 23,
         "Fireball": 90,
         "Spitball": 50,
         "Crazyball": 0,
         "Slo-mo": 82,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 4,
         "Gender": "Girl",
         "B-Day Month": "Oct",
         "B-Day Day": 1,
         "Nickname": "",
         "B": 10,
         "R": 4,
         "P": 6,
         "F": 7
      },
      "Tonya Lesco (01)": {
         "Name": "Tonya Lesco",
         "ID": "QD",
         "Image URL": "https://i.ibb.co/SdfQWNw/generic-10.png",
         "Clone": "Jose Canseco",
         "Variant": "01",
         "Lock Pos": "RF",
         "Stamina": 95,
         "Intelligence": 40,
         "Coordination": 10,
         "Speed": 70,
         "Arm Strength": 80,
         "Throwing": 80,
         "Bat Power": 100,
         "Bat Contact": 19,
         "Eye": 90,
         "Attention": 50,
         "Appearance": 10,
         "Aggression": 81,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 28,
         "Slowball": 45,
         "Left Hook": 0,
         "Right Hook": 75,
         "Corkscrew": 0,
         "Zig-Zag": 60,
         "Big Freeze": 44,
         "Fireball": 0,
         "Spitball": 86,
         "Crazyball": 39,
         "Slo-mo": 0,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 4,
         "Gender": "Girl",
         "B-Day Month": "Jul",
         "B-Day Day": 2,
         "Nickname": "",
         "B": 8,
         "R": 8,
         "P": 6,
         "F": 4
      },
      "Wendy Parsons (01)": {
         "Name": "Wendy Parsons",
         "ID": "QE",
         "Image URL": "https://i.ibb.co/4j2Pwwz/generic-11.png",
         "Clone": "Ivan Rodriguez",
         "Variant": "01",
         "Lock Pos": "C",
         "Stamina": 18,
         "Intelligence": 66,
         "Coordination": 70,
         "Speed": 48,
         "Arm Strength": 99,
         "Throwing": 55,
         "Bat Power": 70,
         "Bat Contact": 70,
         "Eye": 76,
         "Attention": 99,
         "Appearance": 11,
         "Aggression": 34,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 85,
         "Slowball": 67,
         "Left Hook": 52,
         "Right Hook": 85,
         "Corkscrew": 0,
         "Zig-Zag": 50,
         "Big Freeze": 79,
         "Fireball": 0,
         "Spitball": 0,
         "Crazyball": 0,
         "Slo-mo": 54,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 2,
         "Gender": "Girl",
         "B-Day Month": "Nov",
         "B-Day Day": 30,
         "Nickname": "",
         "B": 7,
         "R": 5,
         "P": 7,
         "F": 8
      },
      "Yvonne Carter (01)": {
         "Name": "Yvonne Carter",
         "ID": "QF",
         "Image URL": "https://i.ibb.co/djnk7t3/generic-12.png",
         "Clone": "Shawn Green",
         "Variant": "01",
         "Lock Pos": "RF",
         "Stamina": 59,
         "Intelligence": 58,
         "Coordination": 52,
         "Speed": 63,
         "Arm Strength": 62,
         "Throwing": 46,
         "Bat Power": 82,
         "Bat Contact": 45,
         "Eye": 51,
         "Attention": 71,
         "Appearance": 12,
         "Aggression": 65,
         "Bats": "Left",
         "Throws": "Left",
         "Heat": 74,
         "Slowball": 48,
         "Left Hook": 100,
         "Right Hook": 20,
         "Corkscrew": 18,
         "Zig-Zag": 0,
         "Big Freeze": 38,
         "Fireball": 76,
         "Spitball": 0,
         "Crazyball": 78,
         "Slo-mo": 57,
         "Elevator": 21,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Nov",
         "B-Day Day": 10,
         "Nickname": "",
         "B": 8,
         "R": 7,
         "P": 7,
         "F": 5
      },
      "Zoe Mallory (01)": {
         "Name": "Zoe Mallory",
         "ID": "QG",
         "Image URL": "https://i.ibb.co/ZL29Rqg/generic-9.png",
         "Clone": "Alex Rodriguez",
         "Variant": "01",
         "Lock Pos": "SS",
         "Stamina": 70,
         "Intelligence": 70,
         "Coordination": 85,
         "Speed": 85,
         "Arm Strength": 75,
         "Throwing": 76,
         "Bat Power": 75,
         "Bat Contact": 60,
         "Eye": 55,
         "Attention": 20,
         "Appearance": 12,
         "Aggression": 50,
         "Bats": "Right",
         "Throws": "Right",
         "Heat": 12,
         "Slowball": 42,
         "Left Hook": 30,
         "Right Hook": 20,
         "Corkscrew": 0,
         "Zig-Zag": 0,
         "Big Freeze": 0,
         "Fireball": 0,
         "Spitball": 0,
         "Crazyball": 0,
         "Slo-mo": 0,
         "Elevator": 0,
         "Stance": 2,
         "Height/S-Zone": 3,
         "Gender": "Girl",
         "B-Day Month": "Jul",
         "B-Day Day": 27,
         "Nickname": "",
         "B": 7,
         "R": 9,
         "P": 3,
         "F": 9
      },
      "Maria Luna (Pink)": {
         "Name": "Maria Luna",
         "ID": "AC",
         "Image URL": "https://i.ibb.co/gDXzRbZ/B-Maria-P.png",
         "Clone": "",
         "Variant": "Pink",
         "Lock Pos": "",
         "Stamina": 64,
         "Intelligence": 16,
         "Coordination": 87,
         "Speed": 80,
         "Arm Strength": 73,
         "Throwing": 73,
         "Bat Power": 87,
         "Bat Contact": 75,
         "Eye": 80,
         "Attention": 64,
         "Appearance": 15,
         "Aggression": 21,
         "Bats": "Left",
         "Throws": "Left",
         "Heat": 56,
         "Slowball": 80,
         "Left Hook": 73,
         "Right Hook": 77,
         "Corkscrew": 0,
         "Zig-Zag": 67,
         "Big Freeze": 0,
         "Fireball": 0,
         "Spitball": 0,
         "Crazyball": 28,
         "Slo-mo": 31,
         "Elevator": 86,
         "Stance": 3,
         "Height/S-Zone": 2,
         "Gender": "Girl",
         "B-Day Month": "Jul",
         "B-Day Day": 23,
         "Nickname": "Pinky",
         "B": 9,
         "R": 9,
         "P": 9,
         "F": 10
      }
   }
}