// http://www.convertcsv.com/csv-to-json.htm

module.exports = {
 Players : {
	 'AA': {
		'Name': 'Cloney -.',
			'Batting': 1,
			'Running': 1,
			'Pitching': 1,
			'Fielding': 1,
			'Handedness': 'R',
			'Face Type': 'A',
			'TOTAL': 4,
			'Price': 3
	 },
	 'AB': {
			'Name': 'Kimmy Eckman',
		'Batting': 6,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 16,
			'Price': 3
	 },
	 'AC': {
			'Name': 'Maria Luna',
			'Batting': 6,
			'Running': 7,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'L',
		'Face Type': 'unique',
			'TOTAL': 23,
		'Price': 3
	},
	'AD': {
			'Name': 'Angela Delvecchio',
			'Batting': 8,
			'Running': 4,
			'Pitching': 10,
			'Fielding': 1,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 9
	 },
	 'AE': {
			'Name': 'Vicki Kawaguchi',
			'Batting': 1,
			'Running': 9,
			'Pitching': 5,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 25,
			'Price': 12
	 },
	 'AF': {
			'Name': 'Gretchen Hasselhoff',
			'Batting': 2,
			'Running': 8,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 20,
			'Price': 3
	 },
	 'AG': {
			'Name': 'Sally Dobbs',
			'Batting': 7,
			'Running': 7,
			'Pitching': 7,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 28,
			'Price': 3
	 },
	 'AH': {
			'Name': 'Billy Jean Blackwood',
			'Batting': 8,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 22,
			'Price': 3
	 },
	 'AI': {
			'Name': 'Ashley Webber',
			'Batting': 5,
			'Running': 7,
			'Pitching': 6,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 21,
			'Price': 3
	 },
	 'AJ': {
			'Name': 'Sidney Webber',
			'Batting': 5,
			'Running': 7,
			'Pitching': 6,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 21,
			'Price': 3
	 },
	 'AK': {
			'Name': 'Kiesha Phillips',
			'Batting': 9,
			'Running': 9,
			'Pitching': 4,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 28,
			'Price': 10
	 },
	 'AL': {
			'Name': 'Stephanie Morgan',
			'Batting': 6,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 3
	 },
	 'AM': {
			'Name': 'Luanne Lui',
			'Batting': 6,
			'Running': 10,
			'Pitching': 9,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 29,
			'Price': 13
	 },
	 'AN': {
			'Name': 'Annie Frazier',
			'Batting': 9,
			'Running': 8,
			'Pitching': 1,
			'Fielding': 6,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 24,
			'Price': 7
	 },
	 'AO': {
			'Name': 'Jocinda Smith',
			'Batting': 10,
			'Running': 5,
			'Pitching': 3,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 9
	 },
	 'AP': {
			'Name': 'Lisa Crocket',
			'Batting': 5,
			'Running': 8,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 3
	 },
	 'BA': {
			'Name': 'Ronny Dobbs',
			'Batting': 7,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 3
	 },
	 'BB': {
			'Name': 'Achmed Khan',
			'Batting': 10,
			'Running': 7,
			'Pitching': 2,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 24,
			'Price': 7
	 },
	 'BC': {
			'Name': 'Amir Khan',
			'Batting': 7,
			'Running': 6,
			'Pitching': 9,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 5
	 },
	 'BD': {
			'Name': 'Kenny Kawaguchi',
			'Batting': 3,
			'Running': 8,
			'Pitching': 7,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 22,
			'Price': 3
	 },
	 'BE': {
			'Name': 'Pete Wheeler',
			'Batting': 8,
			'Running': 10,
			'Pitching': 2,
			'Fielding': 7,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 27,
			'Price': 11
	 },
	 'BF': {
			'Name': 'Dmitri Petrovich',
			'Batting': 8,
			'Running': 7,
			'Pitching': 1,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 19,
			'Price': 3
	 },
	 'BG': {
			'Name': 'Ricky Johnson',
			'Batting': 1,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 19,
			'Price': 3
	 },
	 'BH': {
			'Name': 'Marky Dubois',
			'Batting': 5,
			'Running': 4,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 24,
			'Price': 3
	 },
	 'BI': {
			'Name': 'Reese Worthington',
			'Batting': 3,
			'Running': 8,
			'Pitching': 4,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 3
	 },
	 'BJ': {
			'Name': 'Pablo Sanchez',
			'Batting': 10,
			'Running': 9,
			'Pitching': 5,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 34,
			'Price': 22
	 },
	 'BK': {
			'Name': 'Tony Delvecchio',
			'Batting': 7,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 3
	 },
	 'BL': {
			'Name': 'Jorge Garcia',
			'Batting': 8,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 3
	 },
	 'BM': {
			'Name': 'Dante Robinson',
			'Batting': 4,
			'Running': 9,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 25,
			'Price': 4
	 },
	 'BN': {
			'Name': 'Ernie Steele',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 28,
			'Price': 8
	 },
	 'BO': {
			'Name': 'Mikey Thomas',
			'Batting': 10,
			'Running': 4,
			'Pitching': 4,
			'Fielding': 7,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 25,
			'Price': 9
	 },
	 'BP': {
			'Name': 'Troy Glaus',
			'Batting': 8,
			'Running': 8,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 10
	 },
	 'CA': {
			'Name': 'Randy Johnson',
			'Batting': 5,
			'Running': 5,
			'Pitching': 10,
			'Fielding': 3,
			'Handedness': 'R/L',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 10
	 },
	 'CB': {
			'Name': 'Chipper Jones',
			'Batting': 8,
			'Running': 7,
			'Pitching': 4,
			'Fielding': 8,
			'Handedness': 'S/R',
			'Face Type': 'unique',
			'TOTAL': 27,
			'Price': 10
	 },
	 'CC': {
			'Name': 'Jeff Conine',
			'Batting': 8,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 24,
			'Price': 7
	 },
	 'CD': {
			'Name': 'Nomar Garciaparra',
			'Batting': 8,
			'Running': 7,
			'Pitching': 7,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 32,
			'Price': 18
	 },
	 'CE': {
			'Name': 'Sammy Sosa',
			'Batting': 10,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 30,
			'Price': 16
	 },
	 'CF': {
			'Name': 'Frank Thomas',
			'Batting': 7,
			'Running': 4,
			'Pitching': 10,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 25,
			'Price': 12
	 },
	 'CG': {
			'Name': 'Ken Griffey Jr.',
			'Batting': 9,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 10,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 32,
			'Price': 21
	 },
	 'CH': {
			'Name': 'Jim Thome',
			'Batting': 8,
			'Running': 5,
			'Pitching': 4,
			'Fielding': 6,
			'Handedness': 'L/R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 5
	 },
	 'CI': {
			'Name': 'Todd Helton',
			'Batting': 9,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 10,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 17
	 },
	 'CJ': {
			'Name': 'Bobby Higginson',
			'Batting': 7,
			'Running': 8,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': 'L/R',
			'Face Type': 'unique',
			'TOTAL': 27,
			'Price': 13
	 },
	 'CK': {
			'Name': 'Cliff Floyd',
			'Batting': 8,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'L/R',
			'Face Type': 'unique',
			'TOTAL': 27,
			'Price': 13
	 },
	 'CL': {
			'Name': 'Jeff Bagwell',
			'Batting': 8,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 11
	 },
	 'CM': {
			'Name': 'Carlos Beltran',
			'Batting': 5,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': 'S/R',
			'Face Type': 'unique',
			'TOTAL': 25,
			'Price': 6
	 },
	 'CN': {
			'Name': 'Shawn Green',
			'Batting': 8,
			'Running': 7,
			'Pitching': 7,
			'Fielding': 5,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 27,
			'Price': 8
	 },
	 'CO': {
			'Name': 'Richie Sexson',
			'Batting': 7,
			'Running': 6,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 24,
			'Price': 4
	 },
	 'CP': {
			'Name': 'Brad Radke',
			'Batting': 2,
			'Running': 7,
			'Pitching': 8,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 25,
			'Price': 10
	 },
	 'DA': {
			'Name': 'Vladimir Guerrero',
			'Batting': 8,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 27,
			'Price': 9
	 },
	 'DB': {
			'Name': 'Mike Piazza',
			'Batting': 9,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 23,
			'Price': 13
	 },
	 'DC': {
			'Name': 'Derek Jeter',
			'Batting': 8,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 30,
			'Price': 21
	 },
	 'DD': {
			'Name': 'Tim Hudson',
			'Batting': 4,
			'Running': 5,
			'Pitching': 8,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 22,
			'Price': 4
	 },
	 'DE': {
			'Name': 'Jimmy Rollins',
			'Batting': 6,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'S/R',
			'Face Type': 'unique',
			'TOTAL': 25,
			'Price': 10
	 },
	 'DF': {
			'Name': 'Jason Kendall',
			'Batting': 7,
			'Running': 8,
			'Pitching': 4,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 8
	 },
	 'DG': {
			'Name': 'Phil Nevin',
			'Batting': 9,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 24,
			'Price': 8
	 },
	 'DH': {
			'Name': 'Barry Bonds',
			'Batting': 8,
			'Running': 10,
			'Pitching': 6,
			'Fielding': 9,
			'Handedness': 'L',
			'Face Type': 'unique',
			'TOTAL': 33,
			'Price': 22
	 },
	 'DI': {
			'Name': 'Ichiro',
			'Batting': 8,
			'Running': 10,
			'Pitching': 2,
			'Fielding': 10,
			'Handedness': 'L/R',
			'Face Type': 'unique',
			'TOTAL': 30,
			'Price': 24
	 },
	 'DJ': {
			'Name': 'Albert Pujols',
			'Batting': 8,
			'Running': 4,
			'Pitching': 8,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 27,
			'Price': 10
	 },
	 'DK': {
			'Name': 'Greg Vaughn',
			'Batting': 7,
			'Running': 5,
			'Pitching': 4,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 24,
			'Price': 6
	 },
	 'DL': {
			'Name': 'Alex Rodriguez',
			'Batting': 7,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 28,
			'Price': 16
	 },
	 'DM': {
			'Name': 'Carlos Delgado',
			'Batting': 8,
			'Running': 5,
			'Pitching': 8,
			'Fielding': 7,
			'Handedness': 'L/R',
			'Face Type': 'unique',
			'TOTAL': 28,
			'Price': 10
	 },
	 'DN': {
			'Name': 'Jason Giambi',
			'Batting': 7,
			'Running': 4,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': 'L/R',
			'Face Type': 'unique',
			'TOTAL': 26,
			'Price': 8
	 },
	 'DO': {
			'Name': 'Amy Bostwick',
			'Batting': 6,
			'Running': 2,
			'Pitching': 3,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'H',
			'TOTAL': 14,
			'Price': 3
	 },
	 'DP': {
			'Name': 'Arlene Perez',
			'Batting': 6,
			'Running': 7,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'I',
			'TOTAL': 23,
			'Price': 5
	 },
	 'EA': {
			'Name': 'Betty Houston',
			'Batting': 8,
			'Running': 4,
			'Pitching': 9,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': 'J',
			'TOTAL': 22,
			'Price': 11
	 },
	 'EB': {
			'Name': 'Cindy Chang',
			'Batting': 1,
			'Running': 9,
			'Pitching': 5,
			'Fielding': 10,
			'Handedness': '',
			'Face Type': 'K',
			'TOTAL': 25,
			'Price': 17
	 },
	 'EC': {
			'Name': 'Clarice Reid',
			'Batting': 2,
			'Running': 8,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'L',
			'TOTAL': 20,
			'Price': 5
	 },
	 'ED': {
			'Name': 'Colleen Klinker',
			'Batting': 4,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'M',
			'TOTAL': 24,
			'Price': 6
	 },
	 'EE': {
			'Name': 'Debby Nagasawa',
			'Batting': 10,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 26,
			'Price': 12
	 },
	 'EF': {
			'Name': 'Diana Hayes',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'I',
			'TOTAL': 21,
			'Price': 3
	 },
	 'EG': {
			'Name': 'Esther French',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'J',
			'TOTAL': 21,
			'Price': 3
	 },
	 'EH': {
			'Name': 'Francis Blewer',
			'Batting': 9,
			'Running': 9,
			'Pitching': 6,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 31,
			'Price': 17
	 },
	 'EI': {
			'Name': 'Gail Weinmann',
			'Batting': 6,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'L',
			'TOTAL': 28,
			'Price': 11
	 },
	 'EJ': {
			'Name': 'Grace Tipton',
			'Batting': 6,
			'Running': 10,
			'Pitching': 10,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 30,
			'Price': 21
	 },
	 'EK': {
			'Name': 'Hannah Peavy',
			'Batting': 9,
			'Running': 5,
			'Pitching': 1,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': 'H',
			'TOTAL': 21,
			'Price': 8
	 },
	 'EL': {
			'Name': 'Heather Quinn',
			'Batting': 10,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'I',
			'TOTAL': 24,
			'Price': 14
	 },
	 'EM': {
			'Name': 'Holly Franklin',
			'Batting': 5,
			'Running': 8,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'J',
			'TOTAL': 23,
			'Price': 5
	 },
	 'EN': {
			'Name': 'Isabelle Marelli',
			'Batting': 7,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 22,
			'Price': 4
	 },
	 'EO': {
			'Name': 'Jane Davis',
			'Batting': 10,
			'Running': 9,
			'Pitching': 2,
			'Fielding': 5,
			'Handedness': 'L',
			'Face Type': 'L',
			'TOTAL': 26,
			'Price': 17
	 },
	 'EP': {
			'Name': 'Joella Minotti',
			'Batting': 9,
			'Running': 5,
			'Pitching': 2,
			'Fielding': 2,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 18,
			'Price': 7
	 },
	 'FA': {
			'Name': 'Judy Abwunza',
			'Batting': 3,
			'Running': 8,
			'Pitching': 7,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 22,
			'Price': 6
	 },
	 'FB': {
			'Name': 'Julie Dunkel',
			'Batting': 10,
			'Running': 10,
			'Pitching': 8,
			'Fielding': 7,
			'Handedness': 'L',
			'Face Type': 'I',
			'TOTAL': 35,
			'Price': 26
	 },
	 'FC': {
			'Name': 'Karen Donato',
			'Batting': 8,
			'Running': 7,
			'Pitching': 2,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'J',
			'TOTAL': 20,
			'Price': 6
	 },
	 'FD': {
			'Name': 'Katie Shankar',
			'Batting': 1,
			'Running': 4,
			'Pitching': 5,
			'Fielding': 5,
			'Handedness': '',
			'Face Type': 'K',
			'TOTAL': 15,
			'Price': 3
	 },
	 'FE': {
			'Name': 'Krissy Mulligan',
			'Batting': 5,
			'Running': 3,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'L',
			'TOTAL': 23,
			'Price': 6
	 },
	 'FF': {
			'Name': 'Lara Nunez',
			'Batting': 3,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'M',
			'TOTAL': 23,
			'Price': 6
	 },
	 'FG': {
			'Name': 'Leah Wayne',
			'Batting': 10,
			'Running': 10,
			'Pitching': 9,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 39,
			'Price': 37
	 },
	 'FH': {
			'Name': 'Lena Ng',
			'Batting': 7,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'I',
			'TOTAL': 23,
			'Price': 5
	 },
	 'FI': {
			'Name': 'Linda Potter',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'J',
			'TOTAL': 23,
			'Price': 3
	 },
	 'FJ': {
			'Name': 'Liz Kinghorn',
			'Batting': 4,
			'Running': 9,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 24,
			'Price': 6
	 },
	 'FK': {
			'Name': 'Marianna Rauf',
			'Batting': 7,
			'Running': 4,
			'Pitching': 6,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'L',
			'TOTAL': 27,
			'Price': 13
	 },
	 'FL': {
			'Name': 'Mary Reilly',
			'Batting': 8,
			'Running': 3,
			'Pitching': 4,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 22,
			'Price': 6
	 },
	 'FM': {
			'Name': 'Michiko Adachi',
			'Batting': 5,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 21,
			'Price': 7
	 },
	 'FN': {
			'Name': 'Molly May',
			'Batting': 8,
			'Running': 3,
			'Pitching': 2,
			'Fielding': 9,
			'Handedness': '',
			'Face Type': 'H',
			'TOTAL': 22,
			'Price': 11
	 },
	 'FO': {
			'Name': 'Nancy Chin',
			'Batting': 5,
			'Running': 7,
			'Pitching': 8,
			'Fielding': 6,
			'Handedness': 'L',
			'Face Type': 'I',
			'TOTAL': 26,
			'Price': 7
	 },
	 'FP': {
			'Name': 'Olga Tollefson',
			'Batting': 6,
			'Running': 9,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'J',
			'TOTAL': 25,
			'Price': 8
	 },
	 'GA': {
			'Name': 'Olive Haldi',
			'Batting': 6,
			'Running': 7,
			'Pitching': 2,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 22,
			'Price': 5
	 },
	 'GB': {
			'Name': 'Petra Chekov',
			'Batting': 9,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': 'L',
			'TOTAL': 18,
			'Price': 7
	 },
	 'GC': {
			'Name': 'Ramona Bennett',
			'Batting': 7,
			'Running': 8,
			'Pitching': 8,
			'Fielding': 1,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 24,
			'Price': 10
	 },
	 'GD': {
			'Name': 'Randi Uno',
			'Batting': 7,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'H',
			'TOTAL': 21,
			'Price': 3
	 },
	 'GE': {
			'Name': 'Serena Damonte',
			'Batting': 4,
			'Running': 3,
			'Pitching': 7,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'I',
			'TOTAL': 19,
			'Price': 3
	 },
	 'GF': {
			'Name': 'Sheila Basonte',
			'Batting': 5,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'J',
			'TOTAL': 21,
			'Price': 7
	 },
	 'GG': {
			'Name': 'Sonja Hagen',
			'Batting': 8,
			'Running': 7,
			'Pitching': 6,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 29,
			'Price': 11
	 },
	 'GH': {
			'Name': 'Stacy Gordon',
			'Batting': 7,
			'Running': 3,
			'Pitching': 6,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'L',
			'TOTAL': 19,
			'Price': 3
	 },
	 'GI': {
			'Name': 'Star Moonbeam',
			'Batting': 2,
			'Running': 10,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': 'M',
			'TOTAL': 23,
			'Price': 11
	 },
	 'GJ': {
			'Name': 'Tanya Uchida',
			'Batting': 10,
			'Running': 7,
			'Pitching': 4,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': 'H',
			'TOTAL': 27,
			'Price': 13
	 },
	 'GK': {
			'Name': 'Tiffany Bosworth',
			'Batting': 6,
			'Running': 4,
			'Pitching': 10,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'I',
			'TOTAL': 28,
			'Price': 15
	 },
	 'GL': {
			'Name': 'Tina Herrara',
			'Batting': 3,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'J',
			'TOTAL': 23,
			'Price': 6
	 },
	 'GM': {
			'Name': 'Vanna Steinman',
			'Batting': 5,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 18,
			'Price': 3
	 },
	 'GN': {
			'Name': 'Veronica Lee',
			'Batting': 7,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'L',
			'TOTAL': 26,
			'Price': 11
	 },
	 'GO': {
			'Name': 'Whitney Singh',
			'Batting': 6,
			'Running': 9,
			'Pitching': 7,
			'Fielding': 4,
			'Handedness': 'L',
			'Face Type': 'M',
			'TOTAL': 26,
			'Price': 10
	 },
	 'GP': {
			'Name': 'Zena Fromme',
			'Batting': 10,
			'Running': 6,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'L',
			'TOTAL': 29,
			'Price': 15
	 },
	 'HA': {
			'Name': 'Andres Isben',
			'Batting': 6,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 15,
			'Price': 3
	 },
	 'HB': {
			'Name': 'Artie Pimbleton',
			'Batting': 6,
			'Running': 7,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'C',
			'TOTAL': 23,
			'Price': 5
	 },
	 'HC': {
			'Name': 'Bobby Bulgrien',
			'Batting': 8,
			'Running': 4,
			'Pitching': 9,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 22,
			'Price': 11
	 },
	 'HD': {
			'Name': 'Bret Olsen',
			'Batting': 1,
			'Running': 9,
			'Pitching': 5,
			'Fielding': 10,
			'Handedness': '',
			'Face Type': 'E',
			'TOTAL': 25,
			'Price': 17
	 },
	 'HE': {
			'Name': 'Carlos Ocampo',
			'Batting': 2,
			'Running': 8,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'D',
			'TOTAL': 20,
			'Price': 5
	 },
	 'HF': {
			'Name': 'Chad Koppel',
			'Batting': 4,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'D',
			'TOTAL': 24,
			'Price': 6
	 },
	 'HG': {
			'Name': 'Chico Pappas',
			'Batting': 10,
			'Running': 10,
			'Pitching': 5,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 28,
			'Price': 20
	 },
	 'HH': {
			'Name': 'Chris Milton',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 21,
			'Price': 2
	 },
	 'HI': {
			'Name': 'Chucky Flinder',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 21,
			'Price': 2
	 },
	 'HJ': {
			'Name': 'Davy Marian',
			'Batting': 9,
			'Running': 9,
			'Pitching': 6,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'E',
			'TOTAL': 31,
			'Price': 17
	 },
	 'HK': {
			'Name': 'Dominique Lowe',
			'Batting': 6,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 25,
			'Price': 5
	 },
	 'HL': {
			'Name': 'Earl Abbot',
			'Batting': 6,
			'Running': 10,
			'Pitching': 10,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 30,
			'Price': 21
	 },
	 'HM': {
			'Name': 'Eric Lebeaux',
			'Batting': 9,
			'Running': 5,
			'Pitching': 6,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 21,
			'Price': 8
	 },
	 'HN': {
			'Name': 'Felix Grant',
			'Batting': 10,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'C',
			'TOTAL': 24,
			'Price': 14
	 },
	 'HO': {
			'Name': 'Fernando Diaz',
			'Batting': 5,
			'Running': 8,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'D',
			'TOTAL': 23,
			'Price': 6
	 },
	 'HP': {
			'Name': 'Franky Holly',
			'Batting': 7,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': 'R',
			'Face Type': 'E',
			'TOTAL': 22,
			'Price': 4
	 },
	 'IA': {
			'Name': 'Fred Benson',
			'Batting': 10,
			'Running': 9,
			'Pitching': 2,
			'Fielding': 5,
			'Handedness': 'L',
			'Face Type': 'F',
			'TOTAL': 26,
			'Price': 17
	 },
	 'IB': {
			'Name': 'Gary Allen',
			'Batting': 9,
			'Running': 5,
			'Pitching': 2,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': 'G',
			'TOTAL': 18,
			'Price': 7
	 },
	 'IC': {
			'Name': 'George Coleman',
			'Batting': 3,
			'Running': 8,
			'Pitching': 7,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'B',
			'TOTAL': 22,
			'Price': 6
	 },
	 'ID': {
			'Name': 'Henri Deschenes',
			'Batting': 10,
			'Running': 10,
			'Pitching': 8,
			'Fielding': 7,
			'Handedness': 'L',
			'Face Type': 'C',
			'TOTAL': 35,
			'Price': 26
	 },
	 'IE': {
			'Name': 'Horace Young',
			'Batting': 8,
			'Running': 7,
			'Pitching': 2,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'D',
			'TOTAL': 20,
			'Price': 6
	 },
	 'IF': {
			'Name': 'Ibrahim Muhammed',
			'Batting': 1,
			'Running': 4,
			'Pitching': 5,
			'Fielding': 5,
			'Handedness': '',
			'Face Type': 'E',
			'TOTAL': 15,
			'Price': 6
	 },
	 'IG': {
			'Name': 'Isaac Drummond',
			'Batting': 5,
			'Running': 3,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 23,
			'Price': 6
	 },
	 'IH': {
			'Name': 'Jack Joseph',
			'Batting': 3,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'G',
			'TOTAL': 23,
			'Price': 6
	 },
	 'II': {
			'Name': 'Jay Green',
			'Batting': 10,
			'Running': 10,
			'Pitching': 9,
			'Fielding': 10,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 39,
			'Price': 37
	 },
	 'IJ': {
			'Name': 'Jim Kiley',
			'Batting': 7,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'C',
			'TOTAL': 23,
			'Price': 5
	 },
	 'IK': {
			'Name': 'Johnny Omar',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 5,
			'Handedness': '',
			'Face Type': 'D',
			'TOTAL': 23,
			'Price': 3
	 },
	 'IL': {
			'Name': 'Jordan Thorner',
			'Batting': 4,
			'Running': 9,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'E',
			'TOTAL': 25,
			'Price': 9
	 },
	 'IM': {
			'Name': "Mickey O'Connor",
			'Batting': 7,
			'Running': 4,
			'Pitching': 6,
			'Fielding': 10,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 27,
			'Price': 13
	 },
	 'IN': {
			'Name': 'Murray Goldman',
			'Batting': 8,
			'Running': 3,
			'Pitching': 4,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'G',
			'TOTAL': 22,
			'Price': 6
	 },
	 'IO': {
			'Name': 'Nate Kowalski',
			'Batting': 5,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 21,
			'Price': 7
	 },
	 'IP': {
			'Name': 'Nicky Winston',
			'Batting': 8,
			'Running': 3,
			'Pitching': 2,
			'Fielding': 9,
			'Handedness': '',
			'Face Type': 'C',
			'TOTAL': 22,
			'Price': 9
	 },
	 'JA': {
			'Name': 'Thor Herring',
			'Batting': 3,
			'Running': 1,
			'Pitching': 6,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'D',
			'TOTAL': 13,
			'Price': 3
	 },
	 'JB': {
			'Name': 'Paco Kaufman',
			'Batting': 6,
			'Running': 9,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'E',
			'TOTAL': 25,
			'Price': 9
	 },
	 'JC': {
			'Name': 'PJ Sharoff',
			'Batting': 6,
			'Running': 7,
			'Pitching': 2,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 22,
			'Price': 5
	 },
	 'JD': {
			'Name': 'Rafael Hendrix',
			'Batting': 9,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 18,
			'Price': 7
	 },
	 'JE': {
			'Name': 'Ray Tran',
			'Batting': 7,
			'Running': 8,
			'Pitching': 8,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': 'C',
			'TOTAL': 24,
			'Price': 10
	 },
	 'JF': {
			'Name': 'Robby Bocko',
			'Batting': 7,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 21,
			'Price': 3
	 },
	 'JG': {
			'Name': 'Ryan Vanderhoek',
			'Batting': 4,
			'Running': 3,
			'Pitching': 7,
			'Fielding': 5,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 19,
			'Price': 3
	 },
	 'JH': {
			'Name': 'Shane Smith',
			'Batting': 5,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 21,
			'Price': 7
	 },
	 'JI': {
			'Name': 'Stan Olafson',
			'Batting': 8,
			'Running': 7,
			'Pitching': 6,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'G',
			'TOTAL': 29,
			'Price': 11
	 },
	 'JJ': {
			'Name': 'Stevie Lindt',
			'Batting': 7,
			'Running': 3,
			'Pitching': 6,
			'Fielding': 3,
			'Handedness': 'L',
			'Face Type': 'B',
			'TOTAL': 19,
			'Price': 3
	 },
	 'JK': {
			'Name': 'Stuart Sullivan',
			'Batting': 2,
			'Running': 10,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'C',
			'TOTAL': 23,
			'Price': 11
	 },
	 'JL': {
			'Name': 'Timmy Unger',
			'Batting': 10,
			'Running': 7,
			'Pitching': 4,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 27,
			'Price': 13
	 },
	 'JM': {
			'Name': 'Todd Xavier',
			'Batting': 6,
			'Running': 4,
			'Pitching': 10,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'E',
			'TOTAL': 28,
			'Price': 15
	 },
	 'JN': {
			'Name': 'Vic Soufle',
			'Batting': 3,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 23,
			'Price': 6
	 },
	 'JO': {
			'Name': 'Vladimir Womack',
			'Batting': 5,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'G',
			'TOTAL': 18,
			'Price': 3
	 },
	 'JP': {
			'Name': 'Wally Evans',
			'Batting': 7,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 26,
			'Price': 11
	 },
	 'KA': {
			'Name': 'Wing Kwan',
			'Batting': 5,
			'Running': 9,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'C',
			'TOTAL': 23,
			'Price': 5
	 },
	 'KB': {
			'Name': 'Zenon Estrada',
			'Batting': 10,
			'Running': 6,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': 'G',
			'TOTAL': 29,
			'Price': 15
	 },
	 'KC': {
			'Name': 'Alexis Weis',
			'Batting': 8,
			'Running': 8,
			'Pitching': 7,
			'Fielding': 2,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 25,
			'Price': 10
	 },
	 'KD': {
			'Name': 'Angelique Harding',
			'Batting': 4,
			'Running': 3,
			'Pitching': 9,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'I',
			'TOTAL': 24,
			'Price': 11
	 },
	 'KE': {
			'Name': 'Catherine Asher',
			'Batting': 6,
			'Running': 4,
			'Pitching': 9,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 22,
			'Price': 8
	 },
	 'KF': {
			'Name': 'Clair Nelson',
			'Batting': 3,
			'Running': 4,
			'Pitching': 6,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 14,
			'Price': 3
	 },
	 'KG': {
			'Name': 'Courtney Valentino',
			'Batting': 9,
			'Running': 10,
			'Pitching': 5,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 28,
			'Price': 17
	 },
	 'KH': {
			'Name': 'Dana Sekula',
			'Batting': 3,
			'Running': 3,
			'Pitching': 4,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 14,
			'Price': 3
	 },
	 'KI': {
			'Name': 'Ellen Martinez',
			'Batting': 7,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': 'K',
			'TOTAL': 20,
			'Price': 3
	 },
	 'KJ': {
			'Name': 'Erin Harris',
			'Batting': 5,
			'Running': 6,
			'Pitching': 7,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 19,
			'Price': 3
	 },
	 'KK': {
			'Name': 'Esmarelda Heimann',
			'Batting': 1,
			'Running': 3,
			'Pitching': 7,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 15,
			'Price': 3
	 },
	 'KL': {
			'Name': 'Ezra Travolta',
			'Batting': 6,
			'Running': 6,
			'Pitching': 6,
			'Fielding': 9,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 27,
			'Price': 10
	 },
	 'KM': {
			'Name': 'Fabienne Callahan',
			'Batting': 9,
			'Running': 1,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'J',
			'TOTAL': 21,
			'Price': 8
	 },
	 'KN': {
			'Name': 'Francesca Whitaker',
			'Batting': 8,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': 'K',
			'TOTAL': 27,
			'Price': 8
	 },
	 'KO': {
			'Name': 'Gloria Keitel',
			'Batting': 5,
			'Running': 2,
			'Pitching': 5,
			'Fielding': 9,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 21,
			'Price': 7
	 },
	 'KP': {
			'Name': 'Heidi Thurman',
			'Batting': 1,
			'Running': 2,
			'Pitching': 1,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 8,
			'Price': 3
	 },
	 'LA': {
			'Name': 'Jennifer Goodfellow',
			'Batting': 10,
			'Running': 3,
			'Pitching': 2,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 16,
			'Price': 10
	 },
	 'LB': {
			'Name': 'Jody Palmer',
			'Batting': 2,
			'Running': 7,
			'Pitching': 7,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 20,
			'Price': 4
	 },
	 'LC': {
			'Name': 'Katelyn Cain',
			'Batting': 4,
			'Running': 1,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 18,
			'Price': 4
	 },
	 'LD': {
			'Name': 'Kathy Wolf',
			'Batting': 5,
			'Running': 10,
			'Pitching': 5,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'H',
			'TOTAL': 24,
			'Price': 10
	 },
	 'LE': {
			'Name': 'Lindsey Felgate',
			'Batting': 10,
			'Running': 10,
			'Pitching': 7,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'K',
			'TOTAL': 30,
			'Price': 22
	 },
	 'LF': {
			'Name': 'Lorelei Ikaye',
			'Batting': 10,
			'Running': 7,
			'Pitching': 4,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'L',
			'TOTAL': 26,
			'Price': 14
	 },
	 'LG': {
			'Name': 'Mamie Skiumsby',
			'Batting': 8,
			'Running': 4,
			'Pitching': 6,
			'Fielding': 8,
			'Handedness': 'L',
			'Face Type': 'M',
			'TOTAL': 26,
			'Price': 9
	 },
	 'LH': {
			'Name': 'Metessa Sturges',
			'Batting': 9,
			'Running': 6,
			'Pitching': 10,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 28,
			'Price': 17
	 },
	 'LI': {
			'Name': 'Rosanna Phelps',
			'Batting': 3,
			'Running': 7,
			'Pitching': 6,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 23,
			'Price': 5
	 },
	 'LJ': {
			'Name': 'Ruth Proutt',
			'Batting': 8,
			'Running': 9,
			'Pitching': 4,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'I',
			'TOTAL': 24,
			'Price': 11
	 },
	 'LK': {
			'Name': 'Samantha Winslow',
			'Batting': 7,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 22,
			'Price': 6
	 },
	 'LL': {
			'Name': 'Tatiana Jackson',
			'Batting': 7,
			'Running': 7,
			'Pitching': 6,
			'Fielding': 4,
			'Handedness': 'L',
			'Face Type': 'K',
			'TOTAL': 24,
			'Price': 5
	 },
	 'LM': {
			'Name': 'Tracy Hoban',
			'Batting': 5,
			'Running': 4,
			'Pitching': 5,
			'Fielding': 9,
			'Handedness': 'L',
			'Face Type': 'K',
			'TOTAL': 23,
			'Price': 7
	 },
	 'LN': {
			'Name': 'Uma Morris',
			'Batting': 7,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 24,
			'Price': 4
	 },
	 'LO': {
			'Name': 'Vanessa Goodman',
			'Batting': 5,
			'Running': 7,
			'Pitching': 4,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 17,
			'Price': 3
	 },
	 'LP': {
			'Name': 'Victoria Shamberg',
			'Batting': 2,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 12,
			'Price': 3
	 },
	 'MA': {
			'Name': 'Adam Van Doren',
			'Batting': 7,
			'Running': 10,
			'Pitching': 3,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'G',
			'TOTAL': 23,
			'Price': 12
	 },
	 'MB': {
			'Name': 'Adrian McGurk',
			'Batting': 7,
			'Running': 4,
			'Pitching': 10,
			'Fielding': 1,
			'Handedness': 'R',
			'Face Type': 'B',
			'TOTAL': 22,
			'Price': 12
	 },
	 'MC': {
			'Name': 'Billy Mendelson',
			'Batting': 5,
			'Running': 6,
			'Pitching': 6,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 18,
			'Price': 3
	 },
	 'MD': {
			'Name': 'Ben Olds',
			'Batting': 2,
			'Running': 4,
			'Pitching': 2,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 15,
			'Price': 3
	 },
	 'ME': {
			'Name': 'Buddy Martin',
			'Batting': 2,
			'Running': 4,
			'Pitching': 6,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 18,
			'Price': 3
	 },
	 'MF': {
			'Name': 'Butch Sherrod',
			'Batting': 4,
			'Running': 3,
			'Pitching': 6,
			'Fielding': 10,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 23,
			'Price': 11
	 },
	 'MG': {
			'Name': 'Cameron Haines',
			'Batting': 1,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 13,
			'Price': 3
	 },
	 'MH': {
			'Name': 'Chandler Huggins',
			'Batting': 5,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 20,
			'Price': 7
	 },
	 'MI': {
			'Name': 'Daniel Willis',
			'Batting': 5,
			'Running': 6,
			'Pitching': 2,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 14,
			'Price': 3
	 },
	 'MJ': {
			'Name': 'Derek McCattery',
			'Batting': 7,
			'Running': 8,
			'Pitching': 9,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 26,
			'Price': 13
	 },
	 'MK': {
			'Name': 'Donald Vogel',
			'Batting': 4,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': '',
			'TOTAL': 22,
			'Price': 3
	 },
	 'ML': {
			'Name': 'Guiseppe Prochaska',
			'Batting': 8,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 19,
			'Price': 4
	 },
	 'MM': {
			'Name': 'Ivan King',
			'Batting': 1,
			'Running': 1,
			'Pitching': 2,
			'Fielding': 1,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 5,
			'Price': 3
	 },
	 'MN': {
			'Name': 'Jerry Winchell',
			'Batting': 9,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 27,
			'Price': 10
	 },
	 'MO': {
			'Name': 'Jose Meisenheimer',
			'Batting': 7,
			'Running': 1,
			'Pitching': 8,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 24,
			'Price': 10
	 },
	 'MP': {
			'Name': 'Lance Lambert',
			'Batting': 9,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'C',
			'TOTAL': 27,
			'Price': 10
	 },
	 'NA': {
			'Name': 'Marsellus Marx',
			'Batting': 10,
			'Running': 10,
			'Pitching': 6,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': 'B',
			'TOTAL': 32,
			'Price': 22
	 },
	 'NB': {
			'Name': 'Matthew La Cruz',
			'Batting': 5,
			'Running': 6,
			'Pitching': 1,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 14,
			'Price': 3
	 },
	 'NC': {
			'Name': 'Maynard Mcelroy',
			'Batting': 5,
			'Running': 10,
			'Pitching': 5,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': 'F',
			'TOTAL': 24,
			'Price': 10
	 },
	 'ND': {
			'Name': 'Melvin Berger',
			'Batting': 4,
			'Running': 5,
			'Pitching': 4,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 15,
			'Price': 3
	 },
	 'NE': {
			'Name': 'Parker Collum',
			'Batting': 9,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 4,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 22,
			'Price': 8
	 },
	 'NF': {
			'Name': 'Ron Bourne',
			'Batting': 5,
			'Running': 2,
			'Pitching': 8,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 22,
			'Price': 6
	 },
	 'NG': {
			'Name': 'Quentin Driver',
			'Batting': 1,
			'Running': 1,
			'Pitching': 1,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 5,
			'Price': 3
	 },
	 'NH': {
			'Name': 'Rafael Garbonzos',
			'Batting': 9,
			'Running': 2,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 24,
			'Price': 11
	 },
	 'NI': {
			'Name': 'Robert Young',
			'Batting': 10,
			'Running': 5,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': 'L',
			'Face Type': 'D',
			'TOTAL': 30,
			'Price': 16
	 },
	 'NJ': {
			'Name': 'Scotty Roth',
			'Batting': 5,
			'Running': 8,
			'Pitching': 2,
			'Fielding': 5,
			'Handedness': '',
			'Face Type': 'G',
			'TOTAL': 20,
			'Price': 4
	 },
	 'NK': {
			'Name': 'Terry Vega',
			'Batting': 6,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'C',
			'TOTAL': 19,
			'Price': 3
	 },
	 'NL': {
			'Name': 'Vincent Sweet',
			'Batting': 4,
			'Running': 5,
			'Pitching': 5,
			'Fielding': 9,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 23,
			'Price': 7
	 },
	 'NM': {
			'Name': 'Walter Hall',
			'Batting': 5,
			'Running': 2,
			'Pitching': 7,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 16,
			'Price': 3
	 },
	 'NN': {
			'Name': 'Wayne Pitman',
			'Batting': 3,
			'Running': 1,
			'Pitching': 4,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 10,
			'Price': 3
	 },
	 'NO': {
			'Name': 'Peggy Heffernan',
			'Batting': 9,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 27,
			'Price': 12
	 },
	 'NP': {
			'Name': 'Kendra Yarbrough',
			'Batting': 5,
			'Running': 2,
			'Pitching': 7,
			'Fielding': 2,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 16,
			'Price': 10
	 },
	 'OA': {
			'Name': 'Berit Greenwalt',
			'Batting': 1,
			'Running': 1,
			'Pitching': 3,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'I',
			'TOTAL': 15,
			'Price': 10
	 },
	 'OB': {
			'Name': 'Rose Fluegel',
			'Batting': 9,
			'Running': 2,
			'Pitching': 5,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 21,
			'Price': 7
	 },
	 'OC': {
			'Name': 'Maya Woodruff',
			'Batting': 10,
			'Running': 5,
			'Pitching': 2,
			'Fielding': 7,
			'Handedness': 'L',
			'Face Type': 'K',
			'TOTAL': 24,
			'Price': 12
	 },
	 'OD': {
			'Name': 'Trent Sizemore',
			'Batting': 5,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'G',
			'TOTAL': 28,
			'Price': 14
	 },
	 'OE': {
			'Name': 'Perry Marx',
			'Batting': 7,
			'Running': 4,
			'Pitching': 6,
			'Fielding': 3,
			'Handedness': '',
			'Face Type': 'C',
			'TOTAL': 20,
			'Price': 3
	 },
	 'OF': {
			'Name': 'Dominic Hoskins',
			'Batting': 4,
			'Running': 5,
			'Pitching': 8,
			'Fielding': 8,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 25,
			'Price': 8
	 },
	 'OG': {
			'Name': 'Umberto Ander',
			'Batting': 5,
			'Running': 2,
			'Pitching': 7,
			'Fielding': 7,
			'Handedness': '',
			'Face Type': '',
			'TOTAL': 21,
			'Price': 4
	 },
	 'OH': {
			'Name': 'Tom Glass',
			'Batting': 5,
			'Running': 7,
			'Pitching': 8,
			'Fielding': 6,
			'Handedness': '',
			'Face Type': 'D',
			'TOTAL': 26,
			'Price': 7
	 },
	 'OI': {
			'Name': 'Alicia Blakely',
			'Batting': 8,
			'Running': 8,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 26,
			'Price': 10
	 },
	 'OJ': {
			'Name': 'Amanda Hellerman',
			'Batting': 5,
			'Running': 5,
			'Pitching': 10,
			'Fielding': 3,
			'Handedness': 'R/L',
			'Face Type': 'I',
			'TOTAL': 23,
			'Price': 10
	 },
	 'OK': {
			'Name': 'Anna Goudreau',
			'Batting': 8,
			'Running': 7,
			'Pitching': 4,
			'Fielding': 8,
			'Handedness': 'S/R',
			'Face Type': 'J',
			'TOTAL': 27,
			'Price': 10
	 },
	 'OL': {
			'Name': 'Barbara Jones',
			'Batting': 8,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 24,
			'Price': 7
	 },
	 'OM': {
			'Name': 'Brenda Markart',
			'Batting': 8,
			'Running': 7,
			'Pitching': 7,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'L',
			'TOTAL': 32,
			'Price': 18
	 },
	 'ON': {
			'Name': 'Cheryl Reynolds',
			'Batting': 10,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 30,
			'Price': 16
	 },
	 'OO': {
			'Name': 'Christina Beattie',
			'Batting': 7,
			'Running': 4,
			'Pitching': 10,
			'Fielding': 4,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 25,
			'Price': 12
	 },
	 'OP': {
			'Name': 'Claudia Villarta',
			'Batting': 9,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 10,
			'Handedness': 'L',
			'Face Type': 'I',
			'TOTAL': 32,
			'Price': 21
	 },
	 'PA': {
			'Name': 'Dawn Cozart',
			'Batting': 8,
			'Running': 5,
			'Pitching': 4,
			'Fielding': 6,
			'Handedness': 'L/R',
			'Face Type': 'J',
			'TOTAL': 23,
			'Price': 5
	 },
	 'PB': {
			'Name': 'Emily Lewbel',
			'Batting': 9,
			'Running': 4,
			'Pitching': 3,
			'Fielding': 10,
			'Handedness': 'L',
			'Face Type': 'K',
			'TOTAL': 26,
			'Price': 17
	 },
	 'PC': {
			'Name': 'Fay Dawson',
			'Batting': 7,
			'Running': 8,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': 'L/R',
			'Face Type': 'L',
			'TOTAL': 27,
			'Price': 13
	 },
	 'PD': {
			'Name': 'Gwen Sears',
			'Batting': 8,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'L/R',
			'Face Type': 'M',
			'TOTAL': 27,
			'Price': 13
	 },
	 'PE': {
			'Name': 'Hillary Vargas',
			'Batting': 8,
			'Running': 6,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 26,
			'Price': 12
	 },
	 'PF': {
			'Name': 'Ingrid Dahlman',
			'Batting': 5,
			'Running': 7,
			'Pitching': 5,
			'Fielding': 8,
			'Handedness': 'S/R',
			'Face Type': 'I',
			'TOTAL': 25,
			'Price': 6
	 },
	 'PG': {
			'Name': 'Jessica Wassersas',
			'Batting': 8,
			'Running': 7,
			'Pitching': 7,
			'Fielding': 5,
			'Handedness': 'L',
			'Face Type': 'J',
			'TOTAL': 27,
			'Price': 8
	 },
	 'PH': {
			'Name': 'Jillian Paine',
			'Batting': 7,
			'Running': 6,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 24,
			'Price': 4
	 },
	 'PI': {
			'Name': 'Kristen Sullivan',
			'Batting': 2,
			'Running': 7,
			'Pitching': 8,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'L',
			'TOTAL': 25,
			'Price': 10
	 },
	 'PJ': {
			'Name': "Kay O'Toole",
			'Batting': 8,
			'Running': 8,
			'Pitching': 5,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 27,
			'Price': 10
	 },
	 'PK': {
			'Name': 'Libby Futterman',
			'Batting': 9,
			'Running': 3,
			'Pitching': 3,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'H',
			'TOTAL': 23,
			'Price': 11
	 },
	 'PL': {
			'Name': 'Marilyn McDonnell',
			'Batting': 8,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 10,
			'Handedness': 'R',
			'Face Type': 'I',
			'TOTAL': 30,
			'Price': 21
	 },
	 'PM': {
			'Name': 'Melissa Waters',
			'Batting': 4,
			'Running': 5,
			'Pitching': 8,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'J',
			'TOTAL': 22,
			'Price': 4
	 },
	 'PN': {
			'Name': 'Nan Porter',
			'Batting': 6,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 7,
			'Handedness': 'S/R',
			'Face Type': 'K',
			'TOTAL': 25,
			'Price': 10
	 },
	 'PO': {
			'Name': 'Pamela Kirkos',
			'Batting': 7,
			'Running': 8,
			'Pitching': 4,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'L',
			'TOTAL': 26,
			'Price': 8
	 },
	 'PP': {
			'Name': 'Raquel Cullen',
			'Batting': 9,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 5,
			'Handedness': 'R',
			'Face Type': 'M',
			'TOTAL': 24,
			'Price': 8
	 },
	 'QA': {
			'Name': 'Sarah Maxwell',
			'Batting': 8,
			'Running': 10,
			'Pitching': 6,
			'Fielding': 9,
			'Handedness': 'L',
			'Face Type': 'H',
			'TOTAL': 33,
			'Price': 22
	 },
	 'QB': {
			'Name': 'Susan Gore',
			'Batting': 8,
			'Running': 10,
			'Pitching': 2,
			'Fielding': 10,
			'Handedness': 'L/R',
			'Face Type': 'I',
			'TOTAL': 30,
			'Price': 24
	 },
	 'QC': {
			'Name': 'Sophie Meyer',
			'Batting': 8,
			'Running': 4,
			'Pitching': 8,
			'Fielding': 7,
			'Handedness': 'R',
			'Face Type': 'J',
			'TOTAL': 27,
			'Price': 10
	 },
	 'QD': {
			'Name': 'Tonya Lesco',
			'Batting': 7,
			'Running': 5,
			'Pitching': 4,
			'Fielding': 8,
			'Handedness': 'R',
			'Face Type': 'K',
			'TOTAL': 24,
			'Price': 6
	 },
	 'QE': {
			'Name': 'Wendy Parsons',
			'Batting': 7,
			'Running': 9,
			'Pitching': 3,
			'Fielding': 9,
			'Handedness': 'R',
			'Face Type': 'L',
			'TOTAL': 28,
			'Price': 16
	 },
	 'QF': {
			'Name': 'Yvonne Carter',
			'Batting': 8,
			'Running': 5,
			'Pitching': 8,
			'Fielding': 7,
			'Handedness': 'L/R',
			'Face Type': 'M',
			'TOTAL': 28,
			'Price': 10
	 },
	 'QG': {
			'Name': 'Zoe Mallory',
			'Batting': 7,
			'Running': 4,
			'Pitching': 7,
			'Fielding': 8,
			'Handedness': 'L/R',
			'Face Type': 'H',
			'TOTAL': 26,
			'Price': 8
	 },
	 'QH': {
			'Name': 'Mr. Clanky',
			'Batting': 8,
			'Running': 6,
			'Pitching': 10,
			'Fielding': 6,
			'Handedness': 'R',
			'Face Type': 'unique',
			'TOTAL': 30,
			'Price': 16
	 },
	 'QI': {
			'Name': 'Ruby Diamond',
			'Batting': 6,
			'Running': 6,
			'Pitching': 4,
			'Fielding': 7,
			'Handedness': '-',
			'Face Type': '-',
			'TOTAL': 0,
			'Price': 0
	 },
   'QI': {
      'Name': 'Garbage McGee',
      'Batting': 6,
      'Running': 6,
      'Pitching': 4,
      'Fielding': 7,
      'Handedness': '-',
      'Face Type': '-',
      'TOTAL': 0,
      'Price': 0
   },
}
}
