// http://www.convertcsv.com/csv-to-json.htm

const s1302teams = {
    "Gauchos": "<@&702678421423128637>",
    "Ostriches": "<@&496817420753960961>",
    "Reapers": "<@&496817127668580362>",
    "Nine": "<@&493888943754838036>",
    "Penguins": "<@&703669468768895206>",
    "Bells": "<@&1067672079060713512>",
    "Oxs": "<@&702678271749390457>",
    "Rockers": "<@&1224278068495908874>",
    "Dragons": "<@&484763804236906497>",
    "Mets": "<@&847666608852041778>",
    "Trojans": "<@&1067528046451642418>",
    "Blue Jays": "<@&1306532385982255125>",
    "Oysters": "<@&1224471696820670616>",
    "Grebes": "<@&1224784681166438540>",
    "Mariners": "<@&496815444116635658>",
    "Hornets": "<@&603606321492787210>",
    "Giants": "<@&1306528207994093639>",
    "Red Sox": "<@&1067536861570023424>",
    "Athletics": "<@&847666595748249640>",
    "Skeeters": "<@&847665786708688936>",
    "Teens": "<@&1071144968435028049>",
    "Vaqueros": "<@&1306533265422680156>",
    "Iguanas": "<@&1224267311993716770>",
    "Dice": "<@&1306532649573285888>",
    
};

//"game": "1",
//"away_team": "As",
//"away_code": "NF",
//"home_team": "Red Sox",
//"home_code": "XD"

const s1302schedule =[
    { "game": 1, "away_team": "Gauchos", "away_code": "CS", "home_team": "Reapers", "home_code": "DG" },
{ "game": 1, "away_team": "Ostriches", "away_code": "NV", "home_team": "Blue Jays", "home_code": "TT" },
{ "game": 1, "away_team": "Penguins", "away_code": "GB", "home_team": "Rockers", "home_code": "AD" },
{ "game": 1, "away_team": "Dragons", "away_code": "FJ", "home_team": "Bells", "home_code": "SB" },
{ "game": 1, "away_team": "Nine", "away_code": "JK", "home_team": "Mets", "home_code": "MK" },
{ "game": 1, "away_team": "Oxs", "away_code": "05", "home_team": "Trojans", "home_code": "DK" },
{ "game": 1, "away_team": "Oysters", "away_code": "JR", "home_team": "Athletics", "home_code": "JL" },
{ "game": 1, "away_team": "Hornets", "away_code": "WW", "home_team": "Vaqueros", "home_code": "CC" },
{ "game": 1, "away_team": "Teens", "away_code": "DA", "home_team": "Giants", "home_code": "CU" },
{ "game": 1, "away_team": "Grebes", "away_code": "FF", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 1, "away_team": "Red Sox", "away_code": "NP", "home_team": "Dice", "home_code": "WS" },
{ "game": 1, "away_team": "Iguanas", "away_code": "OB", "home_team": "Mariners", "home_code": "YZ" },
{ "game": 2, "away_team": "Reapers", "away_code": "DG", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 2, "away_team": "Rockers", "away_code": "AD", "home_team": "Gauchos", "home_code": "CS" },
{ "game": 2, "away_team": "Bells", "away_code": "SB", "home_team": "Oxs", "home_code": "05" },
{ "game": 2, "away_team": "Penguins", "away_code": "GB", "home_team": "Nine", "home_code": "JK" },
{ "game": 2, "away_team": "Mets", "away_code": "MK", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 2, "away_team": "Blue Jays", "away_code": "TT", "home_team": "Trojans", "home_code": "DK" },
{ "game": 2, "away_team": "Dice", "away_code": "WS", "home_team": "Grebes", "home_code": "FF" },
{ "game": 2, "away_team": "Giants", "away_code": "CU", "home_team": "Hornets", "home_code": "WW" },
{ "game": 2, "away_team": "Mariners", "away_code": "YZ", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 2, "away_team": "Athletics", "away_code": "JL", "home_team": "Teens", "home_code": "DA" },
{ "game": 2, "away_team": "Skeeters", "away_code": "MC", "home_team": "Iguanas", "home_code": "OB" },
{ "game": 2, "away_team": "Vaqueros", "away_code": "CC", "home_team": "Oysters", "home_code": "JR" },
{ "game": 3, "away_team": "Reapers", "away_code": "DG", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 3, "away_team": "Gauchos", "away_code": "CS", "home_team": "Blue Jays", "home_code": "TT" },
{ "game": 3, "away_team": "Dragons", "away_code": "FJ", "home_team": "Penguins", "home_code": "GB" },
{ "game": 3, "away_team": "Trojans", "away_code": "DK", "home_team": "Bells", "home_code": "SB" },
{ "game": 3, "away_team": "Nine", "away_code": "JK", "home_team": "Rockers", "home_code": "AD" },
{ "game": 3, "away_team": "Oxs", "away_code": "05", "home_team": "Mets", "home_code": "MK" },
{ "game": 3, "away_team": "Iguanas", "away_code": "OB", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 3, "away_team": "Athletics", "away_code": "JL", "home_team": "Giants", "home_code": "CU" },
{ "game": 3, "away_team": "Vaqueros", "away_code": "CC", "home_team": "Mariners", "home_code": "YZ" },
{ "game": 3, "away_team": "Dice", "away_code": "WS", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 3, "away_team": "Hornets", "away_code": "WW", "home_team": "Oysters", "home_code": "JR" },
{ "game": 3, "away_team": "Teens", "away_code": "DA", "home_team": "Grebes", "home_code": "FF" },
{ "game": 4, "away_team": "Bells", "away_code": "SB", "home_team": "Reapers", "home_code": "DG" },
{ "game": 4, "away_team": "Ostriches", "away_code": "NV", "home_team": "Nine", "home_code": "JK" },
{ "game": 4, "away_team": "Penguins", "away_code": "GB", "home_team": "Gauchos", "home_code": "CS" },
{ "game": 4, "away_team": "Blue Jays", "away_code": "TT", "home_team": "Oxs", "home_code": "05" },
{ "game": 4, "away_team": "Rockers", "away_code": "AD", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 4, "away_team": "Mets", "away_code": "MK", "home_team": "Trojans", "home_code": "DK" },
{ "game": 4, "away_team": "Teens", "away_code": "DA", "home_team": "Dice", "home_code": "WS" },
{ "game": 4, "away_team": "Iguanas", "away_code": "OB", "home_team": "Vaqueros", "home_code": "CC" },
{ "game": 4, "away_team": "Hornets", "away_code": "WW", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 4, "away_team": "Red Sox", "away_code": "NP", "home_team": "Athletics", "home_code": "JL" },
{ "game": 4, "away_team": "Oysters", "away_code": "JR", "home_team": "Mariners", "home_code": "YZ" },
{ "game": 4, "away_team": "Grebes", "away_code": "FF", "home_team": "Giants", "home_code": "CU" },
{ "game": 5, "away_team": "Trojans", "away_code": "DK", "home_team": "Reapers", "home_code": "DG" },
{ "game": 5, "away_team": "Blue Jays", "away_code": "TT", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 5, "away_team": "Nine", "away_code": "JK", "home_team": "Bells", "home_code": "SB" },
{ "game": 5, "away_team": "Oxs", "away_code": "05", "home_team": "Penguins", "home_code": "GB" },
{ "game": 5, "away_team": "Ostriches", "away_code": "NV", "home_team": "Rockers", "home_code": "AD" },
{ "game": 5, "away_team": "Mets", "away_code": "MK", "home_team": "Gauchos", "home_code": "CS" },
{ "game": 5, "away_team": "Giants", "away_code": "CU", "home_team": "Oysters", "home_code": "JR" },
{ "game": 5, "away_team": "Mariners", "away_code": "YZ", "home_team": "Grebes", "home_code": "FF" },
{ "game": 5, "away_team": "Athletics", "away_code": "JL", "home_team": "Hornets", "home_code": "WW" },
{ "game": 5, "away_team": "Skeeters", "away_code": "MC", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 5, "away_team": "Vaqueros", "away_code": "CC", "home_team": "Teens", "home_code": "DA" },
{ "game": 5, "away_team": "Dice", "away_code": "WS", "home_team": "Iguanas", "home_code": "OB" },
{ "game": 6, "away_team": "Reapers", "away_code": "DG", "home_team": "Oxs", "home_code": "05" },
{ "game": 6, "away_team": "Bells", "away_code": "SB", "home_team": "Blue Jays", "home_code": "TT" },
{ "game": 6, "away_team": "Penguins", "away_code": "GB", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 6, "away_team": "Gauchos", "away_code": "CS", "home_team": "Nine", "home_code": "JK" },
{ "game": 6, "away_team": "Dragons", "away_code": "FJ", "home_team": "Trojans", "home_code": "DK" },
{ "game": 6, "away_team": "Rockers", "away_code": "AD", "home_team": "Mets", "home_code": "MK" },
{ "game": 6, "away_team": "Oysters", "away_code": "JR", "home_team": "Iguanas", "home_code": "OB" },
{ "game": 6, "away_team": "Grebes", "away_code": "FF", "home_team": "Hornets", "home_code": "WW" },
{ "game": 6, "away_team": "Red Sox", "away_code": "NP", "home_team": "Teens", "home_code": "DA" },
{ "game": 6, "away_team": "Giants", "away_code": "CU", "home_team": "Dice", "home_code": "WS" },
{ "game": 6, "away_team": "Mariners", "away_code": "YZ", "home_team": "Athletics", "home_code": "JL" },
{ "game": 6, "away_team": "Skeeters", "away_code": "MC", "home_team": "Vaqueros", "home_code": "CC" },
{ "game": 7, "away_team": "Reapers", "away_code": "DG", "home_team": "Mets", "home_code": "MK" },
{ "game": 7, "away_team": "Rockers", "away_code": "AD", "home_team": "Blue Jays", "home_code": "TT" },
{ "game": 7, "away_team": "Bells", "away_code": "SB", "home_team": "Penguins", "home_code": "GB" },
{ "game": 7, "away_team": "Oxs", "away_code": "05", "home_team": "Nine", "home_code": "JK" },
{ "game": 7, "away_team": "Dragons", "away_code": "FJ", "home_team": "Gauchos", "home_code": "CS" },
{ "game": 7, "away_team": "Trojans", "away_code": "DK", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 7, "away_team": "Vaqueros", "away_code": "CC", "home_team": "Dice", "home_code": "WS" },
{ "game": 7, "away_team": "Iguanas", "away_code": "OB", "home_team": "Teens", "home_code": "DA" },
{ "game": 7, "away_team": "Athletics", "away_code": "JL", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 7, "away_team": "Hornets", "away_code": "WW", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 7, "away_team": "Mariners", "away_code": "YZ", "home_team": "Giants", "home_code": "CU" },
{ "game": 7, "away_team": "Oysters", "away_code": "JR", "home_team": "Grebes", "home_code": "FF" },
{ "game": 8, "away_team": "Blue Jays", "away_code": "TT", "home_team": "Reapers", "home_code": "DG" },
{ "game": 8, "away_team": "Ostriches", "away_code": "NV", "home_team": "Gauchos", "home_code": "CS" },
{ "game": 8, "away_team": "Mets", "away_code": "MK", "home_team": "Penguins", "home_code": "GB" },
{ "game": 8, "away_team": "Oxs", "away_code": "05", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 8, "away_team": "Rockers", "away_code": "AD", "home_team": "Bells", "home_code": "SB" },
{ "game": 8, "away_team": "Nine", "away_code": "JK", "home_team": "Trojans", "home_code": "DK" },
{ "game": 8, "away_team": "Grebes", "away_code": "FF", "home_team": "Athletics", "home_code": "JL" },
{ "game": 8, "away_team": "Giants", "away_code": "CU", "home_team": "Iguanas", "home_code": "OB" },
{ "game": 8, "away_team": "Teens", "away_code": "DA", "home_team": "Mariners", "home_code": "YZ" },
{ "game": 8, "away_team": "Vaqueros", "away_code": "CC", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 8, "away_team": "Skeeters", "away_code": "MC", "home_team": "Oysters", "home_code": "JR" },
{ "game": 8, "away_team": "Dice", "away_code": "WS", "home_team": "Hornets", "home_code": "WW" },
{ "game": 9, "away_team": "Penguins", "away_code": "GB", "home_team": "Reapers", "home_code": "DG" },
{ "game": 9, "away_team": "Ostriches", "away_code": "NV", "home_team": "Oxs", "home_code": "05" },
{ "game": 9, "away_team": "Nine", "away_code": "JK", "home_team": "Blue Jays", "home_code": "TT" },
{ "game": 9, "away_team": "Gauchos", "away_code": "CS", "home_team": "Bells", "home_code": "SB" },
{ "game": 9, "away_team": "Mets", "away_code": "MK", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 9, "away_team": "Trojans", "away_code": "DK", "home_team": "Rockers", "home_code": "AD" },
{ "game": 9, "away_team": "Oysters", "away_code": "JR", "home_team": "Teens", "home_code": "DA" },
{ "game": 9, "away_team": "Red Sox", "away_code": "NP", "home_team": "Grebes", "home_code": "FF" },
{ "game": 9, "away_team": "Iguanas", "away_code": "OB", "home_team": "Hornets", "home_code": "WW" },
{ "game": 9, "away_team": "Giants", "away_code": "CU", "home_team": "Vaqueros", "home_code": "CC" },
{ "game": 9, "away_team": "Mariners", "away_code": "YZ", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 9, "away_team": "Athletics", "away_code": "JL", "home_team": "Dice", "home_code": "WS" },
{ "game": 10, "away_team": "Reapers", "away_code": "DG", "home_team": "Gauchos", "home_code": "CS" },
{ "game": 10, "away_team": "Blue Jays", "away_code": "TT", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 10, "away_team": "Trojans", "away_code": "DK", "home_team": "Penguins", "home_code": "GB" },
{ "game": 10, "away_team": "Bells", "away_code": "SB", "home_team": "Mets", "home_code": "MK" },
{ "game": 10, "away_team": "Dragons", "away_code": "FJ", "home_team": "Nine", "home_code": "JK" },
{ "game": 10, "away_team": "Oxs", "away_code": "05", "home_team": "Rockers", "home_code": "AD" },
{ "game": 10, "away_team": "Red Sox", "away_code": "NP", "home_team": "Giants", "home_code": "CU" },
{ "game": 10, "away_team": "Teens", "away_code": "DA", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 10, "away_team": "Iguanas", "away_code": "OB", "home_team": "Athletics", "home_code": "JL" },
{ "game": 10, "away_team": "Dice", "away_code": "WS", "home_team": "Oysters", "home_code": "JR" },
{ "game": 10, "away_team": "Vaqueros", "away_code": "CC", "home_team": "Grebes", "home_code": "FF" },
{ "game": 10, "away_team": "Hornets", "away_code": "WW", "home_team": "Mariners", "home_code": "YZ" },
{ "game": 11, "away_team": "Rockers", "away_code": "AD", "home_team": "Reapers", "home_code": "DG" },
{ "game": 11, "away_team": "Gauchos", "away_code": "CS", "home_team": "Trojans", "home_code": "DK" },
{ "game": 11, "away_team": "Oxs", "away_code": "05", "home_team": "Bells", "home_code": "SB" },
{ "game": 11, "away_team": "Nine", "away_code": "JK", "home_team": "Penguins", "home_code": "GB" },
{ "game": 11, "away_team": "Ostriches", "away_code": "NV", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 11, "away_team": "Mets", "away_code": "MK", "home_team": "Blue Jays", "home_code": "TT" },
{ "game": 11, "away_team": "Skeeters", "away_code": "MC", "home_team": "Hornets", "home_code": "WW" },
{ "game": 11, "away_team": "Athletics", "away_code": "JL", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 11, "away_team": "Mariners", "away_code": "YZ", "home_team": "Oysters", "home_code": "JR" },
{ "game": 11, "away_team": "Giants", "away_code": "CU", "home_team": "Grebes", "home_code": "FF" },
{ "game": 11, "away_team": "Dice", "away_code": "WS", "home_team": "Teens", "home_code": "DA" },
{ "game": 11, "away_team": "Vaqueros", "away_code": "CC", "home_team": "Iguanas", "home_code": "OB" },
{ "game": 12, "away_team": "Reapers", "away_code": "DG", "home_team": "Nine", "home_code": "JK" },
{ "game": 12, "away_team": "Bells", "away_code": "SB", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 12, "away_team": "Blue Jays", "away_code": "TT", "home_team": "Penguins", "home_code": "GB" },
{ "game": 12, "away_team": "Gauchos", "away_code": "CS", "home_team": "Oxs", "home_code": "05" },
{ "game": 12, "away_team": "Dragons", "away_code": "FJ", "home_team": "Rockers", "home_code": "AD" },
{ "game": 12, "away_team": "Trojans", "away_code": "DK", "home_team": "Mets", "home_code": "MK" },
{ "game": 12, "away_team": "Oysters", "away_code": "JR", "home_team": "Giants", "home_code": "CU" },
{ "game": 12, "away_team": "Grebes", "away_code": "FF", "home_team": "Mariners", "home_code": "YZ" },
{ "game": 12, "away_team": "Hornets", "away_code": "WW", "home_team": "Athletics", "home_code": "JL" },
{ "game": 12, "away_team": "Red Sox", "away_code": "NP", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 12, "away_team": "Teens", "away_code": "DA", "home_team": "Vaqueros", "home_code": "CC" },
{ "game": 12, "away_team": "Iguanas", "away_code": "OB", "home_team": "Dice", "home_code": "WS" },
{ "game": 13, "away_team": "Ostriches", "away_code": "NV", "home_team": "Reapers", "home_code": "DG" },
{ "game": 13, "away_team": "Blue Jays", "away_code": "TT", "home_team": "Gauchos", "home_code": "CS" },
{ "game": 13, "away_team": "Bells", "away_code": "SB", "home_team": "Nine", "home_code": "JK" },
{ "game": 13, "away_team": "Penguins", "away_code": "GB", "home_team": "Oxs", "home_code": "05" },
{ "game": 13, "away_team": "Trojans", "away_code": "DK", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 13, "away_team": "Mets", "away_code": "MK", "home_team": "Rockers", "home_code": "AD" },
{ "game": 13, "away_team": "Oysters", "away_code": "JR", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 13, "away_team": "Grebes", "away_code": "FF", "home_team": "Iguanas", "home_code": "OB" },
{ "game": 13, "away_team": "Hornets", "away_code": "WW", "home_team": "Teens", "home_code": "DA" },
{ "game": 13, "away_team": "Skeeters", "away_code": "MC", "home_team": "Giants", "home_code": "CU" },
{ "game": 13, "away_team": "Athletics", "away_code": "JL", "home_team": "Vaqueros", "home_code": "CC" },
{ "game": 13, "away_team": "Mariners", "away_code": "YZ", "home_team": "Dice", "home_code": "WS" },
{ "game": 14, "away_team": "Reapers", "away_code": "DG", "home_team": "Blue Jays", "home_code": "TT" },
{ "game": 14, "away_team": "Gauchos", "away_code": "CS", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 14, "away_team": "Penguins", "away_code": "GB", "home_team": "Bells", "home_code": "SB" },
{ "game": 14, "away_team": "Nine", "away_code": "JK", "home_team": "Oxs", "home_code": "05" },
{ "game": 14, "away_team": "Dragons", "away_code": "FJ", "home_team": "Mets", "home_code": "MK" },
{ "game": 14, "away_team": "Rockers", "away_code": "AD", "home_team": "Trojans", "home_code": "DK" },
{ "game": 14, "away_team": "Grebes", "away_code": "FF", "home_team": "Oysters", "home_code": "JR" },
{ "game": 14, "away_team": "Giants", "away_code": "CU", "home_team": "Mariners", "home_code": "YZ" },
{ "game": 14, "away_team": "Teens", "away_code": "DA", "home_team": "Iguanas", "home_code": "OB" },
{ "game": 14, "away_team": "Dice", "away_code": "WS", "home_team": "Vaqueros", "home_code": "CC" },
{ "game": 14, "away_team": "Red Sox", "away_code": "NP", "home_team": "Hornets", "home_code": "WW" },
{ "game": 14, "away_team": "Skeeters", "away_code": "MC", "home_team": "Athletics", "home_code": "JL" }   
 ]
module.exports = { s1302teams, s1302schedule};
