// http://www.convertcsv.com/csv-to-json.htm

const s1303teams = {
    "Devil Rays": "<@&1142985787114266624>",
    "Wombats": "<@&1306540379423637565>",
    "Marlins": "<@&1306540511766642718>",
    "Melonheads": "<@&1224260726642835456>",
    "Yankees": "<@&668468071861583891>",
    "Royals": "<@&1067544069221392414>",
    "Expos": "<@&496713526778265624>",
    "Rockies": "<@&1306541385301889046>",
    "Giants": "<@&1071145998656737360>",
    "Diamondbacks": "<@&1306541040886485062>",
    "Twins": "<@&1071145277362274434>",
    "Blue Jays": "<@&603589804868763648>",
    "Astros": "<@&1067544975325265960>",
    "Monsters": "<@&1306540888687906827>",
    "Mariners": "<@&603768487676215316>",
    "Hornets": "<@&1306541154422099969>",
    "Angels": "<@&1067540852769050744>",
    "Rangers": "<@&603589502891458574>",
    "Tigers": "<@&1306540691538841630>",
    "Bombers": "<@&603291831744200737>",
    "Indians": "<@&448576195190063110>",
    "Cubs": "<@&1306541292020305940>",
    "Athletics": "<@&703992227160129667>",
    "Brewers": "<@&1306541618941267998>",
    
};

//"game": "1",
//"away_team": "As",
//"away_code": "NF",
//"home_team": "Red Sox",
//"home_code": "XD"

const s1303schedule =[
{ "game": 1, "away_team": "Tigers", "away_code": "VS", "home_team": "Blue Jays", "home_code": "MK" },
{ "game": 1, "away_team": "Royals", "away_code": "AX", "home_team": "Rangers", "home_code": "CS" },
{ "game": 1, "away_team": "Melonheads", "away_code": "MP", "home_team": "Diamondbacks", "home_code": "DG" },
{ "game": 1, "away_team": "Giants", "away_code": "2F", "home_team": "Wombats", "home_code": "DA" },
{ "game": 1, "away_team": "Twins", "away_code": "PZ", "home_team": "Angels", "home_code": "AP" },
{ "game": 1, "away_team": "Cubs", "away_code": "BO", "home_team": "Rockies", "home_code": "JL" },
{ "game": 1, "away_team": "Expos", "away_code": "LW", "home_team": "Yankees", "home_code": "WF" },
{ "game": 1, "away_team": "Indians", "away_code": "SK", "home_team": "Bombers", "home_code": "TC" },
{ "game": 1, "away_team": "Mariners", "away_code": "MM", "home_team": "Devil Rays", "home_code": "MC" },
{ "game": 1, "away_team": "Athletics", "away_code": "C8", "home_team": "Astros", "home_code": "PS" },
{ "game": 1, "away_team": "Hornets", "away_code": "IS", "home_team": "Brewers", "home_code": "CU" },
{ "game": 1, "away_team": "Marlins", "away_code": "GB", "home_team": "Monsters", "home_code": "M@" },
{ "game": 2, "away_team": "Angels", "away_code": "AP", "home_team": "Giants", "home_code": "2F" },
{ "game": 2, "away_team": "Diamondbacks", "away_code": "DG", "home_team": "Royals", "home_code": "AX" },
{ "game": 2, "away_team": "Rockies", "away_code": "JL", "home_team": "Twins", "home_code": "PZ" },
{ "game": 2, "away_team": "Blue Jays", "away_code": "MK", "home_team": "Melonheads", "home_code": "MP" },
{ "game": 2, "away_team": "Wombats", "away_code": "DA", "home_team": "Cubs", "home_code": "BO" },
{ "game": 2, "away_team": "Rangers", "away_code": "CS", "home_team": "Tigers", "home_code": "VS" },
{ "game": 2, "away_team": "Yankees", "away_code": "WF", "home_team": "Athletics", "home_code": "C8" },
{ "game": 2, "away_team": "Devil Rays", "away_code": "MC", "home_team": "Expos", "home_code": "LW" },
{ "game": 2, "away_team": "Astros", "away_code": "PS", "home_team": "Marlins", "home_code": "GB" },
{ "game": 2, "away_team": "Mariners", "away_code": "MM", "home_team": "Hornets", "home_code": "IS" },
{ "game": 2, "away_team": "Brewers", "away_code": "CU", "home_team": "Indians", "home_code": "SK" },
{ "game": 2, "away_team": "Bombers", "away_code": "TC", "home_team": "Monsters", "home_code": "M@" },
{ "game": 3, "away_team": "Cubs", "away_code": "BO", "home_team": "Twins", "home_code": "PZ" },
{ "game": 3, "away_team": "Blue Jays", "away_code": "MK", "home_team": "Diamondbacks", "home_code": "DG" },
{ "game": 3, "away_team": "Rangers", "away_code": "CS", "home_team": "Rockies", "home_code": "JL" },
{ "game": 3, "away_team": "Angels", "away_code": "AP", "home_team": "Wombats", "home_code": "DA" },
{ "game": 3, "away_team": "Royals", "away_code": "AX", "home_team": "Tigers", "home_code": "VS" },
{ "game": 3, "away_team": "Melonheads", "away_code": "MP", "home_team": "Giants", "home_code": "2F" },
{ "game": 3, "away_team": "Yankees", "away_code": "WF", "home_team": "Indians", "home_code": "SK" },
{ "game": 3, "away_team": "Expos", "away_code": "LW", "home_team": "Bombers", "home_code": "TC" },
{ "game": 3, "away_team": "Athletics", "away_code": "C8", "home_team": "Mariners", "home_code": "MM" },
{ "game": 3, "away_team": "Monsters", "away_code": "M@", "home_team": "Astros", "home_code": "PS" },
{ "game": 3, "away_team": "Hornets", "away_code": "IS", "home_team": "Devil Rays", "home_code": "MC" },
{ "game": 3, "away_team": "Marlins", "away_code": "GB", "home_team": "Brewers", "home_code": "CU" },
{ "game": 4, "away_team": "Melonheads", "away_code": "MP", "home_team": "Angels", "home_code": "AP" },
{ "game": 4, "away_team": "Cubs", "away_code": "BO", "home_team": "Rangers", "home_code": "CS" },
{ "game": 4, "away_team": "Royals", "away_code": "AX", "home_team": "Wombats", "home_code": "DA" },
{ "game": 4, "away_team": "Twins", "away_code": "PZ", "home_team": "Blue Jays", "home_code": "MK" },
{ "game": 4, "away_team": "Tigers", "away_code": "VS", "home_team": "Rockies", "home_code": "JL" },
{ "game": 4, "away_team": "Giants", "away_code": "2F", "home_team": "Diamondbacks", "home_code": "DG" },
{ "game": 4, "away_team": "Astros", "away_code": "PS", "home_team": "Yankees", "home_code": "WF" },
{ "game": 4, "away_team": "Indians", "away_code": "SK", "home_team": "Hornets", "home_code": "IS" },
{ "game": 4, "away_team": "Mariners", "away_code": "MM", "home_team": "Expos", "home_code": "LW" },
{ "game": 4, "away_team": "Bombers", "away_code": "TC", "home_team": "Marlins", "home_code": "GB" },
{ "game": 4, "away_team": "Devil Rays", "away_code": "MC", "home_team": "Athletics", "home_code": "C8" },
{ "game": 4, "away_team": "Brewers", "away_code": "CU", "home_team": "Monsters", "home_code": "M@" },
{ "game": 5, "away_team": "Diamondbacks", "away_code": "DG", "home_team": "Tigers", "home_code": "VS" },
{ "game": 5, "away_team": "Rockies", "away_code": "JL", "home_team": "Giants", "home_code": "2F" },
{ "game": 5, "away_team": "Blue Jays", "away_code": "MK", "home_team": "Royals", "home_code": "AX" },
{ "game": 5, "away_team": "Wombats", "away_code": "DA", "home_team": "Twins", "home_code": "PZ" },
{ "game": 5, "away_team": "Rangers", "away_code": "CS", "home_team": "Melonheads", "home_code": "MP" },
{ "game": 5, "away_team": "Angels", "away_code": "AP", "home_team": "Cubs", "home_code": "BO" },
{ "game": 5, "away_team": "Monsters", "away_code": "M@", "home_team": "Yankees", "home_code": "WF" },
{ "game": 5, "away_team": "Bombers", "away_code": "TC", "home_team": "Athletics", "home_code": "C8" },
{ "game": 5, "away_team": "Hornets", "away_code": "IS", "home_team": "Astros", "home_code": "PS" },
{ "game": 5, "away_team": "Marlins", "away_code": "GB", "home_team": "Mariners", "home_code": "MM" },
{ "game": 5, "away_team": "Indians", "away_code": "SK", "home_team": "Devil Rays", "home_code": "MC" },
{ "game": 5, "away_team": "Brewers", "away_code": "CU", "home_team": "Expos", "home_code": "LW" },
{ "game": 6, "away_team": "Tigers", "away_code": "VS", "home_team": "Cubs", "home_code": "BO" },
{ "game": 6, "away_team": "Giants", "away_code": "2F", "home_team": "Royals", "home_code": "AX" },
{ "game": 6, "away_team": "Twins", "away_code": "PZ", "home_team": "Melonheads", "home_code": "MP" },
{ "game": 6, "away_team": "Diamondbacks", "away_code": "DG", "home_team": "Angels", "home_code": "AP" },
{ "game": 6, "away_team": "Rockies", "away_code": "JL", "home_team": "Blue Jays", "home_code": "MK" },
{ "game": 6, "away_team": "Wombats", "away_code": "DA", "home_team": "Rangers", "home_code": "CS" },
{ "game": 6, "away_team": "Yankees", "away_code": "WF", "home_team": "Marlins", "home_code": "GB" },
{ "game": 6, "away_team": "Astros", "away_code": "PS", "home_team": "Bombers", "home_code": "TC" },
{ "game": 6, "away_team": "Mariners", "away_code": "MM", "home_team": "Indians", "home_code": "SK" },
{ "game": 6, "away_team": "Expos", "away_code": "LW", "home_team": "Hornets", "home_code": "IS" },
{ "game": 6, "away_team": "Athletics", "away_code": "C8", "home_team": "Monsters", "home_code": "M@" },
{ "game": 6, "away_team": "Devil Rays", "away_code": "MC", "home_team": "Brewers", "home_code": "CU" },
{ "game": 7, "away_team": "Rangers", "away_code": "CS", "home_team": "Angels", "home_code": "AP" },
{ "game": 7, "away_team": "Cubs", "away_code": "BO", "home_team": "Melonheads", "home_code": "MP" },
{ "game": 7, "away_team": "Blue Jays", "away_code": "MK", "home_team": "Wombats", "home_code": "DA" },
{ "game": 7, "away_team": "Royals", "away_code": "AX", "home_team": "Twins", "home_code": "PZ" },
{ "game": 7, "away_team": "Rockies", "away_code": "JL", "home_team": "Diamondbacks", "home_code": "DG" },
{ "game": 7, "away_team": "Tigers", "away_code": "VS", "home_team": "Giants", "home_code": "2F" },
{ "game": 7, "away_team": "Yankees", "away_code": "WF", "home_team": "Brewers", "home_code": "CU" },
{ "game": 7, "away_team": "Devil Rays", "away_code": "MC", "home_team": "Bombers", "home_code": "TC" },
{ "game": 7, "away_team": "Astros", "away_code": "PS", "home_team": "Mariners", "home_code": "MM" },
{ "game": 7, "away_team": "Marlins", "away_code": "GB", "home_team": "Hornets", "home_code": "IS" },
{ "game": 7, "away_team": "Athletics", "away_code": "C8", "home_team": "Expos", "home_code": "LW" },
{ "game": 7, "away_team": "Monsters", "away_code": "M@", "home_team": "Indians", "home_code": "SK" },
{ "game": 8, "away_team": "Giants", "away_code": "2F", "home_team": "Blue Jays", "home_code": "MK" },
{ "game": 8, "away_team": "Diamondbacks", "away_code": "DG", "home_team": "Cubs", "home_code": "BO" },
{ "game": 8, "away_team": "Melonheads", "away_code": "MP", "home_team": "Rockies", "home_code": "JL" },
{ "game": 8, "away_team": "Rangers", "away_code": "CS", "home_team": "Twins", "home_code": "PZ" },
{ "game": 8, "away_team": "Wombats", "away_code": "DA", "home_team": "Tigers", "home_code": "VS" },
{ "game": 8, "away_team": "Angels", "away_code": "AP", "home_team": "Royals", "home_code": "AX" },
{ "game": 8, "away_team": "Bombers", "away_code": "TC", "home_team": "Yankees", "home_code": "WF" },
{ "game": 8, "away_team": "Indians", "away_code": "SK", "home_team": "Expos", "home_code": "LW" },
{ "game": 8, "away_team": "Brewers", "away_code": "CU", "home_team": "Mariners", "home_code": "MM" },
{ "game": 8, "away_team": "Marlins", "away_code": "GB", "home_team": "Athletics", "home_code": "C8" },
{ "game": 8, "away_team": "Devil Rays", "away_code": "MC", "home_team": "Astros", "home_code": "PS" },
{ "game": 8, "away_team": "Hornets", "away_code": "IS", "home_team": "Monsters", "home_code": "M@" },
{ "game": 9, "away_team": "Tigers", "away_code": "VS", "home_team": "Melonheads", "home_code": "MP" },
{ "game": 9, "away_team": "Twins", "away_code": "PZ", "home_team": "Giants", "home_code": "2F" },
{ "game": 9, "away_team": "Cubs", "away_code": "BO", "home_team": "Royals", "home_code": "AX" },
{ "game": 9, "away_team": "Diamondbacks", "away_code": "DG", "home_team": "Rangers", "home_code": "CS" },
{ "game": 9, "away_team": "Rockies", "away_code": "JL", "home_team": "Wombats", "home_code": "DA" },
{ "game": 9, "away_team": "Blue Jays", "away_code": "MK", "home_team": "Angels", "home_code": "AP" },
{ "game": 9, "away_team": "Mariners", "away_code": "MM", "home_team": "Yankees", "home_code": "WF" },
{ "game": 9, "away_team": "Indians", "away_code": "SK", "home_team": "Marlins", "home_code": "GB" },
{ "game": 9, "away_team": "Hornets", "away_code": "IS", "home_team": "Bombers", "home_code": "TC" },
{ "game": 9, "away_team": "Expos", "away_code": "LW", "home_team": "Astros", "home_code": "PS" },
{ "game": 9, "away_team": "Brewers", "away_code": "CU", "home_team": "Athletics", "home_code": "C8" },
{ "game": 9, "away_team": "Monsters", "away_code": "M@", "home_team": "Devil Rays", "home_code": "MC" },
{ "game": 10, "away_team": "Twins", "away_code": "PZ", "home_team": "Diamondbacks", "home_code": "DG" },
{ "game": 10, "away_team": "Melonheads", "away_code": "MP", "home_team": "Wombats", "home_code": "DA" },
{ "game": 10, "away_team": "Cubs", "away_code": "BO", "home_team": "Blue Jays", "home_code": "MK" },
{ "game": 10, "away_team": "Angels", "away_code": "AP", "home_team": "Tigers", "home_code": "VS" },
{ "game": 10, "away_team": "Rangers", "away_code": "CS", "home_team": "Giants", "home_code": "2F" },
{ "game": 10, "away_team": "Royals", "away_code": "AX", "home_team": "Rockies", "home_code": "JL" },
{ "game": 10, "away_team": "Yankees", "away_code": "WF", "home_team": "Expos", "home_code": "LW" },
{ "game": 10, "away_team": "Bombers", "away_code": "TC", "home_team": "Indians", "home_code": "SK" },
{ "game": 10, "away_team": "Monsters", "away_code": "M@", "home_team": "Mariners", "home_code": "MM" },
{ "game": 10, "away_team": "Astros", "away_code": "PS", "home_team": "Brewers", "home_code": "CU" },
{ "game": 10, "away_team": "Athletics", "away_code": "C8", "home_team": "Hornets", "home_code": "IS" },
{ "game": 10, "away_team": "Marlins", "away_code": "GB", "home_team": "Devil Rays", "home_code": "MC" },
{ "game": 11, "away_team": "Wombats", "away_code": "DA", "home_team": "Royals", "home_code": "AX" },
{ "game": 11, "away_team": "Blue Jays", "away_code": "MK", "home_team": "Twins", "home_code": "PZ" },
{ "game": 11, "away_team": "Rockies", "away_code": "JL", "home_team": "Tigers", "home_code": "VS" },
{ "game": 11, "away_team": "Diamondbacks", "away_code": "DG", "home_team": "Giants", "home_code": "2F" },
{ "game": 11, "away_team": "Angels", "away_code": "AP", "home_team": "Melonheads", "home_code": "MP" },
{ "game": 11, "away_team": "Rangers", "away_code": "CS", "home_team": "Cubs", "home_code": "BO" },
{ "game": 11, "away_team": "Devil Rays", "away_code": "MC", "home_team": "Yankees", "home_code": "WF" },
{ "game": 11, "away_team": "Expos", "away_code": "LW", "home_team": "Monsters", "home_code": "M@" },
{ "game": 11, "away_team": "Marlins", "away_code": "GB", "home_team": "Astros", "home_code": "PS" },
{ "game": 11, "away_team": "Hornets", "away_code": "IS", "home_team": "Mariners", "home_code": "MM" },
{ "game": 11, "away_team": "Indians", "away_code": "SK", "home_team": "Athletics", "home_code": "C8" },
{ "game": 11, "away_team": "Brewers", "away_code": "CU", "home_team": "Bombers", "home_code": "TC" },
{ "game": 12, "away_team": "Tigers", "away_code": "VS", "home_team": "Diamondbacks", "home_code": "DG" },
{ "game": 12, "away_team": "Giants", "away_code": "2F", "home_team": "Rockies", "home_code": "JL" },
{ "game": 12, "away_team": "Royals", "away_code": "AX", "home_team": "Blue Jays", "home_code": "MK" },
{ "game": 12, "away_team": "Twins", "away_code": "PZ", "home_team": "Wombats", "home_code": "DA" },
{ "game": 12, "away_team": "Melonheads", "away_code": "MP", "home_team": "Rangers", "home_code": "CS" },
{ "game": 12, "away_team": "Cubs", "away_code": "BO", "home_team": "Angels", "home_code": "AP" },
{ "game": 12, "away_team": "Yankees", "away_code": "WF", "home_team": "Hornets", "home_code": "IS" },
{ "game": 12, "away_team": "Astros", "away_code": "PS", "home_team": "Indians", "home_code": "SK" },
{ "game": 12, "away_team": "Bombers", "away_code": "TC", "home_team": "Mariners", "home_code": "MM" },
{ "game": 12, "away_team": "Expos", "away_code": "LW", "home_team": "Marlins", "home_code": "GB" },
{ "game": 12, "away_team": "Athletics", "away_code": "C8", "home_team": "Devil Rays", "home_code": "MC" },
{ "game": 12, "away_team": "Monsters", "away_code": "M@", "home_team": "Brewers", "home_code": "CU" },
{ "game": 13, "away_team": "Tigers", "away_code": "VS", "home_team": "Twins", "home_code": "PZ" },
{ "game": 13, "away_team": "Giants", "away_code": "2F", "home_team": "Cubs", "home_code": "BO" },
{ "game": 13, "away_team": "Royals", "away_code": "AX", "home_team": "Melonheads", "home_code": "MP" },
{ "game": 13, "away_team": "Wombats", "away_code": "DA", "home_team": "Diamondbacks", "home_code": "DG" },
{ "game": 13, "away_team": "Blue Jays", "away_code": "MK", "home_team": "Rangers", "home_code": "CS" },
{ "game": 13, "away_team": "Rockies", "away_code": "JL", "home_team": "Angels", "home_code": "AP" },
{ "game": 13, "away_team": "Indians", "away_code": "SK", "home_team": "Yankees", "home_code": "WF" },
{ "game": 13, "away_team": "Bombers", "away_code": "TC", "home_team": "Expos", "home_code": "LW" },
{ "game": 13, "away_team": "Astros", "away_code": "PS", "home_team": "Hornets", "home_code": "IS" },
{ "game": 13, "away_team": "Mariners", "away_code": "MM", "home_team": "Marlins", "home_code": "GB" },
{ "game": 13, "away_team": "Monsters", "away_code": "M@", "home_team": "Athletics", "home_code": "C8" },
{ "game": 13, "away_team": "Brewers", "away_code": "CU", "home_team": "Devil Rays", "home_code": "MC" },
{ "game": 14, "away_team": "Giants", "away_code": "2F", "home_team": "Tigers", "home_code": "VS" },
{ "game": 14, "away_team": "Diamondbacks", "away_code": "DG", "home_team": "Rockies", "home_code": "JL" },
{ "game": 14, "away_team": "Melonheads", "away_code": "MP", "home_team": "Cubs", "home_code": "BO" },
{ "game": 14, "away_team": "Angels", "away_code": "AP", "home_team": "Rangers", "home_code": "CS" },
{ "game": 14, "away_team": "Twins", "away_code": "PZ", "home_team": "Royals", "home_code": "AX" },
{ "game": 14, "away_team": "Wombats", "away_code": "DA", "home_team": "Blue Jays", "home_code": "MK" },
{ "game": 14, "away_team": "Yankees", "away_code": "WF", "home_team": "Bombers", "home_code": "TC" },
{ "game": 14, "away_team": "Expos", "away_code": "LW", "home_team": "Indians", "home_code": "SK" },
{ "game": 14, "away_team": "Mariners", "away_code": "MM", "home_team": "Astros", "home_code": "PS" },
{ "game": 14, "away_team": "Hornets", "away_code": "IS", "home_team": "Marlins", "home_code": "GB" },
{ "game": 14, "away_team": "Athletics", "away_code": "C8", "home_team": "Brewers", "home_code": "CU" },
{ "game": 14, "away_team": "Devil Rays", "away_code": "MC", "home_team": "Monsters", "home_code": "M@" }   
 ]
module.exports = { s1303teams, s1303schedule};
