// http://www.convertcsv.com/csv-to-json.htm

const s1301teams = {
    "Rays": "<@&496788937705259009>",
    "Slices": "<@&670773176984403982>",
    "Marlins": "<@&496815324553936898>",
    "Melonheads": "<@&604520363673518119>",
    "Beers": "<@&496530637596000287>",
    "Cheesewheels": "<@&1067670617094094878>",
    "Bunnies": "<@&1306529245186625566>",
    "Squids": "<@&603286831823585280>",
    "Giants": "<@&1071145998656737360>",
    "Padres": "<@&1071145701725184070>",
    "Twins": "<@&1224263062996123678>",
    "Patriots": "<@&1224799651677605969>",
    "Ghosts": "<@&603589134744944670>",
    "Boss": "<@&783577309000368189>",
    "Blimps": "<@&448576748767150091>",
    "Knights": "<@&603768704295108628>",
    "Villains": "<@&702678271749390457>",
    "Grimaces": "<@&1224476744770261022>",
    "Fishes": "<@&603589333676589066>",
    "Reds": "<@&995878927753019412>",
    "Whitecaps": "<@&1224762411853287475>",
    "Cheese": "<@&900907535983329291>",
    "Jayhawks": "<@&1224790518819717312>",
    "Brats": "<@&603591280471048213>",
    
};

//"game": "1",
//"away_team": "As",
//"away_code": "NF",
//"home_team": "Red Sox",
//"home_code": "XD"

const s1301schedule =[
    { "game": 1, "away_team": "Slices", "away_code": "WZ", "home_team": "Bunnies", "home_code": "VS" },
{ "game": 1, "away_team": "Padres", "away_code": "BB", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 1, "away_team": "Giants", "away_code": "2F", "home_team": "Beers", "home_code": "HC" },
{ "game": 1, "away_team": "Cheesewheels", "away_code": "CH", "home_team": "Squids", "home_code": "YY" },
{ "game": 1, "away_team": "Patriots", "away_code": "BO", "home_team": "Boss", "home_code": "IT" },
{ "game": 1, "away_team": "Ghosts", "away_code": "M@", "home_team": "Marlins", "home_code": "LO" },
{ "game": 1, "away_team": "Knights", "away_code": "HZ", "home_team": "Villains", "home_code": "MF" },
{ "game": 1, "away_team": "Rays", "away_code": "AP", "home_team": "Blimps", "home_code": "C8" },
{ "game": 1, "away_team": "Whitecaps", "away_code": "JY", "home_team": "Jayhawks", "home_code": "AX" },
{ "game": 1, "away_team": "Brats", "away_code": "LW", "home_team": "Fishes", "home_code": "CW" },
{ "game": 1, "away_team": "Grimaces", "away_code": "N8", "home_team": "Cheese", "home_code": "PS" },
{ "game": 1, "away_team": "Reds", "away_code": "PZ", "home_team": "Twins", "home_code": "TO" },
{ "game": 2, "away_team": "Boss", "away_code": "IT", "home_team": "Cheesewheels", "home_code": "CH" },
{ "game": 2, "away_team": "Beers", "away_code": "HC", "home_team": "Padres", "home_code": "BB" },
{ "game": 2, "away_team": "Marlins", "away_code": "LO", "home_team": "Patriots", "home_code": "BO" },
{ "game": 2, "away_team": "Bunnies", "away_code": "VS", "home_team": "Giants", "home_code": "2F" },
{ "game": 2, "away_team": "Squids", "away_code": "YY", "home_team": "Ghosts", "home_code": "M@" },
{ "game": 2, "away_team": "Melonheads", "away_code": "TW", "home_team": "Slices", "home_code": "WZ" },
{ "game": 2, "away_team": "Villains", "away_code": "MF", "home_team": "Brats", "home_code": "LW" },
{ "game": 2, "away_team": "Jayhawks", "away_code": "AX", "home_team": "Knights", "home_code": "HZ" },
{ "game": 2, "away_team": "Fishes", "away_code": "CW", "home_team": "Reds", "home_code": "PZ" },
{ "game": 2, "away_team": "Whitecaps", "away_code": "JY", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 2, "away_team": "Cheese", "away_code": "PS", "home_team": "Rays", "home_code": "AP" },
{ "game": 2, "away_team": "Blimps", "away_code": "C8", "home_team": "Twins", "home_code": "TO" },
{ "game": 3, "away_team": "Ghosts", "away_code": "M@", "home_team": "Patriots", "home_code": "BO" },
{ "game": 3, "away_team": "Bunnies", "away_code": "VS", "home_team": "Beers", "home_code": "HC" },
{ "game": 3, "away_team": "Melonheads", "away_code": "TW", "home_team": "Marlins", "home_code": "LO" },
{ "game": 3, "away_team": "Boss", "away_code": "IT", "home_team": "Squids", "home_code": "YY" },
{ "game": 3, "away_team": "Padres", "away_code": "BB", "home_team": "Slices", "home_code": "WZ" },
{ "game": 3, "away_team": "Giants", "away_code": "2F", "home_team": "Cheesewheels", "home_code": "CH" },
{ "game": 3, "away_team": "Villains", "away_code": "MF", "home_team": "Rays", "home_code": "AP" },
{ "game": 3, "away_team": "Knights", "away_code": "HZ", "home_team": "Blimps", "home_code": "C8" },
{ "game": 3, "away_team": "Brats", "away_code": "LW", "home_team": "Whitecaps", "home_code": "JY" },
{ "game": 3, "away_team": "Twins", "away_code": "TO", "home_team": "Fishes", "home_code": "CW" },
{ "game": 3, "away_team": "Grimaces", "away_code": "N8", "home_team": "Jayhawks", "home_code": "AX" },
{ "game": 3, "away_team": "Reds", "away_code": "PZ", "home_team": "Cheese", "home_code": "PS" },
{ "game": 4, "away_team": "Giants", "away_code": "2F", "home_team": "Boss", "home_code": "IT" },
{ "game": 4, "away_team": "Ghosts", "away_code": "M@", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 4, "away_team": "Padres", "away_code": "BB", "home_team": "Squids", "home_code": "YY" },
{ "game": 4, "away_team": "Patriots", "away_code": "BO", "home_team": "Bunnies", "home_code": "VS" },
{ "game": 4, "away_team": "Slices", "away_code": "WZ", "home_team": "Marlins", "home_code": "LO" },
{ "game": 4, "away_team": "Cheesewheels", "away_code": "CH", "home_team": "Beers", "home_code": "HC" },
{ "game": 4, "away_team": "Fishes", "away_code": "CW", "home_team": "Villains", "home_code": "MF" },
{ "game": 4, "away_team": "Rays", "away_code": "AP", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 4, "away_team": "Whitecaps", "away_code": "JY", "home_team": "Knights", "home_code": "HZ" },
{ "game": 4, "away_team": "Blimps", "away_code": "C8", "home_team": "Reds", "home_code": "PZ" },
{ "game": 4, "away_team": "Jayhawks", "away_code": "AX", "home_team": "Brats", "home_code": "LW" },
{ "game": 4, "away_team": "Cheese", "away_code": "PS", "home_team": "Twins", "home_code": "TO" },
{ "game": 5, "away_team": "Beers", "away_code": "HC", "home_team": "Slices", "home_code": "WZ" },
{ "game": 5, "away_team": "Marlins", "away_code": "LO", "home_team": "Cheesewheels", "home_code": "CH" },
{ "game": 5, "away_team": "Bunnies", "away_code": "VS", "home_team": "Padres", "home_code": "BB" },
{ "game": 5, "away_team": "Squids", "away_code": "YY", "home_team": "Patriots", "home_code": "BO" },
{ "game": 5, "away_team": "Melonheads", "away_code": "TW", "home_team": "Giants", "home_code": "2F" },
{ "game": 5, "away_team": "Boss", "away_code": "IT", "home_team": "Ghosts", "home_code": "M@" },
{ "game": 5, "away_team": "Twins", "away_code": "TO", "home_team": "Villains", "home_code": "MF" },
{ "game": 5, "away_team": "Blimps", "away_code": "C8", "home_team": "Brats", "home_code": "LW" },
{ "game": 5, "away_team": "Grimaces", "away_code": "N8", "home_team": "Fishes", "home_code": "CW" },
{ "game": 5, "away_team": "Reds", "away_code": "PZ", "home_team": "Whitecaps", "home_code": "JY" },
{ "game": 5, "away_team": "Rays", "away_code": "AP", "home_team": "Jayhawks", "home_code": "AX" },
{ "game": 5, "away_team": "Cheese", "away_code": "PS", "home_team": "Knights", "home_code": "HZ" },
{ "game": 6, "away_team": "Slices", "away_code": "WZ", "home_team": "Ghosts", "home_code": "M@" },
{ "game": 6, "away_team": "Cheesewheels", "away_code": "CH", "home_team": "Padres", "home_code": "BB" },
{ "game": 6, "away_team": "Patriots", "away_code": "BO", "home_team": "Giants", "home_code": "2F" },
{ "game": 6, "away_team": "Beers", "away_code": "HC", "home_team": "Boss", "home_code": "IT" },
{ "game": 6, "away_team": "Marlins", "away_code": "LO", "home_team": "Bunnies", "home_code": "VS" },
{ "game": 6, "away_team": "Squids", "away_code": "YY", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 6, "away_team": "Villains", "away_code": "MF", "home_team": "Reds", "home_code": "PZ" },
{ "game": 6, "away_team": "Fishes", "away_code": "CW", "home_team": "Blimps", "home_code": "C8" },
{ "game": 6, "away_team": "Whitecaps", "away_code": "JY", "home_team": "Rays", "home_code": "AP" },
{ "game": 6, "away_team": "Knights", "away_code": "HZ", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 6, "away_team": "Brats", "away_code": "LW", "home_team": "Twins", "home_code": "TO" },
{ "game": 6, "away_team": "Jayhawks", "away_code": "AX", "home_team": "Cheese", "home_code": "PS" },
{ "game": 7, "away_team": "Melonheads", "away_code": "TW", "home_team": "Boss", "home_code": "IT" },
{ "game": 7, "away_team": "Ghosts", "away_code": "M@", "home_team": "Giants", "home_code": "2F" },
{ "game": 7, "away_team": "Bunnies", "away_code": "VS", "home_team": "Squids", "home_code": "YY" },
{ "game": 7, "away_team": "Padres", "away_code": "BB", "home_team": "Patriots", "home_code": "BO" },
{ "game": 7, "away_team": "Marlins", "away_code": "LO", "home_team": "Beers", "home_code": "HC" },
{ "game": 7, "away_team": "Slices", "away_code": "WZ", "home_team": "Cheesewheels", "home_code": "CH" },
{ "game": 7, "away_team": "Villains", "away_code": "MF", "home_team": "Cheese", "home_code": "PS" },
{ "game": 7, "away_team": "Jayhawks", "away_code": "AX", "home_team": "Blimps", "home_code": "C8" },
{ "game": 7, "away_team": "Fishes", "away_code": "CW", "home_team": "Whitecaps", "home_code": "JY" },
{ "game": 7, "away_team": "Reds", "away_code": "PZ", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 7, "away_team": "Brats", "away_code": "LW", "home_team": "Knights", "home_code": "HZ" },
{ "game": 7, "away_team": "Twins", "away_code": "TO", "home_team": "Rays", "home_code": "AP" },
{ "game": 8, "away_team": "Cheesewheels", "away_code": "CH", "home_team": "Bunnies", "home_code": "VS" },
{ "game": 8, "away_team": "Beers", "away_code": "HC", "home_team": "Ghosts", "home_code": "M@" },
{ "game": 8, "away_team": "Giants", "away_code": "2F", "home_team": "Marlins", "home_code": "LO" },
{ "game": 8, "away_team": "Melonheads", "away_code": "TW", "home_team": "Patriots", "home_code": "BO" },
{ "game": 8, "away_team": "Squids", "away_code": "YY", "home_team": "Slices", "home_code": "WZ" },
{ "game": 8, "away_team": "Boss", "away_code": "IT", "home_team": "Padres", "home_code": "BB" },
{ "game": 8, "away_team": "Blimps", "away_code": "C8", "home_team": "Villains", "home_code": "MF" },
{ "game": 8, "away_team": "Rays", "away_code": "AP", "home_team": "Knights", "home_code": "HZ" },
{ "game": 8, "away_team": "Cheese", "away_code": "PS", "home_team": "Whitecaps", "home_code": "JY" },
{ "game": 8, "away_team": "Reds", "away_code": "PZ", "home_team": "Brats", "home_code": "LW" },
{ "game": 8, "away_team": "Jayhawks", "away_code": "AX", "home_team": "Fishes", "home_code": "CW" },
{ "game": 8, "away_team": "Grimaces", "away_code": "N8", "home_team": "Twins", "home_code": "TO" },
{ "game": 9, "away_team": "Slices", "away_code": "WZ", "home_team": "Giants", "home_code": "2F" },
{ "game": 9, "away_team": "Patriots", "away_code": "BO", "home_team": "Cheesewheels", "home_code": "CH" },
{ "game": 9, "away_team": "Ghosts", "away_code": "M@", "home_team": "Padres", "home_code": "BB" },
{ "game": 9, "away_team": "Beers", "away_code": "HC", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 9, "away_team": "Marlins", "away_code": "LO", "home_team": "Squids", "home_code": "YY" },
{ "game": 9, "away_team": "Bunnies", "away_code": "VS", "home_team": "Boss", "home_code": "IT" },
{ "game": 9, "away_team": "Whitecaps", "away_code": "JY", "home_team": "Villains", "home_code": "MF" },
{ "game": 9, "away_team": "Rays", "away_code": "AP", "home_team": "Reds", "home_code": "PZ" },
{ "game": 9, "away_team": "Grimaces", "away_code": "N8", "home_team": "Blimps", "home_code": "C8" },
{ "game": 9, "away_team": "Knights", "away_code": "HZ", "home_team": "Fishes", "home_code": "CW" },
{ "game": 9, "away_team": "Cheese", "away_code": "PS", "home_team": "Brats", "home_code": "LW" },
{ "game": 9, "away_team": "Twins", "away_code": "TO", "home_team": "Jayhawks", "home_code": "AX" },
{ "game": 10, "away_team": "Patriots", "away_code": "BO", "home_team": "Beers", "home_code": "HC" },
{ "game": 10, "away_team": "Giants", "away_code": "2F", "home_team": "Squids", "home_code": "YY" },
{ "game": 10, "away_team": "Ghosts", "away_code": "M@", "home_team": "Bunnies", "home_code": "VS" },
{ "game": 10, "away_team": "Boss", "away_code": "IT", "home_team": "Slices", "home_code": "WZ" },
{ "game": 10, "away_team": "Melonheads", "away_code": "TW", "home_team": "Cheesewheels", "home_code": "CH" },
{ "game": 10, "away_team": "Padres", "away_code": "BB", "home_team": "Marlins", "home_code": "LO" },
{ "game": 10, "away_team": "Villains", "away_code": "MF", "home_team": "Knights", "home_code": "HZ" },
{ "game": 10, "away_team": "Blimps", "away_code": "C8", "home_team": "Rays", "home_code": "AP" },
{ "game": 10, "away_team": "Twins", "away_code": "TO", "home_team": "Whitecaps", "home_code": "JY" },
{ "game": 10, "away_team": "Fishes", "away_code": "CW", "home_team": "Cheese", "home_code": "PS" },
{ "game": 10, "away_team": "Brats", "away_code": "LW", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 10, "away_team": "Reds", "away_code": "PZ", "home_team": "Jayhawks", "home_code": "AX" },
{ "game": 11, "away_team": "Squids", "away_code": "YY", "home_team": "Padres", "home_code": "BB" },
{ "game": 11, "away_team": "Bunnies", "away_code": "VS", "home_team": "Patriots", "home_code": "BO" },
{ "game": 11, "away_team": "Marlins", "away_code": "LO", "home_team": "Slices", "home_code": "WZ" },
{ "game": 11, "away_team": "Beers", "away_code": "HC", "home_team": "Cheesewheels", "home_code": "CH" },
{ "game": 11, "away_team": "Boss", "away_code": "IT", "home_team": "Giants", "home_code": "2F" },
{ "game": 11, "away_team": "Melonheads", "away_code": "TW", "home_team": "Ghosts", "home_code": "M@" },
{ "game": 11, "away_team": "Jayhawks", "away_code": "AX", "home_team": "Villains", "home_code": "MF" },
{ "game": 11, "away_team": "Knights", "away_code": "HZ", "home_team": "Twins", "home_code": "TO" },
{ "game": 11, "away_team": "Reds", "away_code": "PZ", "home_team": "Fishes", "home_code": "CW" },
{ "game": 11, "away_team": "Grimaces", "away_code": "N8", "home_team": "Whitecaps", "home_code": "JY" },
{ "game": 11, "away_team": "Rays", "away_code": "AP", "home_team": "Brats", "home_code": "LW" },
{ "game": 11, "away_team": "Cheese", "away_code": "PS", "home_team": "Blimps", "home_code": "C8" },
{ "game": 12, "away_team": "Slices", "away_code": "WZ", "home_team": "Beers", "home_code": "HC" },
{ "game": 12, "away_team": "Cheesewheels", "away_code": "CH", "home_team": "Marlins", "home_code": "LO" },
{ "game": 12, "away_team": "Padres", "away_code": "BB", "home_team": "Bunnies", "home_code": "VS" },
{ "game": 12, "away_team": "Patriots", "away_code": "BO", "home_team": "Squids", "home_code": "YY" },
{ "game": 12, "away_team": "Giants", "away_code": "2F", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 12, "away_team": "Ghosts", "away_code": "M@", "home_team": "Boss", "home_code": "IT" },
{ "game": 12, "away_team": "Villains", "away_code": "MF", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 12, "away_team": "Fishes", "away_code": "CW", "home_team": "Rays", "home_code": "AP" },
{ "game": 12, "away_team": "Blimps", "away_code": "C8", "home_team": "Whitecaps", "home_code": "JY" },
{ "game": 12, "away_team": "Knights", "away_code": "HZ", "home_team": "Reds", "home_code": "PZ" },
{ "game": 12, "away_team": "Brats", "away_code": "LW", "home_team": "Jayhawks", "home_code": "AX" },
{ "game": 12, "away_team": "Twins", "away_code": "TO", "home_team": "Cheese", "home_code": "PS" },
{ "game": 13, "away_team": "Slices", "away_code": "WZ", "home_team": "Patriots", "home_code": "BO" },
{ "game": 13, "away_team": "Cheesewheels", "away_code": "CH", "home_team": "Ghosts", "home_code": "M@" },
{ "game": 13, "away_team": "Padres", "away_code": "BB", "home_team": "Giants", "home_code": "2F" },
{ "game": 13, "away_team": "Squids", "away_code": "YY", "home_team": "Beers", "home_code": "HC" },
{ "game": 13, "away_team": "Bunnies", "away_code": "VS", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 13, "away_team": "Marlins", "away_code": "LO", "home_team": "Boss", "home_code": "IT" },
{ "game": 13, "away_team": "Rays", "away_code": "AP", "home_team": "Villains", "home_code": "MF" },
{ "game": 13, "away_team": "Blimps", "away_code": "C8", "home_team": "Knights", "home_code": "HZ" },
{ "game": 13, "away_team": "Fishes", "away_code": "CW", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 13, "away_team": "Whitecaps", "away_code": "JY", "home_team": "Reds", "home_code": "PZ" },
{ "game": 13, "away_team": "Twins", "away_code": "TO", "home_team": "Brats", "home_code": "LW" },
{ "game": 13, "away_team": "Cheese", "away_code": "PS", "home_team": "Jayhawks", "home_code": "AX" },
{ "game": 14, "away_team": "Cheesewheels", "away_code": "CH", "home_team": "Slices", "home_code": "WZ" },
{ "game": 14, "away_team": "Beers", "away_code": "HC", "home_team": "Marlins", "home_code": "LO" },
{ "game": 14, "away_team": "Giants", "away_code": "2F", "home_team": "Ghosts", "home_code": "M@" },
{ "game": 14, "away_team": "Boss", "away_code": "IT", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 14, "away_team": "Patriots", "away_code": "BO", "home_team": "Padres", "home_code": "BB" },
{ "game": 14, "away_team": "Squids", "away_code": "YY", "home_team": "Bunnies", "home_code": "VS" },
{ "game": 14, "away_team": "Villains", "away_code": "MF", "home_team": "Blimps", "home_code": "C8" },
{ "game": 14, "away_team": "Knights", "away_code": "HZ", "home_team": "Rays", "home_code": "AP" },
{ "game": 14, "away_team": "Whitecaps", "away_code": "JY", "home_team": "Fishes", "home_code": "CW" },
{ "game": 14, "away_team": "Grimaces", "away_code": "N8", "home_team": "Reds", "home_code": "PZ" },
{ "game": 14, "away_team": "Brats", "away_code": "LW", "home_team": "Cheese", "home_code": "PS" },
{ "game": 14, "away_team": "Jayhawks", "away_code": "AX", "home_team": "Twins", "home_code": "TO" }
   
 ]
module.exports = { s1301teams, s1301schedule};
