// http://www.convertcsv.com/csv-to-json.htm

const s1403teams = {
    "Tigers": "<@1306540691538841630>",
    "Phillies": "<@1067544069221392414>",
    "Blue Jays": "<@493888943754838036>",
    "Bombers": "<@603291831744200737>",
    "Red Sox": "<@1071145701725184070>",
    "Giants": "<@1067672079060713512>",
    "Hornets": "<@448576195190063110>",
    "Reds": "<@603589804868763648>",
    "Wombats": "<@1306540379423637565>",
    "Melonheads": "<@783577309000368189>",
    "Pirates": "<@1306540511766642718>",
    "Indians": "<@1397106280610664511>",
    "Orioles": "<@603589502891458574>",
    "Fishes": "<@603589333676589066>",
    "Twins": "<@1067544975325265960>",
    "Rockies": "<@1306541385301889046>",
    "Diamondbacks": "<@1224762411853287475>",
    "Athletics": "<@847666595748249640>",
    "Monsters": "<@603286831823585280>",
    "Devil Rays": "<@1067528806765699162>",
    "Braves": "<@1224260726642835456>",
    "Cardinals": "<@1067540852769050744>",
    "Angels": "<@1142985787114266624>",
    "Brewers": "<@1306541292020305940>",
    
};

//"game": "1",
//"away_team": "As",
//"away_code": "NF",
//"home_team": "Red Sox",
//"home_code": "XD"

const s1403schedule =[
{ "game": 1, "away_team": "Angels", "away_code": "EF", "home_team": "Braves", "home_code": "MP" },
{ "game": 1, "away_team": "Cardinals", "away_code": "LW", "home_team": "Brewers", "home_code": "N8" },
{ "game": 1, "away_team": "Fishes", "away_code": "CW", "home_team": "Athletics", "home_code": "WS" },
{ "game": 1, "away_team": "Indians", "away_code": "JJ", "home_team": "Rockies", "home_code": "HZ" },
{ "game": 1, "away_team": "Orioles", "away_code": "NV", "home_team": "Diamondbacks", "home_code": "SB" },
{ "game": 1, "away_team": "Twins", "away_code": "TO", "home_team": "Devil Rays", "home_code": "MS" },
{ "game": 1, "away_team": "Monsters", "away_code": "LS", "home_team": "Hornets", "home_code": "SK" },
{ "game": 1, "away_team": "Wombats", "away_code": "YT", "home_team": "Pirates", "home_code": "GB" },
{ "game": 1, "away_team": "Blue Jays", "away_code": "DA", "home_team": "Bombers", "home_code": "CK" },
{ "game": 1, "away_team": "Phillies", "away_code": "SW", "home_team": "Giants", "home_code": "JO" },
{ "game": 1, "away_team": "Reds", "away_code": "FJ", "home_team": "Melonheads", "home_code": "JY" },
{ "game": 1, "away_team": "Tigers", "away_code": "VS", "home_team": "Red Sox", "home_code": "BO" },
{ "game": 2, "away_team": "Fishes", "away_code": "CW", "home_team": "Indians", "home_code": "JJ" },
{ "game": 2, "away_team": "Orioles", "away_code": "NV", "home_team": "Twins", "home_code": "TO" },
{ "game": 2, "away_team": "Athletics", "away_code": "WS", "home_team": "Braves", "home_code": "MP" },
{ "game": 2, "away_team": "Rockies", "away_code": "HZ", "home_team": "Angels", "home_code": "EF" },
{ "game": 2, "away_team": "Diamondbacks", "away_code": "SB", "home_team": "Brewers", "home_code": "N8" },
{ "game": 2, "away_team": "Devil Rays", "away_code": "MS", "home_team": "Cardinals", "home_code": "LW" },
{ "game": 2, "away_team": "Blue Jays", "away_code": "DA", "home_team": "Phillies", "home_code": "SW" },
{ "game": 2, "away_team": "Reds", "away_code": "FJ", "home_team": "Tigers", "home_code": "VS" },
{ "game": 2, "away_team": "Bombers", "away_code": "CK", "home_team": "Hornets", "home_code": "SK" },
{ "game": 2, "away_team": "Giants", "away_code": "JO", "home_team": "Monsters", "home_code": "LS" },
{ "game": 2, "away_team": "Melonheads", "away_code": "JY", "home_team": "Pirates", "home_code": "GB" },
{ "game": 2, "away_team": "Red Sox", "away_code": "BO", "home_team": "Wombats", "home_code": "YT" },
{ "game": 3, "away_team": "Athletics", "away_code": "WS", "home_team": "Rockies", "home_code": "HZ" },
{ "game": 3, "away_team": "Diamondbacks", "away_code": "SB", "home_team": "Devil Rays", "home_code": "MS" },
{ "game": 3, "away_team": "Braves", "away_code": "MP", "home_team": "Fishes", "home_code": "CW" },
{ "game": 3, "away_team": "Angels", "away_code": "EF", "home_team": "Indians", "home_code": "JJ" },
{ "game": 3, "away_team": "Brewers", "away_code": "N8", "home_team": "Orioles", "home_code": "NV" },
{ "game": 3, "away_team": "Cardinals", "away_code": "LW", "home_team": "Twins", "home_code": "TO" },
{ "game": 3, "away_team": "Bombers", "away_code": "CK", "home_team": "Giants", "home_code": "JO" },
{ "game": 3, "away_team": "Melonheads", "away_code": "JY", "home_team": "Red Sox", "home_code": "BO" },
{ "game": 3, "away_team": "Hornets", "away_code": "SK", "home_team": "Blue Jays", "home_code": "DA" },
{ "game": 3, "away_team": "Monsters", "away_code": "LS", "home_team": "Phillies", "home_code": "SW" },
{ "game": 3, "away_team": "Pirates", "away_code": "GB", "home_team": "Reds", "home_code": "FJ" },
{ "game": 3, "away_team": "Wombats", "away_code": "YT", "home_team": "Tigers", "home_code": "VS" },
{ "game": 4, "away_team": "Angels", "away_code": "EF", "home_team": "Cardinals", "home_code": "LW" },
{ "game": 4, "away_team": "Brewers", "away_code": "N8", "home_team": "Braves", "home_code": "MP" },
{ "game": 4, "away_team": "Fishes", "away_code": "CW", "home_team": "Rockies", "home_code": "HZ" },
{ "game": 4, "away_team": "Indians", "away_code": "JJ", "home_team": "Diamondbacks", "home_code": "SB" },
{ "game": 4, "away_team": "Orioles", "away_code": "NV", "home_team": "Devil Rays", "home_code": "MS" },
{ "game": 4, "away_team": "Twins", "away_code": "TO", "home_team": "Athletics", "home_code": "WS" },
{ "game": 4, "away_team": "Monsters", "away_code": "LS", "home_team": "Wombats", "home_code": "YT" },
{ "game": 4, "away_team": "Pirates", "away_code": "GB", "home_team": "Hornets", "home_code": "SK" },
{ "game": 4, "away_team": "Blue Jays", "away_code": "DA", "home_team": "Giants", "home_code": "JO" },
{ "game": 4, "away_team": "Phillies", "away_code": "SW", "home_team": "Melonheads", "home_code": "JY" },
{ "game": 4, "away_team": "Reds", "away_code": "FJ", "home_team": "Red Sox", "home_code": "BO" },
{ "game": 4, "away_team": "Tigers", "away_code": "VS", "home_team": "Bombers", "home_code": "CK" },
{ "game": 5, "away_team": "Rockies", "away_code": "HZ", "home_team": "Devil Rays", "home_code": "MS" },
{ "game": 5, "away_team": "Athletics", "away_code": "WS", "home_team": "Diamondbacks", "home_code": "SB" },
{ "game": 5, "away_team": "Braves", "away_code": "MP", "home_team": "Indians", "home_code": "JJ" },
{ "game": 5, "away_team": "Angels", "away_code": "EF", "home_team": "Orioles", "home_code": "NV" },
{ "game": 5, "away_team": "Brewers", "away_code": "N8", "home_team": "Twins", "home_code": "TO" },
{ "game": 5, "away_team": "Cardinals", "away_code": "LW", "home_team": "Fishes", "home_code": "CW" },
{ "game": 5, "away_team": "Giants", "away_code": "JO", "home_team": "Red Sox", "home_code": "BO" },
{ "game": 5, "away_team": "Bombers", "away_code": "CK", "home_team": "Melonheads", "home_code": "JY" },
{ "game": 5, "away_team": "Hornets", "away_code": "SK", "home_team": "Phillies", "home_code": "SW" },
{ "game": 5, "away_team": "Monsters", "away_code": "LS", "home_team": "Reds", "home_code": "FJ" },
{ "game": 5, "away_team": "Pirates", "away_code": "GB", "home_team": "Tigers", "home_code": "VS" },
{ "game": 5, "away_team": "Wombats", "away_code": "YT", "home_team": "Blue Jays", "home_code": "DA" },
{ "game": 6, "away_team": "Indians", "away_code": "JJ", "home_team": "Twins", "home_code": "TO" },
{ "game": 6, "away_team": "Fishes", "away_code": "CW", "home_team": "Orioles", "home_code": "NV" },
{ "game": 6, "away_team": "Rockies", "away_code": "HZ", "home_team": "Braves", "home_code": "MP" },
{ "game": 6, "away_team": "Diamondbacks", "away_code": "SB", "home_team": "Angels", "home_code": "EF" },
{ "game": 6, "away_team": "Devil Rays", "away_code": "MS", "home_team": "Brewers", "home_code": "N8" },
{ "game": 6, "away_team": "Athletics", "away_code": "WS", "home_team": "Cardinals", "home_code": "LW" },
{ "game": 6, "away_team": "Phillies", "away_code": "SW", "home_team": "Tigers", "home_code": "VS" },
{ "game": 6, "away_team": "Blue Jays", "away_code": "DA", "home_team": "Reds", "home_code": "FJ" },
{ "game": 6, "away_team": "Giants", "away_code": "JO", "home_team": "Hornets", "home_code": "SK" },
{ "game": 6, "away_team": "Melonheads", "away_code": "JY", "home_team": "Monsters", "home_code": "LS" },
{ "game": 6, "away_team": "Red Sox", "away_code": "BO", "home_team": "Pirates", "home_code": "GB" },
{ "game": 6, "away_team": "Bombers", "away_code": "CK", "home_team": "Wombats", "home_code": "YT" },
{ "game": 7, "away_team": "Cardinals", "away_code": "LW", "home_team": "Braves", "home_code": "MP" },
{ "game": 7, "away_team": "Angels", "away_code": "EF", "home_team": "Brewers", "home_code": "N8" },
{ "game": 7, "away_team": "Twins", "away_code": "TO", "home_team": "Fishes", "home_code": "CW" },
{ "game": 7, "away_team": "Orioles", "away_code": "NV", "home_team": "Indians", "home_code": "JJ" },
{ "game": 7, "away_team": "Devil Rays", "away_code": "MS", "home_team": "Athletics", "home_code": "WS" },
{ "game": 7, "away_team": "Diamondbacks", "away_code": "SB", "home_team": "Rockies", "home_code": "HZ" },
{ "game": 7, "away_team": "Wombats", "away_code": "YT", "home_team": "Hornets", "home_code": "SK" },
{ "game": 7, "away_team": "Monsters", "away_code": "LS", "home_team": "Pirates", "home_code": "GB" },
{ "game": 7, "away_team": "Tigers", "away_code": "VS", "home_team": "Blue Jays", "home_code": "DA" },
{ "game": 7, "away_team": "Reds", "away_code": "FJ", "home_team": "Phillies", "home_code": "SW" },
{ "game": 7, "away_team": "Red Sox", "away_code": "BO", "home_team": "Bombers", "home_code": "CK" },
{ "game": 7, "away_team": "Melonheads", "away_code": "JY", "home_team": "Giants", "home_code": "JO" },
{ "game": 8, "away_team": "Braves", "away_code": "MP", "home_team": "Angels", "home_code": "EF" },
{ "game": 8, "away_team": "Brewers", "away_code": "N8", "home_team": "Cardinals", "home_code": "LW" },
{ "game": 8, "away_team": "Diamondbacks", "away_code": "SB", "home_team": "Fishes", "home_code": "CW" },
{ "game": 8, "away_team": "Devil Rays", "away_code": "MS", "home_team": "Indians", "home_code": "JJ" },
{ "game": 8, "away_team": "Athletics", "away_code": "WS", "home_team": "Orioles", "home_code": "NV" },
{ "game": 8, "away_team": "Rockies", "away_code": "HZ", "home_team": "Twins", "home_code": "TO" },
{ "game": 8, "away_team": "Hornets", "away_code": "SK", "home_team": "Monsters", "home_code": "LS" },
{ "game": 8, "away_team": "Pirates", "away_code": "GB", "home_team": "Wombats", "home_code": "YT" },
{ "game": 8, "away_team": "Melonheads", "away_code": "JY", "home_team": "Blue Jays", "home_code": "DA" },
{ "game": 8, "away_team": "Red Sox", "away_code": "BO", "home_team": "Phillies", "home_code": "SW" },
{ "game": 8, "away_team": "Bombers", "away_code": "CK", "home_team": "Reds", "home_code": "FJ" },
{ "game": 8, "away_team": "Giants", "away_code": "JO", "home_team": "Tigers", "home_code": "VS" },
{ "game": 9, "away_team": "Indians", "away_code": "JJ", "home_team": "Fishes", "home_code": "CW" },
{ "game": 9, "away_team": "Twins", "away_code": "TO", "home_team": "Orioles", "home_code": "NV" },
{ "game": 9, "away_team": "Braves", "away_code": "MP", "home_team": "Diamondbacks", "home_code": "SB" },
{ "game": 9, "away_team": "Angels", "away_code": "EF", "home_team": "Devil Rays", "home_code": "MS" },
{ "game": 9, "away_team": "Brewers", "away_code": "N8", "home_team": "Athletics", "home_code": "WS" },
{ "game": 9, "away_team": "Cardinals", "away_code": "LW", "home_team": "Rockies", "home_code": "HZ" },
{ "game": 9, "away_team": "Phillies", "away_code": "SW", "home_team": "Blue Jays", "home_code": "DA" },
{ "game": 9, "away_team": "Tigers", "away_code": "VS", "home_team": "Reds", "home_code": "FJ" },
{ "game": 9, "away_team": "Hornets", "away_code": "SK", "home_team": "Melonheads", "home_code": "JY" },
{ "game": 9, "away_team": "Monsters", "away_code": "LS", "home_team": "Red Sox", "home_code": "BO" },
{ "game": 9, "away_team": "Pirates", "away_code": "GB", "home_team": "Bombers", "home_code": "CK" },
{ "game": 9, "away_team": "Wombats", "away_code": "YT", "home_team": "Giants", "home_code": "JO" },
{ "game": 10, "away_team": "Rockies", "away_code": "HZ", "home_team": "Athletics", "home_code": "WS" },
{ "game": 10, "away_team": "Devil Rays", "away_code": "MS", "home_team": "Diamondbacks", "home_code": "SB" },
{ "game": 10, "away_team": "Orioles", "away_code": "NV", "home_team": "Braves", "home_code": "MP" },
{ "game": 10, "away_team": "Twins", "away_code": "TO", "home_team": "Angels", "home_code": "EF" },
{ "game": 10, "away_team": "Fishes", "away_code": "CW", "home_team": "Brewers", "home_code": "N8" },
{ "game": 10, "away_team": "Indians", "away_code": "JJ", "home_team": "Cardinals", "home_code": "LW" },
{ "game": 10, "away_team": "Giants", "away_code": "JO", "home_team": "Bombers", "home_code": "CK" },
{ "game": 10, "away_team": "Red Sox", "away_code": "BO", "home_team": "Melonheads", "home_code": "JY" },
{ "game": 10, "away_team": "Reds", "away_code": "FJ", "home_team": "Hornets", "home_code": "SK" },
{ "game": 10, "away_team": "Tigers", "away_code": "VS", "home_team": "Monsters", "home_code": "LS" },
{ "game": 10, "away_team": "Blue Jays", "away_code": "DA", "home_team": "Pirates", "home_code": "GB" },
{ "game": 10, "away_team": "Phillies", "away_code": "SW", "home_team": "Wombats", "home_code": "YT" },
{ "game": 11, "away_team": "Devil Rays", "away_code": "MS", "home_team": "Rockies", "home_code": "HZ" },
{ "game": 11, "away_team": "Diamondbacks", "away_code": "SB", "home_team": "Athletics", "home_code": "WS" },
{ "game": 11, "away_team": "Braves", "away_code": "MP", "home_team": "Twins", "home_code": "TO" },
{ "game": 11, "away_team": "Angels", "away_code": "EF", "home_team": "Fishes", "home_code": "CW" },
{ "game": 11, "away_team": "Brewers", "away_code": "N8", "home_team": "Indians", "home_code": "JJ" },
{ "game": 11, "away_team": "Cardinals", "away_code": "LW", "home_team": "Orioles", "home_code": "NV" },
{ "game": 11, "away_team": "Red Sox", "away_code": "BO", "home_team": "Giants", "home_code": "JO" },
{ "game": 11, "away_team": "Melonheads", "away_code": "JY", "home_team": "Bombers", "home_code": "CK" },
{ "game": 11, "away_team": "Hornets", "away_code": "SK", "home_team": "Tigers", "home_code": "VS" },
{ "game": 11, "away_team": "Monsters", "away_code": "LS", "home_team": "Blue Jays", "home_code": "DA" },
{ "game": 11, "away_team": "Pirates", "away_code": "GB", "home_team": "Phillies", "home_code": "SW" },
{ "game": 11, "away_team": "Wombats", "away_code": "YT", "home_team": "Reds", "home_code": "FJ" },
{ "game": 12, "away_team": "Twins", "away_code": "TO", "home_team": "Indians", "home_code": "JJ" },
{ "game": 12, "away_team": "Orioles", "away_code": "NV", "home_team": "Fishes", "home_code": "CW" },
{ "game": 12, "away_team": "Devil Rays", "away_code": "MS", "home_team": "Braves", "home_code": "MP" },
{ "game": 12, "away_team": "Athletics", "away_code": "WS", "home_team": "Angels", "home_code": "EF" },
{ "game": 12, "away_team": "Rockies", "away_code": "HZ", "home_team": "Brewers", "home_code": "N8" },
{ "game": 12, "away_team": "Diamondbacks", "away_code": "SB", "home_team": "Cardinals", "home_code": "LW" },
{ "game": 12, "away_team": "Tigers", "away_code": "VS", "home_team": "Phillies", "home_code": "SW" },
{ "game": 12, "away_team": "Reds", "away_code": "FJ", "home_team": "Blue Jays", "home_code": "DA" },
{ "game": 12, "away_team": "Red Sox", "away_code": "BO", "home_team": "Hornets", "home_code": "SK" },
{ "game": 12, "away_team": "Bombers", "away_code": "CK", "home_team": "Monsters", "home_code": "LS" },
{ "game": 12, "away_team": "Giants", "away_code": "JO", "home_team": "Pirates", "home_code": "GB" },
{ "game": 12, "away_team": "Melonheads", "away_code": "JY", "home_team": "Wombats", "home_code": "YT" },
{ "game": 13, "away_team": "Cardinals", "away_code": "LW", "home_team": "Angels", "home_code": "EF" },
{ "game": 13, "away_team": "Braves", "away_code": "MP", "home_team": "Brewers", "home_code": "N8" },
{ "game": 13, "away_team": "Fishes", "away_code": "CW", "home_team": "Devil Rays", "home_code": "MS" },
{ "game": 13, "away_team": "Indians", "away_code": "JJ", "home_team": "Athletics", "home_code": "WS" },
{ "game": 13, "away_team": "Orioles", "away_code": "NV", "home_team": "Rockies", "home_code": "HZ" },
{ "game": 13, "away_team": "Twins", "away_code": "TO", "home_team": "Diamondbacks", "home_code": "SB" },
{ "game": 13, "away_team": "Wombats", "away_code": "YT", "home_team": "Monsters", "home_code": "LS" },
{ "game": 13, "away_team": "Hornets", "away_code": "SK", "home_team": "Pirates", "home_code": "GB" },
{ "game": 13, "away_team": "Blue Jays", "away_code": "DA", "home_team": "Red Sox", "home_code": "BO" },
{ "game": 13, "away_team": "Phillies", "away_code": "SW", "home_team": "Bombers", "home_code": "CK" },
{ "game": 13, "away_team": "Reds", "away_code": "FJ", "home_team": "Giants", "home_code": "JO" },
{ "game": 13, "away_team": "Tigers", "away_code": "VS", "home_team": "Melonheads", "home_code": "JY" },
{ "game": 14, "away_team": "Braves", "away_code": "MP", "home_team": "Cardinals", "home_code": "LW" },
{ "game": 14, "away_team": "Brewers", "away_code": "N8", "home_team": "Angels", "home_code": "EF" },
{ "game": 14, "away_team": "Fishes", "away_code": "CW", "home_team": "Twins", "home_code": "TO" },
{ "game": 14, "away_team": "Indians", "away_code": "JJ", "home_team": "Orioles", "home_code": "NV" },
{ "game": 14, "away_team": "Athletics", "away_code": "WS", "home_team": "Devil Rays", "home_code": "MS" },
{ "game": 14, "away_team": "Rockies", "away_code": "HZ", "home_team": "Diamondbacks", "home_code": "SB" },
{ "game": 14, "away_team": "Hornets", "away_code": "SK", "home_team": "Wombats", "home_code": "YT" },
{ "game": 14, "away_team": "Pirates", "away_code": "GB", "home_team": "Monsters", "home_code": "LS" },
{ "game": 14, "away_team": "Blue Jays", "away_code": "DA", "home_team": "Tigers", "home_code": "VS" },
{ "game": 14, "away_team": "Phillies", "away_code": "SW", "home_team": "Reds", "home_code": "FJ" },
{ "game": 14, "away_team": "Bombers", "away_code": "CK", "home_team": "Red Sox", "home_code": "BO" },
{ "game": 14, "away_team": "Giants", "away_code": "JO", "home_team": "Melonheads", "home_code": "JY" }
   
 ]
module.exports = { s1403teams, s1403schedule};
