// http://www.convertcsv.com/csv-to-json.htm

const s1401teams = {
    "Skeeters": "<@847665786708688936>",
    "Patriots": "<@1224799651677605969>",
    "Marlins": "<@496815324553936898>",
    "Casa Houses": "<@603589134744944670>",
    "Machines": "<@603768704295108628>",
    "Baseball Team": "<@1067545232243183737>",
    "Oysters": "<@1224471696820670616>",
    "Reds": "<@995878927753019412>",
    "Wombats": "<@496788937705259009>",
    "Melonheads": "<@604520363673518119>",
    "Penguins": "<@703669468768895206>",
    "Raccoons": "<@1306529245186625566>",
    "Beers": "<@496530637596000287>",
    "Grebes": "<@1224784681166438540>",
    "Pacers": "<@1224790518819717312>",
    "Trippers": "<@448576748767150091>",
    "Salamis": "<@1306541040886485062>",
    "Brats": "<@603591280471048213>",
    "Monsters": "<@496817066201055232>",
    "Warmups": "<@1067670617094094878>",
    "Ostriches": "<@496817420753960961>",
    "Greasels": "<@1224476744770261022>",
    "Rippin": "<@1306541618941267998>",
    "Dice": "<@1306532649573285888>",
    
};

//"game": "1",
//"away_team": "As",
//"away_code": "NF",
//"home_team": "Red Sox",
//"home_code": "XD"

const s1401schedule =[

{ "game": 1, "away_team": "Penguins", "away_code": "GB", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 1, "away_team": "Wombats", "away_code": "AP", "home_team": "Raccoons", "home_code": "VS" },
{ "game": 1, "away_team": "Casa Houses", "away_code": "M@", "home_team": "Baseball Team", "home_code": "MM" },
{ "game": 1, "away_team": "Marlins", "away_code": "LO", "home_team": "Machines", "home_code": "HZ" },
{ "game": 1, "away_team": "Patriots", "away_code": "BO", "home_team": "Oysters", "home_code": "JR" },
{ "game": 1, "away_team": "Skeeters", "away_code": "MC", "home_team": "Reds", "home_code": "PZ" },
{ "game": 1, "away_team": "Greasels", "away_code": "BF", "home_team": "Dice", "home_code": "WS" },
{ "game": 1, "away_team": "Rippin", "away_code": "IT", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 1, "away_team": "Beers", "away_code": "HC", "home_team": "Brats", "home_code": "LW" },
{ "game": 1, "away_team": "Grebes", "away_code": "FF", "home_team": "Monsters", "home_code": "YY" },
{ "game": 1, "away_team": "Pacers", "away_code": "AX", "home_team": "Salamis", "home_code": "GS" },
{ "game": 1, "away_team": "Trippers", "away_code": "C8", "home_team": "Warmups", "home_code": "CH" },
{ "game": 2, "away_team": "Casa Houses", "away_code": "M@", "home_team": "Marlins", "home_code": "LO" },
{ "game": 2, "away_team": "Patriots", "away_code": "BO", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 2, "away_team": "Baseball Team", "away_code": "MM", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 2, "away_team": "Machines", "away_code": "HZ", "home_team": "Penguins", "home_code": "GB" },
{ "game": 2, "away_team": "Oysters", "away_code": "JR", "home_team": "Raccoons", "home_code": "VS" },
{ "game": 2, "away_team": "Reds", "away_code": "PZ", "home_team": "Wombats", "home_code": "AP" },
{ "game": 2, "away_team": "Beers", "away_code": "HC", "home_team": "Grebes", "home_code": "FF" },
{ "game": 2, "away_team": "Pacers", "away_code": "AX", "home_team": "Trippers", "home_code": "C8" },
{ "game": 2, "away_team": "Brats", "away_code": "LW", "home_team": "Dice", "home_code": "WS" },
{ "game": 2, "away_team": "Monsters", "away_code": "YY", "home_team": "Greasels", "home_code": "BF" },
{ "game": 2, "away_team": "Salamis", "away_code": "GS", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 2, "away_team": "Warmups", "away_code": "CH", "home_team": "Rippin", "home_code": "IT" },
{ "game": 3, "away_team": "Baseball Team", "away_code": "MM", "home_team": "Machines", "home_code": "HZ" },
{ "game": 3, "away_team": "Oysters", "away_code": "JR", "home_team": "Reds", "home_code": "PZ" },
{ "game": 3, "away_team": "Melonheads", "away_code": "TW", "home_team": "Casa Houses", "home_code": "M@" },
{ "game": 3, "away_team": "Penguins", "away_code": "GB", "home_team": "Marlins", "home_code": "LO" },
{ "game": 3, "away_team": "Raccoons", "away_code": "VS", "home_team": "Patriots", "home_code": "BO" },
{ "game": 3, "away_team": "Wombats", "away_code": "AP", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 3, "away_team": "Brats", "away_code": "LW", "home_team": "Monsters", "home_code": "YY" },
{ "game": 3, "away_team": "Salamis", "away_code": "GS", "home_team": "Warmups", "home_code": "CH" },
{ "game": 3, "away_team": "Dice", "away_code": "WS", "home_team": "Beers", "home_code": "HC" },
{ "game": 3, "away_team": "Greasels", "away_code": "BF", "home_team": "Grebes", "home_code": "FF" },
{ "game": 3, "away_team": "Ostriches", "away_code": "NV", "home_team": "Pacers", "home_code": "AX" },
{ "game": 3, "away_team": "Rippin", "away_code": "IT", "home_team": "Trippers", "home_code": "C8" },
{ "game": 4, "away_team": "Penguins", "away_code": "GB", "home_team": "Wombats", "home_code": "AP" },
{ "game": 4, "away_team": "Raccoons", "away_code": "VS", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 4, "away_team": "Casa Houses", "away_code": "M@", "home_team": "Machines", "home_code": "HZ" },
{ "game": 4, "away_team": "Marlins", "away_code": "LO", "home_team": "Oysters", "home_code": "JR" },
{ "game": 4, "away_team": "Patriots", "away_code": "BO", "home_team": "Reds", "home_code": "PZ" },
{ "game": 4, "away_team": "Skeeters", "away_code": "MC", "home_team": "Baseball Team", "home_code": "MM" },
{ "game": 4, "away_team": "Greasels", "away_code": "BF", "home_team": "Rippin", "home_code": "IT" },
{ "game": 4, "away_team": "Ostriches", "away_code": "NV", "home_team": "Dice", "home_code": "WS" },
{ "game": 4, "away_team": "Beers", "away_code": "HC", "home_team": "Monsters", "home_code": "YY" },
{ "game": 4, "away_team": "Grebes", "away_code": "FF", "home_team": "Salamis", "home_code": "GS" },
{ "game": 4, "away_team": "Pacers", "away_code": "AX", "home_team": "Warmups", "home_code": "CH" },
{ "game": 4, "away_team": "Trippers", "away_code": "C8", "home_team": "Brats", "home_code": "LW" },
{ "game": 5, "away_team": "Machines", "away_code": "HZ", "home_team": "Reds", "home_code": "PZ" },
{ "game": 5, "away_team": "Baseball Team", "away_code": "MM", "home_team": "Oysters", "home_code": "JR" },
{ "game": 5, "away_team": "Melonheads", "away_code": "TW", "home_team": "Marlins", "home_code": "LO" },
{ "game": 5, "away_team": "Penguins", "away_code": "GB", "home_team": "Patriots", "home_code": "BO" },
{ "game": 5, "away_team": "Raccoons", "away_code": "VS", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 5, "away_team": "Wombats", "away_code": "AP", "home_team": "Casa Houses", "home_code": "M@" },
{ "game": 5, "away_team": "Monsters", "away_code": "YY", "home_team": "Warmups", "home_code": "CH" },
{ "game": 5, "away_team": "Brats", "away_code": "LW", "home_team": "Salamis", "home_code": "GS" },
{ "game": 5, "away_team": "Dice", "away_code": "WS", "home_team": "Grebes", "home_code": "FF" },
{ "game": 5, "away_team": "Greasels", "away_code": "BF", "home_team": "Pacers", "home_code": "AX" },
{ "game": 5, "away_team": "Ostriches", "away_code": "NV", "home_team": "Trippers", "home_code": "C8" },
{ "game": 5, "away_team": "Rippin", "away_code": "IT", "home_team": "Beers", "home_code": "HC" },
{ "game": 6, "away_team": "Marlins", "away_code": "LO", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 6, "away_team": "Casa Houses", "away_code": "M@", "home_team": "Patriots", "home_code": "BO" },
{ "game": 6, "away_team": "Machines", "away_code": "HZ", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 6, "away_team": "Oysters", "away_code": "JR", "home_team": "Penguins", "home_code": "GB" },
{ "game": 6, "away_team": "Reds", "away_code": "PZ", "home_team": "Raccoons", "home_code": "VS" },
{ "game": 6, "away_team": "Baseball Team", "away_code": "MM", "home_team": "Wombats", "home_code": "AP" },
{ "game": 6, "away_team": "Grebes", "away_code": "FF", "home_team": "Trippers", "home_code": "C8" },
{ "game": 6, "away_team": "Beers", "away_code": "HC", "home_team": "Pacers", "home_code": "AX" },
{ "game": 6, "away_team": "Monsters", "away_code": "YY", "home_team": "Dice", "home_code": "WS" },
{ "game": 6, "away_team": "Salamis", "away_code": "GS", "home_team": "Greasels", "home_code": "BF" },
{ "game": 6, "away_team": "Warmups", "away_code": "CH", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 6, "away_team": "Brats", "away_code": "LW", "home_team": "Rippin", "home_code": "IT" },
{ "game": 7, "away_team": "Wombats", "away_code": "AP", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 7, "away_team": "Penguins", "away_code": "GB", "home_team": "Raccoons", "home_code": "VS" },
{ "game": 7, "away_team": "Skeeters", "away_code": "MC", "home_team": "Casa Houses", "home_code": "M@" },
{ "game": 7, "away_team": "Patriots", "away_code": "BO", "home_team": "Marlins", "home_code": "LO" },
{ "game": 7, "away_team": "Reds", "away_code": "PZ", "home_team": "Baseball Team", "home_code": "MM" },
{ "game": 7, "away_team": "Oysters", "away_code": "JR", "home_team": "Machines", "home_code": "HZ" },
{ "game": 7, "away_team": "Rippin", "away_code": "IT", "home_team": "Dice", "home_code": "WS" },
{ "game": 7, "away_team": "Greasels", "away_code": "BF", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 7, "away_team": "Trippers", "away_code": "C8", "home_team": "Beers", "home_code": "HC" },
{ "game": 7, "away_team": "Pacers", "away_code": "AX", "home_team": "Grebes", "home_code": "FF" },
{ "game": 7, "away_team": "Warmups", "away_code": "CH", "home_team": "Brats", "home_code": "LW" },
{ "game": 7, "away_team": "Salamis", "away_code": "GS", "home_team": "Monsters", "home_code": "YY" },
{ "game": 8, "away_team": "Melonheads", "away_code": "TW", "home_team": "Penguins", "home_code": "GB" },
{ "game": 8, "away_team": "Raccoons", "away_code": "VS", "home_team": "Wombats", "home_code": "AP" },
{ "game": 8, "away_team": "Oysters", "away_code": "JR", "home_team": "Casa Houses", "home_code": "M@" },
{ "game": 8, "away_team": "Reds", "away_code": "PZ", "home_team": "Marlins", "home_code": "LO" },
{ "game": 8, "away_team": "Baseball Team", "away_code": "MM", "home_team": "Patriots", "home_code": "BO" },
{ "game": 8, "away_team": "Machines", "away_code": "HZ", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 8, "away_team": "Dice", "away_code": "WS", "home_team": "Greasels", "home_code": "BF" },
{ "game": 8, "away_team": "Ostriches", "away_code": "NV", "home_team": "Rippin", "home_code": "IT" },
{ "game": 8, "away_team": "Salamis", "away_code": "GS", "home_team": "Beers", "home_code": "HC" },
{ "game": 8, "away_team": "Warmups", "away_code": "CH", "home_team": "Grebes", "home_code": "FF" },
{ "game": 8, "away_team": "Brats", "away_code": "LW", "home_team": "Pacers", "home_code": "AX" },
{ "game": 8, "away_team": "Monsters", "away_code": "YY", "home_team": "Trippers", "home_code": "C8" },
{ "game": 9, "away_team": "Marlins", "away_code": "LO", "home_team": "Casa Houses", "home_code": "M@" },
{ "game": 9, "away_team": "Skeeters", "away_code": "MC", "home_team": "Patriots", "home_code": "BO" },
{ "game": 9, "away_team": "Melonheads", "away_code": "TW", "home_team": "Oysters", "home_code": "JR" },
{ "game": 9, "away_team": "Penguins", "away_code": "GB", "home_team": "Reds", "home_code": "PZ" },
{ "game": 9, "away_team": "Raccoons", "away_code": "VS", "home_team": "Baseball Team", "home_code": "MM" },
{ "game": 9, "away_team": "Wombats", "away_code": "AP", "home_team": "Machines", "home_code": "HZ" },
{ "game": 9, "away_team": "Grebes", "away_code": "FF", "home_team": "Beers", "home_code": "HC" },
{ "game": 9, "away_team": "Trippers", "away_code": "C8", "home_team": "Pacers", "home_code": "AX" },
{ "game": 9, "away_team": "Dice", "away_code": "WS", "home_team": "Salamis", "home_code": "GS" },
{ "game": 9, "away_team": "Greasels", "away_code": "BF", "home_team": "Warmups", "home_code": "CH" },
{ "game": 9, "away_team": "Ostriches", "away_code": "NV", "home_team": "Brats", "home_code": "LW" },
{ "game": 9, "away_team": "Rippin", "away_code": "IT", "home_team": "Monsters", "home_code": "YY" },
{ "game": 10, "away_team": "Machines", "away_code": "HZ", "home_team": "Baseball Team", "home_code": "MM" },
{ "game": 10, "away_team": "Reds", "away_code": "PZ", "home_team": "Oysters", "home_code": "JR" },
{ "game": 10, "away_team": "Patriots", "away_code": "BO", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 10, "away_team": "Skeeters", "away_code": "MC", "home_team": "Penguins", "home_code": "GB" },
{ "game": 10, "away_team": "Casa Houses", "away_code": "M@", "home_team": "Raccoons", "home_code": "VS" },
{ "game": 10, "away_team": "Marlins", "away_code": "LO", "home_team": "Wombats", "home_code": "AP" },
{ "game": 10, "away_team": "Monsters", "away_code": "YY", "home_team": "Brats", "home_code": "LW" },
{ "game": 10, "away_team": "Warmups", "away_code": "CH", "home_team": "Salamis", "home_code": "GS" },
{ "game": 10, "away_team": "Pacers", "away_code": "AX", "home_team": "Dice", "home_code": "WS" },
{ "game": 10, "away_team": "Trippers", "away_code": "C8", "home_team": "Greasels", "home_code": "BF" },
{ "game": 10, "away_team": "Beers", "away_code": "HC", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 10, "away_team": "Grebes", "away_code": "FF", "home_team": "Rippin", "home_code": "IT" },
{ "game": 11, "away_team": "Reds", "away_code": "PZ", "home_team": "Machines", "home_code": "HZ" },
{ "game": 11, "away_team": "Oysters", "away_code": "JR", "home_team": "Baseball Team", "home_code": "MM" },
{ "game": 11, "away_team": "Melonheads", "away_code": "TW", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 11, "away_team": "Penguins", "away_code": "GB", "home_team": "Casa Houses", "home_code": "M@" },
{ "game": 11, "away_team": "Raccoons", "away_code": "VS", "home_team": "Marlins", "home_code": "LO" },
{ "game": 11, "away_team": "Wombats", "away_code": "AP", "home_team": "Patriots", "home_code": "BO" },
{ "game": 11, "away_team": "Warmups", "away_code": "CH", "home_team": "Monsters", "home_code": "YY" },
{ "game": 11, "away_team": "Salamis", "away_code": "GS", "home_team": "Brats", "home_code": "LW" },
{ "game": 11, "away_team": "Dice", "away_code": "WS", "home_team": "Trippers", "home_code": "C8" },
{ "game": 11, "away_team": "Greasels", "away_code": "BF", "home_team": "Beers", "home_code": "HC" },
{ "game": 11, "away_team": "Ostriches", "away_code": "NV", "home_team": "Grebes", "home_code": "FF" },
{ "game": 11, "away_team": "Rippin", "away_code": "IT", "home_team": "Pacers", "home_code": "AX" },
{ "game": 12, "away_team": "Skeeters", "away_code": "MC", "home_team": "Marlins", "home_code": "LO" },
{ "game": 12, "away_team": "Patriots", "away_code": "BO", "home_team": "Casa Houses", "home_code": "M@" },
{ "game": 12, "away_team": "Reds", "away_code": "PZ", "home_team": "Melonheads", "home_code": "TW" },
{ "game": 12, "away_team": "Baseball Team", "away_code": "MM", "home_team": "Penguins", "home_code": "GB" },
{ "game": 12, "away_team": "Machines", "away_code": "HZ", "home_team": "Raccoons", "home_code": "VS" },
{ "game": 12, "away_team": "Oysters", "away_code": "JR", "home_team": "Wombats", "home_code": "AP" },
{ "game": 12, "away_team": "Trippers", "away_code": "C8", "home_team": "Grebes", "home_code": "FF" },
{ "game": 12, "away_team": "Pacers", "away_code": "AX", "home_team": "Beers", "home_code": "HC" },
{ "game": 12, "away_team": "Warmups", "away_code": "CH", "home_team": "Dice", "home_code": "WS" },
{ "game": 12, "away_team": "Brats", "away_code": "LW", "home_team": "Greasels", "home_code": "BF" },
{ "game": 12, "away_team": "Monsters", "away_code": "YY", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 12, "away_team": "Salamis", "away_code": "GS", "home_team": "Rippin", "home_code": "IT" },
{ "game": 13, "away_team": "Wombats", "away_code": "AP", "home_team": "Penguins", "home_code": "GB" },
{ "game": 13, "away_team": "Melonheads", "away_code": "TW", "home_team": "Raccoons", "home_code": "VS" },
{ "game": 13, "away_team": "Casa Houses", "away_code": "M@", "home_team": "Reds", "home_code": "PZ" },
{ "game": 13, "away_team": "Marlins", "away_code": "LO", "home_team": "Baseball Team", "home_code": "MM" },
{ "game": 13, "away_team": "Patriots", "away_code": "BO", "home_team": "Machines", "home_code": "HZ" },
{ "game": 13, "away_team": "Skeeters", "away_code": "MC", "home_team": "Oysters", "home_code": "JR" },
{ "game": 13, "away_team": "Rippin", "away_code": "IT", "home_team": "Greasels", "home_code": "BF" },
{ "game": 13, "away_team": "Dice", "away_code": "WS", "home_team": "Ostriches", "home_code": "NV" },
{ "game": 13, "away_team": "Beers", "away_code": "HC", "home_team": "Warmups", "home_code": "CH" },
{ "game": 13, "away_team": "Grebes", "away_code": "FF", "home_team": "Brats", "home_code": "LW" },
{ "game": 13, "away_team": "Pacers", "away_code": "AX", "home_team": "Monsters", "home_code": "YY" },
{ "game": 13, "away_team": "Trippers", "away_code": "C8", "home_team": "Salamis", "home_code": "GS" },
{ "game": 14, "away_team": "Melonheads", "away_code": "TW", "home_team": "Wombats", "home_code": "AP" },
{ "game": 14, "away_team": "Raccoons", "away_code": "VS", "home_team": "Penguins", "home_code": "GB" },
{ "game": 14, "away_team": "Casa Houses", "away_code": "M@", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 14, "away_team": "Marlins", "away_code": "LO", "home_team": "Patriots", "home_code": "BO" },
{ "game": 14, "away_team": "Baseball Team", "away_code": "MM", "home_team": "Reds", "home_code": "PZ" },
{ "game": 14, "away_team": "Machines", "away_code": "HZ", "home_team": "Oysters", "home_code": "JR" },
{ "game": 14, "away_team": "Dice", "away_code": "WS", "home_team": "Rippin", "home_code": "IT" },
{ "game": 14, "away_team": "Ostriches", "away_code": "NV", "home_team": "Greasels", "home_code": "BF" },
{ "game": 14, "away_team": "Beers", "away_code": "HC", "home_team": "Trippers", "home_code": "C8" },
{ "game": 14, "away_team": "Grebes", "away_code": "FF", "home_team": "Pacers", "home_code": "AX" },
{ "game": 14, "away_team": "Brats", "away_code": "LW", "home_team": "Warmups", "home_code": "CH" },
{ "game": 14, "away_team": "Monsters", "away_code": "YY", "home_team": "Salamis", "home_code": "GS" }   
 ]
module.exports = { s1401teams, s1401schedule};
