// http://www.convertcsv.com/csv-to-json.htm

const s1402teams = {
    "Expos": "<@1224263062996123678>",
    "Usuals": "<@1071144968435028049>",
    "Frogs": "<@1306533265422680156>",
    "Snow Cones": "<@1071145998656737360>",
    "Lions": "<@1306541154422099969>",
    "Astros": "<@900907535983329291>",
    "Red Sox": "<@1067536861570023424>",
    "Monopolies": "<@1306532385982255125>",
    "Wombats": "<@668468071861583891>",
    "Bananas": "<@1071145277362274434>",
    "Bombers": "<@703992227160129667>",
    "Dragons": "<@484763804236906497>",
    "Hornets": "<@603606321492787210>",
    "Giants": "<@1306528207994093639>",
    "Diamondbacks": "<@1224278068495908874>",
    "Golds": "<@1224267311993716770>",
    "Mets": "<@847666608852041778>",
    "Sapphire": "<@702678421423128637>",
    "Racers": "<@496713526778265624>",
    "Bullpups": "<@670773176984403982>",
    "Dubbleplays": "<@702678271749390457>",
    "Chanticleers": "<@1067528046451642418>",
    "Badgers": "<@496815444116635658>",
    "Atoms": "<@1361223974649860126>",
    
};

//"game": "1",
//"away_team": "As",
//"away_code": "NF",
//"home_team": "Red Sox",
//"home_code": "XD"

const s1402schedule =[
{ "game": 1, "away_team": "Atoms", "away_code": "AA", "home_team": "Badgers", "home_code": "MD" },
{ "game": 1, "away_team": "Wombats", "away_code": "BC", "home_team": "Chanticleers", "home_code": "DK" },
{ "game": 1, "away_team": "Diamondbacks", "away_code": "JL", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 1, "away_team": "Giants", "away_code": "R6", "home_team": "Dubbleplays", "home_code": "CD" },
{ "game": 1, "away_team": "Golds", "away_code": "GY", "home_team": "Racers", "home_code": "AD" },
{ "game": 1, "away_team": "Mets", "away_code": "MK", "home_team": "Sapphire", "home_code": "PB" },
{ "game": 1, "away_team": "Bananas", "away_code": "FN", "home_team": "Bombers", "home_code": "RR" },
{ "game": 1, "away_team": "Hornets", "away_code": "WW", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 1, "away_team": "Expos", "away_code": "95", "home_team": "Astros", "home_code": "JB" },
{ "game": 1, "away_team": "Frogs", "away_code": "WC", "home_team": "Lions", "home_code": "IS" },
{ "game": 1, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 1, "away_team": "Usuals", "away_code": "MU", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 2, "away_team": "Diamondbacks", "away_code": "JL", "home_team": "Giants", "home_code": "R6" },
{ "game": 2, "away_team": "Golds", "away_code": "GY", "home_team": "Mets", "home_code": "MK" },
{ "game": 2, "away_team": "Bullpups", "away_code": "HM", "home_team": "Badgers", "home_code": "MD" },
{ "game": 2, "away_team": "Dubbleplays", "away_code": "CD", "home_team": "Atoms", "home_code": "AA" },
{ "game": 2, "away_team": "Racers", "away_code": "AD", "home_team": "Chanticleers", "home_code": "DK" },
{ "game": 2, "away_team": "Sapphire", "away_code": "PB", "home_team": "Wombats", "home_code": "BC" },
{ "game": 2, "away_team": "Expos", "away_code": "95", "home_team": "Frogs", "home_code": "WC" },
{ "game": 2, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Usuals", "home_code": "MU" },
{ "game": 2, "away_team": "Astros", "away_code": "JB", "home_team": "Bombers", "home_code": "RR" },
{ "game": 2, "away_team": "Lions", "away_code": "IS", "home_team": "Bananas", "home_code": "FN" },
{ "game": 2, "away_team": "Monopolies", "away_code": "W1", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 2, "away_team": "Red Sox", "away_code": "NP", "home_team": "Hornets", "home_code": "WW" },
{ "game": 3, "away_team": "Bullpups", "away_code": "HM", "home_team": "Dubbleplays", "home_code": "CD" },
{ "game": 3, "away_team": "Racers", "away_code": "AD", "home_team": "Sapphire", "home_code": "PB" },
{ "game": 3, "away_team": "Badgers", "away_code": "MD", "home_team": "Diamondbacks", "home_code": "JL" },
{ "game": 3, "away_team": "Atoms", "away_code": "AA", "home_team": "Giants", "home_code": "R6" },
{ "game": 3, "away_team": "Chanticleers", "away_code": "DK", "home_team": "Golds", "home_code": "GY" },
{ "game": 3, "away_team": "Wombats", "away_code": "BC", "home_team": "Mets", "home_code": "MK" },
{ "game": 3, "away_team": "Astros", "away_code": "JB", "home_team": "Lions", "home_code": "IS" },
{ "game": 3, "away_team": "Monopolies", "away_code": "W1", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 3, "away_team": "Bombers", "away_code": "RR", "home_team": "Expos", "home_code": "95" },
{ "game": 3, "away_team": "Bananas", "away_code": "FN", "home_team": "Frogs", "home_code": "WC" },
{ "game": 3, "away_team": "Dragons", "away_code": "FJ", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 3, "away_team": "Hornets", "away_code": "WW", "home_team": "Usuals", "home_code": "MU" },
{ "game": 4, "away_team": "Atoms", "away_code": "AA", "home_team": "Wombats", "home_code": "BC" },
{ "game": 4, "away_team": "Chanticleers", "away_code": "DK", "home_team": "Badgers", "home_code": "MD" },
{ "game": 4, "away_team": "Diamondbacks", "away_code": "JL", "home_team": "Dubbleplays", "home_code": "CD" },
{ "game": 4, "away_team": "Giants", "away_code": "R6", "home_team": "Racers", "home_code": "AD" },
{ "game": 4, "away_team": "Golds", "away_code": "GY", "home_team": "Sapphire", "home_code": "PB" },
{ "game": 4, "away_team": "Mets", "away_code": "MK", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 4, "away_team": "Bananas", "away_code": "FN", "home_team": "Hornets", "home_code": "WW" },
{ "game": 4, "away_team": "Dragons", "away_code": "FJ", "home_team": "Bombers", "home_code": "RR" },
{ "game": 4, "away_team": "Expos", "away_code": "95", "home_team": "Lions", "home_code": "IS" },
{ "game": 4, "away_team": "Frogs", "away_code": "WC", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 4, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 4, "away_team": "Usuals", "away_code": "MU", "home_team": "Astros", "home_code": "JB" },
{ "game": 5, "away_team": "Dubbleplays", "away_code": "CD", "home_team": "Sapphire", "home_code": "PB" },
{ "game": 5, "away_team": "Bullpups", "away_code": "HM", "home_team": "Racers", "home_code": "AD" },
{ "game": 5, "away_team": "Badgers", "away_code": "MD", "home_team": "Giants", "home_code": "R6" },
{ "game": 5, "away_team": "Atoms", "away_code": "AA", "home_team": "Golds", "home_code": "GY" },
{ "game": 5, "away_team": "Chanticleers", "away_code": "DK", "home_team": "Mets", "home_code": "MK" },
{ "game": 5, "away_team": "Wombats", "away_code": "BC", "home_team": "Diamondbacks", "home_code": "JL" },
{ "game": 5, "away_team": "Lions", "away_code": "IS", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 5, "away_team": "Astros", "away_code": "JB", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 5, "away_team": "Bombers", "away_code": "RR", "home_team": "Frogs", "home_code": "WC" },
{ "game": 5, "away_team": "Bananas", "away_code": "FN", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 5, "away_team": "Dragons", "away_code": "FJ", "home_team": "Usuals", "home_code": "MU" },
{ "game": 5, "away_team": "Hornets", "away_code": "WW", "home_team": "Expos", "home_code": "95" },
{ "game": 6, "away_team": "Giants", "away_code": "R6", "home_team": "Mets", "home_code": "MK" },
{ "game": 6, "away_team": "Diamondbacks", "away_code": "JL", "home_team": "Golds", "home_code": "GY" },
{ "game": 6, "away_team": "Dubbleplays", "away_code": "CD", "home_team": "Badgers", "home_code": "MD" },
{ "game": 6, "away_team": "Racers", "away_code": "AD", "home_team": "Atoms", "home_code": "AA" },
{ "game": 6, "away_team": "Sapphire", "away_code": "PB", "home_team": "Chanticleers", "home_code": "DK" },
{ "game": 6, "away_team": "Bullpups", "away_code": "HM", "home_team": "Wombats", "home_code": "BC" },
{ "game": 6, "away_team": "Frogs", "away_code": "WC", "home_team": "Usuals", "home_code": "MU" },
{ "game": 6, "away_team": "Expos", "away_code": "95", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 6, "away_team": "Lions", "away_code": "IS", "home_team": "Bombers", "home_code": "RR" },
{ "game": 6, "away_team": "Monopolies", "away_code": "W1", "home_team": "Bananas", "home_code": "FN" },
{ "game": 6, "away_team": "Red Sox", "away_code": "NP", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 6, "away_team": "Astros", "away_code": "JB", "home_team": "Hornets", "home_code": "WW" },
{ "game": 7, "away_team": "Wombats", "away_code": "BC", "home_team": "Badgers", "home_code": "MD" },
{ "game": 7, "away_team": "Atoms", "away_code": "AA", "home_team": "Chanticleers", "home_code": "DK" },
{ "game": 7, "away_team": "Mets", "away_code": "MK", "home_team": "Diamondbacks", "home_code": "JL" },
{ "game": 7, "away_team": "Golds", "away_code": "GY", "home_team": "Giants", "home_code": "R6" },
{ "game": 7, "away_team": "Sapphire", "away_code": "PB", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 7, "away_team": "Racers", "away_code": "AD", "home_team": "Dubbleplays", "home_code": "CD" },
{ "game": 7, "away_team": "Hornets", "away_code": "WW", "home_team": "Bombers", "home_code": "RR" },
{ "game": 7, "away_team": "Bananas", "away_code": "FN", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 7, "away_team": "Usuals", "away_code": "MU", "home_team": "Expos", "home_code": "95" },
{ "game": 7, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Frogs", "home_code": "WC" },
{ "game": 7, "away_team": "Red Sox", "away_code": "NP", "home_team": "Astros", "home_code": "JB" },
{ "game": 7, "away_team": "Monopolies", "away_code": "W1", "home_team": "Lions", "home_code": "IS" },
{ "game": 8, "away_team": "Badgers", "away_code": "MD", "home_team": "Atoms", "home_code": "AA" },
{ "game": 8, "away_team": "Chanticleers", "away_code": "DK", "home_team": "Wombats", "home_code": "BC" },
{ "game": 8, "away_team": "Racers", "away_code": "AD", "home_team": "Diamondbacks", "home_code": "JL" },
{ "game": 8, "away_team": "Sapphire", "away_code": "PB", "home_team": "Giants", "home_code": "R6" },
{ "game": 8, "away_team": "Bullpups", "away_code": "HM", "home_team": "Golds", "home_code": "GY" },
{ "game": 8, "away_team": "Dubbleplays", "away_code": "CD", "home_team": "Mets", "home_code": "MK" },
{ "game": 8, "away_team": "Bombers", "away_code": "RR", "home_team": "Bananas", "home_code": "FN" },
{ "game": 8, "away_team": "Dragons", "away_code": "FJ", "home_team": "Hornets", "home_code": "WW" },
{ "game": 8, "away_team": "Monopolies", "away_code": "W1", "home_team": "Expos", "home_code": "95" },
{ "game": 8, "away_team": "Red Sox", "away_code": "NP", "home_team": "Frogs", "home_code": "WC" },
{ "game": 8, "away_team": "Astros", "away_code": "JB", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 8, "away_team": "Lions", "away_code": "IS", "home_team": "Usuals", "home_code": "MU" },
{ "game": 9, "away_team": "Giants", "away_code": "R6", "home_team": "Diamondbacks", "home_code": "JL" },
{ "game": 9, "away_team": "Mets", "away_code": "MK", "home_team": "Golds", "home_code": "GY" },
{ "game": 9, "away_team": "Badgers", "away_code": "MD", "home_team": "Racers", "home_code": "AD" },
{ "game": 9, "away_team": "Atoms", "away_code": "AA", "home_team": "Sapphire", "home_code": "PB" },
{ "game": 9, "away_team": "Chanticleers", "away_code": "DK", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 9, "away_team": "Wombats", "away_code": "BC", "home_team": "Dubbleplays", "home_code": "CD" },
{ "game": 9, "away_team": "Frogs", "away_code": "WC", "home_team": "Expos", "home_code": "95" },
{ "game": 9, "away_team": "Usuals", "away_code": "MU", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 9, "away_team": "Bombers", "away_code": "RR", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 9, "away_team": "Bananas", "away_code": "FN", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 9, "away_team": "Dragons", "away_code": "FJ", "home_team": "Astros", "home_code": "JB" },
{ "game": 9, "away_team": "Hornets", "away_code": "WW", "home_team": "Lions", "home_code": "IS" },
{ "game": 10, "away_team": "Dubbleplays", "away_code": "CD", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 10, "away_team": "Sapphire", "away_code": "PB", "home_team": "Racers", "home_code": "AD" },
{ "game": 10, "away_team": "Golds", "away_code": "GY", "home_team": "Badgers", "home_code": "MD" },
{ "game": 10, "away_team": "Mets", "away_code": "MK", "home_team": "Atoms", "home_code": "AA" },
{ "game": 10, "away_team": "Diamondbacks", "away_code": "JL", "home_team": "Chanticleers", "home_code": "DK" },
{ "game": 10, "away_team": "Giants", "away_code": "R6", "home_team": "Wombats", "home_code": "BC" },
{ "game": 10, "away_team": "Lions", "away_code": "IS", "home_team": "Astros", "home_code": "JB" },
{ "game": 10, "away_team": "Red Sox", "away_code": "NP", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 10, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Bombers", "home_code": "RR" },
{ "game": 10, "away_team": "Usuals", "away_code": "MU", "home_team": "Bananas", "home_code": "FN" },
{ "game": 10, "away_team": "Expos", "away_code": "95", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 10, "away_team": "Frogs", "away_code": "WC", "home_team": "Hornets", "home_code": "WW" },
{ "game": 11, "away_team": "Sapphire", "away_code": "PB", "home_team": "Dubbleplays", "home_code": "CD" },
{ "game": 11, "away_team": "Racers", "away_code": "AD", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 11, "away_team": "Badgers", "away_code": "MD", "home_team": "Mets", "home_code": "MK" },
{ "game": 11, "away_team": "Atoms", "away_code": "AA", "home_team": "Diamondbacks", "home_code": "JL" },
{ "game": 11, "away_team": "Chanticleers", "away_code": "DK", "home_team": "Giants", "home_code": "R6" },
{ "game": 11, "away_team": "Wombats", "away_code": "BC", "home_team": "Golds", "home_code": "GY" },
{ "game": 11, "away_team": "Red Sox", "away_code": "NP", "home_team": "Lions", "home_code": "IS" },
{ "game": 11, "away_team": "Monopolies", "away_code": "W1", "home_team": "Astros", "home_code": "JB" },
{ "game": 11, "away_team": "Bombers", "away_code": "RR", "home_team": "Usuals", "home_code": "MU" },
{ "game": 11, "away_team": "Bananas", "away_code": "FN", "home_team": "Expos", "home_code": "95" },
{ "game": 11, "away_team": "Dragons", "away_code": "FJ", "home_team": "Frogs", "home_code": "WC" },
{ "game": 11, "away_team": "Hornets", "away_code": "WW", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 12, "away_team": "Mets", "away_code": "MK", "home_team": "Giants", "home_code": "R6" },
{ "game": 12, "away_team": "Golds", "away_code": "GY", "home_team": "Diamondbacks", "home_code": "JL" },
{ "game": 12, "away_team": "Sapphire", "away_code": "PB", "home_team": "Badgers", "home_code": "MD" },
{ "game": 12, "away_team": "Bullpups", "away_code": "HM", "home_team": "Atoms", "home_code": "AA" },
{ "game": 12, "away_team": "Dubbleplays", "away_code": "CD", "home_team": "Chanticleers", "home_code": "DK" },
{ "game": 12, "away_team": "Racers", "away_code": "AD", "home_team": "Wombats", "home_code": "BC" },
{ "game": 12, "away_team": "Usuals", "away_code": "MU", "home_team": "Frogs", "home_code": "WC" },
{ "game": 12, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Expos", "home_code": "95" },
{ "game": 12, "away_team": "Red Sox", "away_code": "NP", "home_team": "Bombers", "home_code": "RR" },
{ "game": 12, "away_team": "Astros", "away_code": "JB", "home_team": "Bananas", "home_code": "FN" },
{ "game": 12, "away_team": "Lions", "away_code": "IS", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 12, "away_team": "Monopolies", "away_code": "W1", "home_team": "Hornets", "home_code": "WW" },
{ "game": 13, "away_team": "Wombats", "away_code": "BC", "home_team": "Atoms", "home_code": "AA" },
{ "game": 13, "away_team": "Badgers", "away_code": "MD", "home_team": "Chanticleers", "home_code": "DK" },
{ "game": 13, "away_team": "Diamondbacks", "away_code": "JL", "home_team": "Sapphire", "home_code": "PB" },
{ "game": 13, "away_team": "Giants", "away_code": "R6", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 13, "away_team": "Golds", "away_code": "GY", "home_team": "Dubbleplays", "home_code": "CD" },
{ "game": 13, "away_team": "Mets", "away_code": "MK", "home_team": "Racers", "home_code": "AD" },
{ "game": 13, "away_team": "Hornets", "away_code": "WW", "home_team": "Bananas", "home_code": "FN" },
{ "game": 13, "away_team": "Bombers", "away_code": "RR", "home_team": "Dragons", "home_code": "FJ" },
{ "game": 13, "away_team": "Expos", "away_code": "95", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 13, "away_team": "Frogs", "away_code": "WC", "home_team": "Astros", "home_code": "JB" },
{ "game": 13, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Lions", "home_code": "IS" },
{ "game": 13, "away_team": "Usuals", "away_code": "MU", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 14, "away_team": "Badgers", "away_code": "MD", "home_team": "Wombats", "home_code": "BC" },
{ "game": 14, "away_team": "Chanticleers", "away_code": "DK", "home_team": "Atoms", "home_code": "AA" },
{ "game": 14, "away_team": "Diamondbacks", "away_code": "JL", "home_team": "Mets", "home_code": "MK" },
{ "game": 14, "away_team": "Giants", "away_code": "R6", "home_team": "Golds", "home_code": "GY" },
{ "game": 14, "away_team": "Bullpups", "away_code": "HM", "home_team": "Sapphire", "home_code": "PB" },
{ "game": 14, "away_team": "Dubbleplays", "away_code": "CD", "home_team": "Racers", "home_code": "AD" },
{ "game": 14, "away_team": "Bombers", "away_code": "RR", "home_team": "Hornets", "home_code": "WW" },
{ "game": 14, "away_team": "Dragons", "away_code": "FJ", "home_team": "Bananas", "home_code": "FN" },
{ "game": 14, "away_team": "Expos", "away_code": "95", "home_team": "Usuals", "home_code": "MU" },
{ "game": 14, "away_team": "Frogs", "away_code": "WC", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 14, "away_team": "Astros", "away_code": "JB", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 14, "away_team": "Lions", "away_code": "IS", "home_team": "Monopolies", "home_code": "W1" }
   
 ]
module.exports = { s1402teams, s1402schedule};
