const s1502teams = {
"Skeeters": "<@&847665786708688936>",
"Tornados": "<@&1451367092338163905>",
"Phillies": "<@&1067544069221392414>",
"Mets": "<@&1486814075047645407>",
"Mothmen": "<@&1224762411853287475>",
"Bombers": "<@&1069707239478272131>",
"Policemen": "<@&1071144968435028049>",
"Lumberlobos": "<@&603606321492787210>",
"Lightning": "<@&702678271749390457>",
"Smores": "<@&496817420753960961>",
"Wombats": "<@&496815444116635658>",
"Red Sox": "<@&1067536861570023424>",
"Figures": "<@&703992227160129667>",
"Monarchs": "<@&604520363673518119>",
"Bankees": "<@&668468071861583891>",
"Penguins": "<@&1488357585227874344>",
"Fireballs": "<@&783577309000368189>",
"Warmups": "<@&1067670617094094878>",
"Waffles": "<@&484763804236906497>",
"Wildcards": "<@&1224790518819717312>",
"Frogs": "<@&1306533265422680156>",
"Feraligatr": "<@&1306541040886485062>",
"Storm": "<@&900907535983329291>",
"-200 Boys": "<@&1067672079060713512>",
"Monopolies": "<@&1306532385982255125>",
"Goblins": "<@&448576195190063110>",
"Crows": "<@&1224278068495908874>",
"Bananas": "<@&1071145277362274434>",
};

const s1502schedule =[

{ "game": 1, "away_team": "Penguins", "away_code": "JS", "home_team": "Lightning", "home_code": "SE" },
{ "game": 1, "away_team": "Waffles", "away_code": "FJ", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 1, "away_team": "Phillies", "away_code": "MK", "home_team": "Policemen", "home_code": "MU" },
{ "game": 1, "away_team": "-200 Boys", "away_code": "CM", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 1, "away_team": "Wildcards", "away_code": "ME", "home_team": "Lumberlobos", "home_code": "P9" },
{ "game": 1, "away_team": "Monarchs", "away_code": "OB", "home_team": "Mets", "home_code": "AD" },
{ "game": 1, "away_team": "Wombats", "away_code": "ST", "home_team": "Bankees", "home_code": "SW" },
{ "game": 1, "away_team": "Warmups", "away_code": "CH", "home_team": "Fireballs", "home_code": "BR" },
{ "game": 1, "away_team": "Mothmen", "away_code": "SB", "home_team": "Storm", "home_code": "JB" },
{ "game": 1, "away_team": "Frogs", "away_code": "WC", "home_team": "Bombers", "home_code": "SR" },
{ "game": 1, "away_team": "Smores", "away_code": "GG", "home_team": "Bananas", "home_code": "FN" },
{ "game": 1, "away_team": "Goblins", "away_code": "GE", "home_team": "Figures", "home_code": "RR" },
{ "game": 1, "away_team": "Feraligatr", "away_code": "B3", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 1, "away_team": "Tornados", "away_code": "DK", "home_team": "Crows", "home_code": "KJ" },
{ "game": 2, "away_team": "Monarchs", "away_code": "OB", "home_team": "Penguins", "home_code": "JS" },
{ "game": 2, "away_team": "Wombats", "away_code": "ST", "home_team": "Waffles", "home_code": "FJ" },
{ "game": 2, "away_team": "Bankees", "away_code": "SW", "home_team": "Phillies", "home_code": "MK" },
{ "game": 2, "away_team": "Mets", "away_code": "AD", "home_team": "Policemen", "home_code": "MU" },
{ "game": 2, "away_team": "Lumberlobos", "away_code": "P9", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 2, "away_team": "Skeeters", "away_code": "MC", "home_team": "Lightning", "home_code": "SE" },
{ "game": 2, "away_team": "Wildcards", "away_code": "ME", "home_team": "-200 Boys", "home_code": "CM" },
{ "game": 2, "away_team": "Feraligatr", "away_code": "B3", "home_team": "Warmups", "home_code": "CH" },
{ "game": 2, "away_team": "Tornados", "away_code": "DK", "home_team": "Mothmen", "home_code": "SB" },
{ "game": 2, "away_team": "Crows", "away_code": "KJ", "home_team": "Frogs", "home_code": "WC" },
{ "game": 2, "away_team": "Monopolies", "away_code": "W1", "home_team": "Bombers", "home_code": "SR" },
{ "game": 2, "away_team": "Figures", "away_code": "RR", "home_team": "Storm", "home_code": "JB" },
{ "game": 2, "away_team": "Bananas", "away_code": "FN", "home_team": "Fireballs", "home_code": "BR" },
{ "game": 2, "away_team": "Goblins", "away_code": "GE", "home_team": "Smores", "home_code": "GG" },
{ "game": 3, "away_team": "Policemen", "away_code": "MU", "home_team": "Waffles", "home_code": "FJ" },
{ "game": 3, "away_team": "Red Sox", "away_code": "NP", "home_team": "Penguins", "home_code": "JS" },
{ "game": 3, "away_team": "Lightning", "away_code": "SE", "home_team": "-200 Boys", "home_code": "CM" },
{ "game": 3, "away_team": "Phillies", "away_code": "MK", "home_team": "Wombats", "home_code": "ST" },
{ "game": 3, "away_team": "Bankees", "away_code": "SW", "home_team": "Monarchs", "home_code": "OB" },
{ "game": 3, "away_team": "Mets", "away_code": "AD", "home_team": "Wildcards", "home_code": "ME" },
{ "game": 3, "away_team": "Lumberlobos", "away_code": "P9", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 3, "away_team": "Bombers", "away_code": "SR", "home_team": "Mothmen", "home_code": "SB" },
{ "game": 3, "away_team": "Warmups", "away_code": "CH", "home_team": "Storm", "home_code": "JB" },
{ "game": 3, "away_team": "Fireballs", "away_code": "BR", "home_team": "Smores", "home_code": "GG" },
{ "game": 3, "away_team": "Frogs", "away_code": "WC", "home_team": "Tornados", "home_code": "DK" },
{ "game": 3, "away_team": "Crows", "away_code": "KJ", "home_team": "Feraligatr", "home_code": "B3" },
{ "game": 3, "away_team": "Monopolies", "away_code": "W1", "home_team": "Goblins", "home_code": "GE" },
{ "game": 3, "away_team": "Figures", "away_code": "RR", "home_team": "Bananas", "home_code": "FN" },
{ "game": 4, "away_team": "Penguins", "away_code": "JS", "home_team": "Wombats", "home_code": "ST" },
{ "game": 4, "away_team": "Waffles", "away_code": "FJ", "home_team": "Bankees", "home_code": "SW" },
{ "game": 4, "away_team": "Phillies", "away_code": "MK", "home_team": "Mets", "home_code": "AD" },
{ "game": 4, "away_team": "Policemen", "away_code": "MU", "home_team": "Lumberlobos", "home_code": "P9" },
{ "game": 4, "away_team": "Red Sox", "away_code": "NP", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 4, "away_team": "Lightning", "away_code": "SE", "home_team": "Wildcards", "home_code": "ME" },
{ "game": 4, "away_team": "-200 Boys", "away_code": "CM", "home_team": "Monarchs", "home_code": "OB" },
{ "game": 4, "away_team": "Warmups", "away_code": "CH", "home_team": "Tornados", "home_code": "DK" },
{ "game": 4, "away_team": "Mothmen", "away_code": "SB", "home_team": "Crows", "home_code": "KJ" },
{ "game": 4, "away_team": "Frogs", "away_code": "WC", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 4, "away_team": "Figures", "away_code": "RR", "home_team": "Bombers", "home_code": "SR" },
{ "game": 4, "away_team": "Storm", "away_code": "JB", "home_team": "Bananas", "home_code": "FN" },
{ "game": 4, "away_team": "Fireballs", "away_code": "BR", "home_team": "Goblins", "home_code": "GE" },
{ "game": 4, "away_team": "Smores", "away_code": "GG", "home_team": "Feraligatr", "home_code": "B3" },
{ "game": 5, "away_team": "Waffles", "away_code": "FJ", "home_team": "-200 Boys", "home_code": "CM" },
{ "game": 5, "away_team": "Phillies", "away_code": "MK", "home_team": "Lightning", "home_code": "SE" },
{ "game": 5, "away_team": "Policemen", "away_code": "MU", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 5, "away_team": "Penguins", "away_code": "JS", "home_team": "Wildcards", "home_code": "ME" },
{ "game": 5, "away_team": "Monarchs", "away_code": "OB", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 5, "away_team": "Wombats", "away_code": "ST", "home_team": "Lumberlobos", "home_code": "P9" },
{ "game": 5, "away_team": "Bankees", "away_code": "SW", "home_team": "Mets", "home_code": "AD" },
{ "game": 5, "away_team": "Mothmen", "away_code": "SB", "home_team": "Smores", "home_code": "GG" },
{ "game": 5, "away_team": "Frogs", "away_code": "WC", "home_team": "Fireballs", "home_code": "BR" },
{ "game": 5, "away_team": "Storm", "away_code": "JB", "home_team": "Bombers", "home_code": "SR" },
{ "game": 5, "away_team": "Warmups", "away_code": "CH", "home_team": "Goblins", "home_code": "GE" },
{ "game": 5, "away_team": "Feraligatr", "away_code": "B3", "home_team": "Bananas", "home_code": "FN" },
{ "game": 5, "away_team": "Tornados", "away_code": "DK", "home_team": "Figures", "home_code": "RR" },
{ "game": 5, "away_team": "Crows", "away_code": "KJ", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 7, "away_team": "Penguins", "away_code": "JS", "home_team": "Bankees", "home_code": "SW" },
{ "game": 7, "away_team": "Waffles", "away_code": "FJ", "home_team": "Mets", "home_code": "AD" },
{ "game": 7, "away_team": "Phillies", "away_code": "MK", "home_team": "Lumberlobos", "home_code": "P9" },
{ "game": 7, "away_team": "Policemen", "away_code": "MU", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 7, "away_team": "Red Sox", "away_code": "NP", "home_team": "Wildcards", "home_code": "ME" },
{ "game": 7, "away_team": "Lightning", "away_code": "SE", "home_team": "Monarchs", "home_code": "OB" },
{ "game": 7, "away_team": "-200 Boys", "away_code": "CM", "home_team": "Wombats", "home_code": "ST" },
{ "game": 7, "away_team": "Warmups", "away_code": "CH", "home_team": "Crows", "home_code": "KJ" },
{ "game": 7, "away_team": "Mothmen", "away_code": "SB", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 7, "away_team": "Frogs", "away_code": "WC", "home_team": "Figures", "home_code": "RR" },
{ "game": 7, "away_team": "Bombers", "away_code": "SR", "home_team": "Bananas", "home_code": "FN" },
{ "game": 7, "away_team": "Storm", "away_code": "JB", "home_team": "Goblins", "home_code": "GE" },
{ "game": 7, "away_team": "Fireballs", "away_code": "BR", "home_team": "Feraligatr", "home_code": "B3" },
{ "game": 7, "away_team": "Smores", "away_code": "GG", "home_team": "Tornados", "home_code": "DK" },
{ "game": 6, "away_team": "Goblins", "away_code": "GE", "home_team": "Penguins", "home_code": "JS" },
{ "game": 6, "away_team": "Feraligatr", "away_code": "B3", "home_team": "Waffles", "home_code": "FJ" },
{ "game": 6, "away_team": "Tornados", "away_code": "DK", "home_team": "Phillies", "home_code": "MK" },
{ "game": 6, "away_team": "Crows", "away_code": "KJ", "home_team": "Policemen", "home_code": "MU" },
{ "game": 6, "away_team": "Monopolies", "away_code": "W1", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 6, "away_team": "Bombers", "away_code": "SR", "home_team": "Lightning", "home_code": "SE" },
{ "game": 6, "away_team": "Bananas", "away_code": "FN", "home_team": "-200 Boys", "home_code": "CM" },
{ "game": 6, "away_team": "Wildcards", "away_code": "ME", "home_team": "Warmups", "home_code": "CH" },
{ "game": 6, "away_team": "Monarchs", "away_code": "OB", "home_team": "Mothmen", "home_code": "SB" },
{ "game": 6, "away_team": "Wombats", "away_code": "ST", "home_team": "Frogs", "home_code": "WC" },
{ "game": 6, "away_team": "Bankees", "away_code": "SW", "home_team": "Figures", "home_code": "RR" },
{ "game": 6, "away_team": "Mets", "away_code": "AD", "home_team": "Storm", "home_code": "JB" },
{ "game": 6, "away_team": "Lumberlobos", "away_code": "P9", "home_team": "Fireballs", "home_code": "BR" },
{ "game": 6, "away_team": "Skeeters", "away_code": "MC", "home_team": "Smores", "home_code": "GG" },
{ "game": 8, "away_team": "Red Sox", "away_code": "NP", "home_team": "Phillies", "home_code": "MK" },
{ "game": 8, "away_team": "Lightning", "away_code": "SE", "home_team": "Waffles", "home_code": "FJ" },
{ "game": 8, "away_team": "-200 Boys", "away_code": "CM", "home_team": "Penguins", "home_code": "JS" },
{ "game": 8, "away_team": "Policemen", "away_code": "MU", "home_team": "Bankees", "home_code": "SW" },
{ "game": 8, "away_team": "Mets", "away_code": "AD", "home_team": "Wombats", "home_code": "ST" },
{ "game": 8, "away_team": "Lumberlobos", "away_code": "P9", "home_team": "Monarchs", "home_code": "OB" },
{ "game": 8, "away_team": "Skeeters", "away_code": "MC", "home_team": "Wildcards", "home_code": "ME" },
{ "game": 8, "away_team": "Storm", "away_code": "JB", "home_team": "Frogs", "home_code": "WC" },
{ "game": 8, "away_team": "Fireballs", "away_code": "BR", "home_team": "Mothmen", "home_code": "SB" },
{ "game": 8, "away_team": "Smores", "away_code": "GG", "home_team": "Warmups", "home_code": "CH" },
{ "game": 8, "away_team": "Bombers", "away_code": "SR", "home_team": "Crows", "home_code": "KJ" },
{ "game": 8, "away_team": "Monopolies", "away_code": "W1", "home_team": "Tornados", "home_code": "DK" },
{ "game": 8, "away_team": "Figures", "away_code": "RR", "home_team": "Feraligatr", "home_code": "B3" },
{ "game": 8, "away_team": "Bananas", "away_code": "FN", "home_team": "Goblins", "home_code": "GE" },
{ "game": 9, "away_team": "Mets", "away_code": "AD", "home_team": "Penguins", "home_code": "JS" },
{ "game": 9, "away_team": "Lumberlobos", "away_code": "P9", "home_team": "Waffles", "home_code": "FJ" },
{ "game": 9, "away_team": "Skeeters", "away_code": "MC", "home_team": "Phillies", "home_code": "MK" },
{ "game": 9, "away_team": "Wildcards", "away_code": "ME", "home_team": "Policemen", "home_code": "MU" },
{ "game": 9, "away_team": "Monarchs", "away_code": "OB", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 9, "away_team": "Wombats", "away_code": "ST", "home_team": "Lightning", "home_code": "SE" },
{ "game": 9, "away_team": "Bankees", "away_code": "SW", "home_team": "-200 Boys", "home_code": "CM" },
{ "game": 9, "away_team": "Monopolies", "away_code": "W1", "home_team": "Warmups", "home_code": "CH" },
{ "game": 9, "away_team": "Figures", "away_code": "RR", "home_team": "Mothmen", "home_code": "SB" },
{ "game": 9, "away_team": "Bananas", "away_code": "FN", "home_team": "Frogs", "home_code": "WC" },
{ "game": 9, "away_team": "Goblins", "away_code": "GE", "home_team": "Bombers", "home_code": "SR" },
{ "game": 9, "away_team": "Feraligatr", "away_code": "B3", "home_team": "Storm", "home_code": "JB" },
{ "game": 9, "away_team": "Tornados", "away_code": "DK", "home_team": "Fireballs", "home_code": "BR" },
{ "game": 9, "away_team": "Crows", "away_code": "KJ", "home_team": "Smores", "home_code": "GG" },
{ "game": 10, "away_team": "Phillies", "away_code": "MK", "home_team": "Penguins", "home_code": "JS" },
{ "game": 10, "away_team": "Policemen", "away_code": "MU", "home_team": "-200 Boys", "home_code": "CM" },
{ "game": 10, "away_team": "Red Sox", "away_code": "NP", "home_team": "Lightning", "home_code": "SE" },
{ "game": 10, "away_team": "Waffles", "away_code": "FJ", "home_team": "Monarchs", "home_code": "OB" },
{ "game": 10, "away_team": "Wombats", "away_code": "ST", "home_team": "Wildcards", "home_code": "ME" },
{ "game": 10, "away_team": "Bankees", "away_code": "SW", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 10, "away_team": "Mets", "away_code": "AD", "home_team": "Lumberlobos", "home_code": "P9" },
{ "game": 10, "away_team": "Frogs", "away_code": "WC", "home_team": "Warmups", "home_code": "CH" },
{ "game": 10, "away_team": "Bombers", "away_code": "SR", "home_team": "Smores", "home_code": "GG" },
{ "game": 10, "away_team": "Storm", "away_code": "JB", "home_team": "Fireballs", "home_code": "BR" },
{ "game": 10, "away_team": "Mothmen", "away_code": "SB", "home_team": "Feraligatr", "home_code": "B3" },
{ "game": 10, "away_team": "Tornados", "away_code": "DK", "home_team": "Goblins", "home_code": "GE" },
{ "game": 10, "away_team": "Crows", "away_code": "KJ", "home_team": "Bananas", "home_code": "FN" },
{ "game": 10, "away_team": "Monopolies", "away_code": "W1", "home_team": "Figures", "home_code": "RR" },
{ "game": 11, "away_team": "Penguins", "away_code": "JS", "home_team": "Lumberlobos", "home_code": "P9" },
{ "game": 11, "away_team": "Waffles", "away_code": "FJ", "home_team": "Skeeters", "home_code": "MC" },
{ "game": 11, "away_team": "Phillies", "away_code": "MK", "home_team": "Wildcards", "home_code": "ME" },
{ "game": 11, "away_team": "Policemen", "away_code": "MU", "home_team": "Monarchs", "home_code": "OB" },
{ "game": 11, "away_team": "Red Sox", "away_code": "NP", "home_team": "Wombats", "home_code": "ST" },
{ "game": 11, "away_team": "Lightning", "away_code": "SE", "home_team": "Bankees", "home_code": "SW" },
{ "game": 11, "away_team": "-200 Boys", "away_code": "CM", "home_team": "Mets", "home_code": "AD" },
{ "game": 11, "away_team": "Warmups", "away_code": "CH", "home_team": "Figures", "home_code": "RR" },
{ "game": 11, "away_team": "Mothmen", "away_code": "SB", "home_team": "Bananas", "home_code": "FN" },
{ "game": 11, "away_team": "Frogs", "away_code": "WC", "home_team": "Goblins", "home_code": "GE" },
{ "game": 11, "away_team": "Bombers", "away_code": "SR", "home_team": "Feraligatr", "home_code": "B3" },
{ "game": 11, "away_team": "Storm", "away_code": "JB", "home_team": "Tornados", "home_code": "DK" },
{ "game": 11, "away_team": "Fireballs", "away_code": "BR", "home_team": "Crows", "home_code": "KJ" },
{ "game": 11, "away_team": "Smores", "away_code": "GG", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 12, "away_team": "Lightning", "away_code": "SE", "home_team": "Policemen", "home_code": "MU" },
{ "game": 12, "away_team": "-200 Boys", "away_code": "CM", "home_team": "Phillies", "home_code": "MK" },
{ "game": 12, "away_team": "Penguins", "away_code": "JS", "home_team": "Waffles", "home_code": "FJ" },
{ "game": 12, "away_team": "Red Sox", "away_code": "NP", "home_team": "Mets", "home_code": "AD" },
{ "game": 12, "away_team": "Lumberlobos", "away_code": "P9", "home_team": "Bankees", "home_code": "SW" },
{ "game": 12, "away_team": "Skeeters", "away_code": "MC", "home_team": "Wombats", "home_code": "ST" },
{ "game": 12, "away_team": "Wildcards", "away_code": "ME", "home_team": "Monarchs", "home_code": "OB" },
{ "game": 12, "away_team": "Fireballs", "away_code": "BR", "home_team": "Bombers", "home_code": "SR" },
{ "game": 12, "away_team": "Smores", "away_code": "GG", "home_team": "Frogs", "home_code": "WC" },
{ "game": 12, "away_team": "Warmups", "away_code": "CH", "home_team": "Mothmen", "home_code": "SB" },
{ "game": 12, "away_team": "Storm", "away_code": "JB", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 12, "away_team": "Figures", "away_code": "RR", "home_team": "Crows", "home_code": "KJ" },
{ "game": 12, "away_team": "Bananas", "away_code": "FN", "home_team": "Tornados", "home_code": "DK" },
{ "game": 12, "away_team": "Goblins", "away_code": "GE", "home_team": "Feraligatr", "home_code": "B3" },
{ "game": 13, "away_team": "Skeeters", "away_code": "MC", "home_team": "Penguins", "home_code": "JS" },
{ "game": 13, "away_team": "Wildcards", "away_code": "ME", "home_team": "Waffles", "home_code": "FJ" },
{ "game": 13, "away_team": "Monarchs", "away_code": "OB", "home_team": "Phillies", "home_code": "MK" },
{ "game": 13, "away_team": "Wombats", "away_code": "ST", "home_team": "Policemen", "home_code": "MU" },
{ "game": 13, "away_team": "Bankees", "away_code": "SW", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 13, "away_team": "Mets", "away_code": "AD", "home_team": "Lightning", "home_code": "SE" },
{ "game": 13, "away_team": "Lumberlobos", "away_code": "P9", "home_team": "-200 Boys", "home_code": "CM" },
{ "game": 13, "away_team": "Bananas", "away_code": "FN", "home_team": "Warmups", "home_code": "CH" },
{ "game": 13, "away_team": "Goblins", "away_code": "GE", "home_team": "Mothmen", "home_code": "SB" },
{ "game": 13, "away_team": "Feraligatr", "away_code": "B3", "home_team": "Frogs", "home_code": "WC" },
{ "game": 13, "away_team": "Tornados", "away_code": "DK", "home_team": "Bombers", "home_code": "SR" },
{ "game": 13, "away_team": "Crows", "away_code": "KJ", "home_team": "Storm", "home_code": "JB" },
{ "game": 13, "away_team": "Monopolies", "away_code": "W1", "home_team": "Fireballs", "home_code": "BR" },
{ "game": 13, "away_team": "Figures", "away_code": "RR", "home_team": "Smores", "home_code": "GG" },
{ "game": 14, "away_team": "-200 Boys", "away_code": "CM", "home_team": "Red Sox", "home_code": "NP" },
{ "game": 14, "away_team": "Penguins", "away_code": "JS", "home_team": "Policemen", "home_code": "MU" },
{ "game": 14, "away_team": "Waffles", "away_code": "FJ", "home_team": "Phillies", "home_code": "MK" },
{ "game": 14, "away_team": "Lightning", "away_code": "SE", "home_team": "Lumberlobos", "home_code": "P9" },
{ "game": 14, "away_team": "Skeeters", "away_code": "MC", "home_team": "Mets", "home_code": "AD" },
{ "game": 14, "away_team": "Wildcards", "away_code": "ME", "home_team": "Bankees", "home_code": "SW" },
{ "game": 14, "away_team": "Monarchs", "away_code": "OB", "home_team": "Wombats", "home_code": "ST" },
{ "game": 14, "away_team": "Smores", "away_code": "GG", "home_team": "Storm", "home_code": "JB" },
{ "game": 14, "away_team": "Bombers", "away_code": "SR", "home_team": "Warmups", "home_code": "CH" },
{ "game": 14, "away_team": "Mothmen", "away_code": "SB", "home_team": "Frogs", "home_code": "WC" },
{ "game": 14, "away_team": "Fireballs", "away_code": "BR", "home_team": "Figures", "home_code": "RR" },
{ "game": 14, "away_team": "Bananas", "away_code": "FN", "home_team": "Monopolies", "home_code": "W1" },
{ "game": 14, "away_team": "Goblins", "away_code": "GE", "home_team": "Crows", "home_code": "KJ" },
{ "game": 14, "away_team": "Feraligatr", "away_code": "B3", "home_team": "Tornados", "home_code": "DK" }
]
module.exports = {s1502teams, s1502schedule};