const s1501teams = {
"Snow Cones": "<@&1071145998656737360>",
"Borioles": "<@&603589502891458574>",
"Wines": "<@&496530637596000287>",
"Reds": "<@&995878927753019412>",
"Moose": "<@&1224476744770261022>",
"Bullpups": "<@&670773176984403982>",
"Crew": "<@&603768704295108628>",
"Royals": "<@&1224260726642835456>",
"Retrievers": "<@&1290493575926251602>",
"Dice": "<@&1306532649573285888>",
"Blasters": "<@&448576748767150091>",
"Cat Ray DJs": "<@&1306541292020305940>",
"Koalas": "<@&1224799651677605969>",
"Beavers": "<@&1306541618941267998>",
"Teens": "<@&1361223974649860126>",
"Cheesers": "<@&1224263062996123678>",
"Bantams": "<@&702678421423128637>",
"Matts": "<@&1490785439710314726>",
"Giants": "<@&1306528207994093639>",
"Monsters": "<@&496817066201055232>",
"Goobers": "<@&703669468768895206>",
"Fishes": "<@&603589333676589066>",
"Gnomes": "<@&1224267311993716770>",
"Stranglers": "<@&496713526778265624>",
"Marlins": "<@&496815324553936898>",
"Kids": "<@&603591280471048213>",
"Rays": "<@&496788937705259009>",
"Memes": "<@&1067545232243183737>",
};

const s1501schedule =[

{ "game": 1, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Borioles", "home_code": "NV" },
{ "game": 1, "away_team": "Giants", "away_code": "R6", "home_team": "Retrievers", "home_code": "VS" },
{ "game": 1, "away_team": "Reds", "away_code": "PZ", "home_team": "Moose", "home_code": "PS" },
{ "game": 1, "away_team": "Matts", "away_code": "M@", "home_team": "Beavers", "home_code": "IT" },
{ "game": 1, "away_team": "Bantams", "away_code": "PB", "home_team": "Crew", "home_code": "HZ" },
{ "game": 1, "away_team": "Gnomes", "away_code": "GY", "home_team": "Teens", "home_code": "DA" },
{ "game": 1, "away_team": "Fishes", "away_code": "CW", "home_team": "Blasters", "home_code": "C8" },
{ "game": 1, "away_team": "Koalas", "away_code": "BO", "home_team": "Wines", "home_code": "HC" },
{ "game": 1, "away_team": "Cheesers", "away_code": "95", "home_team": "Royals", "home_code": "CK" },
{ "game": 1, "away_team": "Monsters", "away_code": "YY", "home_team": "Stranglers", "home_code": "AT" },
{ "game": 1, "away_team": "Goobers", "away_code": "GB", "home_team": "Rays", "home_code": "AP" },
{ "game": 1, "away_team": "Cat Ray DJs", "away_code": "N8", "home_team": "Dice", "home_code": "WS" },
{ "game": 1, "away_team": "Marlins", "away_code": "LO", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 1, "away_team": "Memes", "away_code": "MM", "home_team": "Kids", "home_code": "LW" },
{ "game": 2, "away_team": "Gnomes", "away_code": "GY", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 2, "away_team": "Fishes", "away_code": "CW", "home_team": "Giants", "home_code": "R6" },
{ "game": 2, "away_team": "Blasters", "away_code": "C8", "home_team": "Reds", "home_code": "PZ" },
{ "game": 2, "away_team": "Teens", "away_code": "DA", "home_team": "Moose", "home_code": "PS" },
{ "game": 2, "away_team": "Crew", "away_code": "HZ", "home_team": "Retrievers", "home_code": "VS" },
{ "game": 2, "away_team": "Beavers", "away_code": "IT", "home_team": "Borioles", "home_code": "NV" },
{ "game": 2, "away_team": "Bantams", "away_code": "PB", "home_team": "Matts", "home_code": "M@" },
{ "game": 2, "away_team": "Marlins", "away_code": "LO", "home_team": "Koalas", "home_code": "BO" },
{ "game": 2, "away_team": "Memes", "away_code": "MM", "home_team": "Cheesers", "home_code": "95" },
{ "game": 2, "away_team": "Kids", "away_code": "LW", "home_team": "Monsters", "home_code": "YY" },
{ "game": 2, "away_team": "Bullpups", "away_code": "HM", "home_team": "Stranglers", "home_code": "AT" },
{ "game": 2, "away_team": "Dice", "away_code": "WS", "home_team": "Royals", "home_code": "CK" },
{ "game": 2, "away_team": "Rays", "away_code": "AP", "home_team": "Wines", "home_code": "HC" },
{ "game": 2, "away_team": "Cat Ray DJs", "away_code": "N8", "home_team": "Goobers", "home_code": "GB" },
{ "game": 3, "away_team": "Moose", "away_code": "PS", "home_team": "Giants", "home_code": "R6" },
{ "game": 3, "away_team": "Retrievers", "away_code": "VS", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 3, "away_team": "Borioles", "away_code": "NV", "home_team": "Matts", "home_code": "M@" },
{ "game": 3, "away_team": "Reds", "away_code": "PZ", "home_team": "Fishes", "home_code": "CW" },
{ "game": 3, "away_team": "Blasters", "away_code": "C8", "home_team": "Gnomes", "home_code": "GY" },
{ "game": 3, "away_team": "Teens", "away_code": "DA", "home_team": "Bantams", "home_code": "PB" },
{ "game": 3, "away_team": "Crew", "away_code": "HZ", "home_team": "Beavers", "home_code": "IT" },
{ "game": 3, "away_team": "Stranglers", "away_code": "AT", "home_team": "Cheesers", "home_code": "95" },
{ "game": 3, "away_team": "Royals", "away_code": "CK", "home_team": "Koalas", "home_code": "BO" },
{ "game": 3, "away_team": "Wines", "away_code": "HC", "home_team": "Goobers", "home_code": "GB" },
{ "game": 3, "away_team": "Monsters", "away_code": "YY", "home_team": "Memes", "home_code": "MM" },
{ "game": 3, "away_team": "Kids", "away_code": "LW", "home_team": "Marlins", "home_code": "LO" },
{ "game": 3, "away_team": "Bullpups", "away_code": "HM", "home_team": "Cat Ray DJs", "home_code": "N8" },
{ "game": 3, "away_team": "Dice", "away_code": "WS", "home_team": "Rays", "home_code": "AP" },
{ "game": 4, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Fishes", "home_code": "CW" },
{ "game": 4, "away_team": "Giants", "away_code": "R6", "home_team": "Blasters", "home_code": "C8" },
{ "game": 4, "away_team": "Teens", "away_code": "DA", "home_team": "Reds", "home_code": "PZ" },
{ "game": 4, "away_team": "Moose", "away_code": "PS", "home_team": "Crew", "home_code": "HZ" },
{ "game": 4, "away_team": "Retrievers", "away_code": "VS", "home_team": "Beavers", "home_code": "IT" },
{ "game": 4, "away_team": "Borioles", "away_code": "NV", "home_team": "Bantams", "home_code": "PB" },
{ "game": 4, "away_team": "Matts", "away_code": "M@", "home_team": "Gnomes", "home_code": "GY" },
{ "game": 4, "away_team": "Koalas", "away_code": "BO", "home_team": "Memes", "home_code": "MM" },
{ "game": 4, "away_team": "Cheesers", "away_code": "95", "home_team": "Kids", "home_code": "LW" },
{ "game": 4, "away_team": "Monsters", "away_code": "YY", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 4, "away_team": "Stranglers", "away_code": "AT", "home_team": "Dice", "home_code": "WS" },
{ "game": 4, "away_team": "Royals", "away_code": "CK", "home_team": "Rays", "home_code": "AP" },
{ "game": 4, "away_team": "Wines", "away_code": "HC", "home_team": "Cat Ray DJs", "home_code": "N8" },
{ "game": 4, "away_team": "Goobers", "away_code": "GB", "home_team": "Marlins", "home_code": "LO" },
{ "game": 5, "away_team": "Giants", "away_code": "R6", "home_team": "Matts", "home_code": "M@" },
{ "game": 5, "away_team": "Reds", "away_code": "PZ", "home_team": "Borioles", "home_code": "NV" },
{ "game": 5, "away_team": "Moose", "away_code": "PS", "home_team": "Retrievers", "home_code": "VS" },
{ "game": 5, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Bantams", "home_code": "PB" },
{ "game": 5, "away_team": "Gnomes", "away_code": "GY", "home_team": "Beavers", "home_code": "IT" },
{ "game": 5, "away_team": "Fishes", "away_code": "CW", "home_team": "Crew", "home_code": "HZ" },
{ "game": 5, "away_team": "Blasters", "away_code": "C8", "home_team": "Teens", "home_code": "DA" },
{ "game": 5, "away_team": "Cheesers", "away_code": "95", "home_team": "Goobers", "home_code": "GB" },
{ "game": 5, "away_team": "Monsters", "away_code": "YY", "home_team": "Wines", "home_code": "HC" },
{ "game": 5, "away_team": "Stranglers", "away_code": "AT", "home_team": "Royals", "home_code": "CK" },
{ "game": 5, "away_team": "Koalas", "away_code": "BO", "home_team": "Cat Ray DJs", "home_code": "N8" },
{ "game": 5, "away_team": "Marlins", "away_code": "LO", "home_team": "Rays", "home_code": "AP" },
{ "game": 5, "away_team": "Memes", "away_code": "MM", "home_team": "Dice", "home_code": "WS" },
{ "game": 5, "away_team": "Kids", "away_code": "LW", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 7, "away_team": "Blasters", "away_code": "C8", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 7, "away_team": "Giants", "away_code": "R6", "home_team": "Teens", "home_code": "DA" },
{ "game": 7, "away_team": "Reds", "away_code": "PZ", "home_team": "Crew", "home_code": "HZ" },
{ "game": 7, "away_team": "Moose", "away_code": "PS", "home_team": "Beavers", "home_code": "IT" },
{ "game": 7, "away_team": "Retrievers", "away_code": "VS", "home_team": "Bantams", "home_code": "PB" },
{ "game": 7, "away_team": "Borioles", "away_code": "NV", "home_team": "Gnomes", "home_code": "GY" },
{ "game": 7, "away_team": "Matts", "away_code": "M@", "home_team": "Fishes", "home_code": "CW" },
{ "game": 7, "away_team": "Koalas", "away_code": "BO", "home_team": "Kids", "home_code": "LW" },
{ "game": 7, "away_team": "Cheesers", "away_code": "95", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 7, "away_team": "Monsters", "away_code": "YY", "home_team": "Dice", "home_code": "WS" },
{ "game": 7, "away_team": "Stranglers", "away_code": "AT", "home_team": "Rays", "home_code": "AP" },
{ "game": 7, "away_team": "Royals", "away_code": "CK", "home_team": "Cat Ray DJs", "home_code": "N8" },
{ "game": 7, "away_team": "Wines", "away_code": "HC", "home_team": "Marlins", "home_code": "LO" },
{ "game": 7, "away_team": "Goobers", "away_code": "GB", "home_team": "Memes", "home_code": "MM" },
{ "game": 6, "away_team": "Cat Ray DJs", "away_code": "N8", "home_team": "Blasters", "home_code": "C8" },
{ "game": 6, "away_team": "Marlins", "away_code": "LO", "home_team": "Giants", "home_code": "R6" },
{ "game": 6, "away_team": "Memes", "away_code": "MM", "home_team": "Teens", "home_code": "DA" },
{ "game": 6, "away_team": "Kids", "away_code": "LW", "home_team": "Moose", "home_code": "PS" },
{ "game": 6, "away_team": "Bullpups", "away_code": "HM", "home_team": "Retrievers", "home_code": "VS" },
{ "game": 6, "away_team": "Dice", "away_code": "WS", "home_team": "Borioles", "home_code": "NV" },
{ "game": 6, "away_team": "Rays", "away_code": "AP", "home_team": "Matts", "home_code": "M@" },
{ "game": 6, "away_team": "Bantams", "away_code": "PB", "home_team": "Koalas", "home_code": "BO" },
{ "game": 6, "away_team": "Gnomes", "away_code": "GY", "home_team": "Cheesers", "home_code": "95" },
{ "game": 6, "away_team": "Fishes", "away_code": "CW", "home_team": "Monsters", "home_code": "YY" },
{ "game": 6, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Stranglers", "home_code": "AT" },
{ "game": 6, "away_team": "Reds", "away_code": "PZ", "home_team": "Royals", "home_code": "CK" },
{ "game": 6, "away_team": "Crew", "away_code": "HZ", "home_team": "Wines", "home_code": "HC" },
{ "game": 6, "away_team": "Beavers", "away_code": "IT", "home_team": "Goobers", "home_code": "GB" },
{ "game": 8, "away_team": "Retrievers", "away_code": "VS", "home_team": "Reds", "home_code": "PZ" },
{ "game": 8, "away_team": "Borioles", "away_code": "NV", "home_team": "Giants", "home_code": "R6" },
{ "game": 8, "away_team": "Matts", "away_code": "M@", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 8, "away_team": "Moose", "away_code": "PS", "home_team": "Blasters", "home_code": "C8" },
{ "game": 8, "away_team": "Teens", "away_code": "DA", "home_team": "Fishes", "home_code": "CW" },
{ "game": 8, "away_team": "Crew", "away_code": "HZ", "home_team": "Gnomes", "home_code": "GY" },
{ "game": 8, "away_team": "Beavers", "away_code": "IT", "home_team": "Bantams", "home_code": "PB" },
{ "game": 8, "away_team": "Royals", "away_code": "CK", "home_team": "Monsters", "home_code": "YY" },
{ "game": 8, "away_team": "Wines", "away_code": "HC", "home_team": "Cheesers", "home_code": "95" },
{ "game": 8, "away_team": "Goobers", "away_code": "GB", "home_team": "Koalas", "home_code": "BO" },
{ "game": 8, "away_team": "Stranglers", "away_code": "AT", "home_team": "Kids", "home_code": "LW" },
{ "game": 8, "away_team": "Bullpups", "away_code": "HM", "home_team": "Memes", "home_code": "MM" },
{ "game": 8, "away_team": "Dice", "away_code": "WS", "home_team": "Marlins", "home_code": "LO" },
{ "game": 8, "away_team": "Rays", "away_code": "AP", "home_team": "Cat Ray DJs", "home_code": "N8" },
{ "game": 9, "away_team": "Teens", "away_code": "DA", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 9, "away_team": "Crew", "away_code": "HZ", "home_team": "Giants", "home_code": "R6" },
{ "game": 9, "away_team": "Beavers", "away_code": "IT", "home_team": "Reds", "home_code": "PZ" },
{ "game": 9, "away_team": "Bantams", "away_code": "PB", "home_team": "Moose", "home_code": "PS" },
{ "game": 9, "away_team": "Gnomes", "away_code": "GY", "home_team": "Retrievers", "home_code": "VS" },
{ "game": 9, "away_team": "Fishes", "away_code": "CW", "home_team": "Borioles", "home_code": "NV" },
{ "game": 9, "away_team": "Blasters", "away_code": "C8", "home_team": "Matts", "home_code": "M@" },
{ "game": 9, "away_team": "Bullpups", "away_code": "HM", "home_team": "Koalas", "home_code": "BO" },
{ "game": 9, "away_team": "Dice", "away_code": "WS", "home_team": "Cheesers", "home_code": "95" },
{ "game": 9, "away_team": "Rays", "away_code": "AP", "home_team": "Monsters", "home_code": "YY" },
{ "game": 9, "away_team": "Cat Ray DJs", "away_code": "N8", "home_team": "Stranglers", "home_code": "AT" },
{ "game": 9, "away_team": "Marlins", "away_code": "LO", "home_team": "Royals", "home_code": "CK" },
{ "game": 9, "away_team": "Memes", "away_code": "MM", "home_team": "Wines", "home_code": "HC" },
{ "game": 9, "away_team": "Kids", "away_code": "LW", "home_team": "Goobers", "home_code": "GB" },
{ "game": 10, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Reds", "home_code": "PZ" },
{ "game": 10, "away_team": "Moose", "away_code": "PS", "home_team": "Matts", "home_code": "M@" },
{ "game": 10, "away_team": "Retrievers", "away_code": "VS", "home_team": "Borioles", "home_code": "NV" },
{ "game": 10, "away_team": "Giants", "away_code": "R6", "home_team": "Gnomes", "home_code": "GY" },
{ "game": 10, "away_team": "Fishes", "away_code": "CW", "home_team": "Bantams", "home_code": "PB" },
{ "game": 10, "away_team": "Blasters", "away_code": "C8", "home_team": "Beavers", "home_code": "IT" },
{ "game": 10, "away_team": "Teens", "away_code": "DA", "home_team": "Crew", "home_code": "HZ" },
{ "game": 10, "away_team": "Monsters", "away_code": "YY", "home_team": "Koalas", "home_code": "BO" },
{ "game": 10, "away_team": "Stranglers", "away_code": "AT", "home_team": "Goobers", "home_code": "GB" },
{ "game": 10, "away_team": "Royals", "away_code": "CK", "home_team": "Wines", "home_code": "HC" },
{ "game": 10, "away_team": "Cheesers", "away_code": "95", "home_team": "Marlins", "home_code": "LO" },
{ "game": 10, "away_team": "Memes", "away_code": "MM", "home_team": "Cat Ray DJs", "home_code": "N8" },
{ "game": 10, "away_team": "Kids", "away_code": "LW", "home_team": "Rays", "home_code": "AP" },
{ "game": 10, "away_team": "Bullpups", "away_code": "HM", "home_team": "Dice", "home_code": "WS" },
{ "game": 11, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Crew", "home_code": "HZ" },
{ "game": 11, "away_team": "Giants", "away_code": "R6", "home_team": "Beavers", "home_code": "IT" },
{ "game": 11, "away_team": "Reds", "away_code": "PZ", "home_team": "Bantams", "home_code": "PB" },
{ "game": 11, "away_team": "Moose", "away_code": "PS", "home_team": "Gnomes", "home_code": "GY" },
{ "game": 11, "away_team": "Retrievers", "away_code": "VS", "home_team": "Fishes", "home_code": "CW" },
{ "game": 11, "away_team": "Borioles", "away_code": "NV", "home_team": "Blasters", "home_code": "C8" },
{ "game": 11, "away_team": "Matts", "away_code": "M@", "home_team": "Teens", "home_code": "DA" },
{ "game": 11, "away_team": "Koalas", "away_code": "BO", "home_team": "Dice", "home_code": "WS" },
{ "game": 11, "away_team": "Cheesers", "away_code": "95", "home_team": "Rays", "home_code": "AP" },
{ "game": 11, "away_team": "Monsters", "away_code": "YY", "home_team": "Cat Ray DJs", "home_code": "N8" },
{ "game": 11, "away_team": "Stranglers", "away_code": "AT", "home_team": "Marlins", "home_code": "LO" },
{ "game": 11, "away_team": "Royals", "away_code": "CK", "home_team": "Memes", "home_code": "MM" },
{ "game": 11, "away_team": "Wines", "away_code": "HC", "home_team": "Kids", "home_code": "LW" },
{ "game": 11, "away_team": "Goobers", "away_code": "GB", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 12, "away_team": "Borioles", "away_code": "NV", "home_team": "Moose", "home_code": "PS" },
{ "game": 12, "away_team": "Matts", "away_code": "M@", "home_team": "Reds", "home_code": "PZ" },
{ "game": 12, "away_team": "Giants", "away_code": "R6", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 12, "away_team": "Retrievers", "away_code": "VS", "home_team": "Teens", "home_code": "DA" },
{ "game": 12, "away_team": "Crew", "away_code": "HZ", "home_team": "Blasters", "home_code": "C8" },
{ "game": 12, "away_team": "Beavers", "away_code": "IT", "home_team": "Fishes", "home_code": "CW" },
{ "game": 12, "away_team": "Bantams", "away_code": "PB", "home_team": "Gnomes", "home_code": "GY" },
{ "game": 12, "away_team": "Wines", "away_code": "HC", "home_team": "Stranglers", "home_code": "AT" },
{ "game": 12, "away_team": "Goobers", "away_code": "GB", "home_team": "Monsters", "home_code": "YY" },
{ "game": 12, "away_team": "Koalas", "away_code": "BO", "home_team": "Cheesers", "home_code": "95" },
{ "game": 12, "away_team": "Royals", "away_code": "CK", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 12, "away_team": "Dice", "away_code": "WS", "home_team": "Kids", "home_code": "LW" },
{ "game": 12, "away_team": "Rays", "away_code": "AP", "home_team": "Memes", "home_code": "MM" },
{ "game": 12, "away_team": "Cat Ray DJs", "away_code": "N8", "home_team": "Marlins", "home_code": "LO" },
{ "game": 13, "away_team": "Beavers", "away_code": "IT", "home_team": "Snow Cones", "home_code": "TC" },
{ "game": 13, "away_team": "Bantams", "away_code": "PB", "home_team": "Giants", "home_code": "R6" },
{ "game": 13, "away_team": "Gnomes", "away_code": "GY", "home_team": "Reds", "home_code": "PZ" },
{ "game": 13, "away_team": "Fishes", "away_code": "CW", "home_team": "Moose", "home_code": "PS" },
{ "game": 13, "away_team": "Blasters", "away_code": "C8", "home_team": "Retrievers", "home_code": "VS" },
{ "game": 13, "away_team": "Teens", "away_code": "DA", "home_team": "Borioles", "home_code": "NV" },
{ "game": 13, "away_team": "Crew", "away_code": "HZ", "home_team": "Matts", "home_code": "M@" },
{ "game": 13, "away_team": "Rays", "away_code": "AP", "home_team": "Koalas", "home_code": "BO" },
{ "game": 13, "away_team": "Cat Ray DJs", "away_code": "N8", "home_team": "Cheesers", "home_code": "95" },
{ "game": 13, "away_team": "Marlins", "away_code": "LO", "home_team": "Monsters", "home_code": "YY" },
{ "game": 13, "away_team": "Memes", "away_code": "MM", "home_team": "Stranglers", "home_code": "AT" },
{ "game": 13, "away_team": "Kids", "away_code": "LW", "home_team": "Royals", "home_code": "CK" },
{ "game": 13, "away_team": "Bullpups", "away_code": "HM", "home_team": "Wines", "home_code": "HC" },
{ "game": 13, "away_team": "Dice", "away_code": "WS", "home_team": "Goobers", "home_code": "GB" },
{ "game": 14, "away_team": "Matts", "away_code": "M@", "home_team": "Retrievers", "home_code": "VS" },
{ "game": 14, "away_team": "Snow Cones", "away_code": "TC", "home_team": "Moose", "home_code": "PS" },
{ "game": 14, "away_team": "Reds", "away_code": "PZ", "home_team": "Giants", "home_code": "R6" },
{ "game": 14, "away_team": "Borioles", "away_code": "NV", "home_team": "Crew", "home_code": "HZ" },
{ "game": 14, "away_team": "Beavers", "away_code": "IT", "home_team": "Teens", "home_code": "DA" },
{ "game": 14, "away_team": "Bantams", "away_code": "PB", "home_team": "Blasters", "home_code": "C8" },
{ "game": 14, "away_team": "Gnomes", "away_code": "GY", "home_team": "Fishes", "home_code": "CW" },
{ "game": 14, "away_team": "Goobers", "away_code": "GB", "home_team": "Royals", "home_code": "CK" },
{ "game": 14, "away_team": "Koalas", "away_code": "BO", "home_team": "Stranglers", "home_code": "AT" },
{ "game": 14, "away_team": "Cheesers", "away_code": "95", "home_team": "Monsters", "home_code": "YY" },
{ "game": 14, "away_team": "Wines", "away_code": "HC", "home_team": "Dice", "home_code": "WS" },
{ "game": 14, "away_team": "Rays", "away_code": "AP", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 14, "away_team": "Cat Ray DJs", "away_code": "N8", "home_team": "Kids", "home_code": "LW" },
{ "game": 14, "away_team": "Marlins", "away_code": "LO", "home_team": "Memes", "home_code": "MM" }
]
module.exports = { s1501teams, s1501schedule};