const s1503teams = {
"Wombats": "<@&493888943754838036>",
"Gamblers": "<@&1486618231589310595>",
"Indians": "<@&1397106280610664511>",
"Grimaces": "<@&1306540379423637565>",
"Bankees": "<@&668468071861583891>",
"Pickles": "<@&1067528806765699162>",
"I.J.L.S.A.": "<@&1306541385301889046>",
"Boys": "<@&1142985787114266624>",
"Warmers": "<@&1449501498647253105>",
"Swimmers": "<@&1224784681166438540>",
"Jays": "<@&603589804868763648>",
"Knights": "<@&847666595748249640>",
"Mets": "<@&847666608852041778>",
"Giants": "<@&1067540852769050744>",
"Lizards": "<@&1071145701725184070>",
"Angelas": "<@&1290574091069296671>",
"Buddies": "<@&603286831823585280>",
"Pigskins": "<@&1486617885676667043>",
"Melonheads": "<@&1306541154422099969>",
"Bullpups": "<@&670773176984403982>",
"Marvels": "<@&603589134744944670>",
"Mimes": "<@&1067544975325265960>",
"Poopers": "<@&1486618090509701150>",
"Bombers": "<@&603291831744200737>",
"Mathematicians": "<@&448576610489335809>",
"Intimidators": "<@&1067528046451642418>",
"Astros": "<@&1486617669879857262>",
"Chucks": "<@&1306540511766642718>",
};

const s1503schedule =[

{ "game": 1, "away_team": "Warmers", "away_code": "VS", "home_team": "Pickles", "home_code": "MS" },
{ "game": 1, "away_team": "Pigskins", "away_code": "R6", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 1, "away_team": "I.J.L.S.A.", "away_code": "AP", "home_team": "Mimes", "home_code": "JB" },
{ "game": 1, "away_team": "Mets", "away_code": "MK", "home_team": "Indians", "home_code": "JJ" },
{ "game": 1, "away_team": "Giants", "away_code": "C8", "home_team": "Wombats", "home_code": "DA" },
{ "game": 1, "away_team": "Swimmers", "away_code": "W1", "home_team": "Marvels", "home_code": "M@" },
{ "game": 1, "away_team": "Gamblers", "away_code": "MM", "home_team": "Melonheads", "home_code": "IS" },
{ "game": 1, "away_team": "Poopers", "away_code": "RR", "home_team": "Knights", "home_code": "WS" },
{ "game": 1, "away_team": "Boys", "away_code": "EF", "home_team": "Bankees", "home_code": "SW" },
{ "game": 1, "away_team": "Angelas", "away_code": "PZ", "home_team": "Jays", "home_code": "FJ" },
{ "game": 1, "away_team": "Bullpups", "away_code": "HM", "home_team": "Mathematicians", "home_code": "MT" },
{ "game": 1, "away_team": "Chucks", "away_code": "BO", "home_team": "Lizards", "home_code": "SA" },
{ "game": 1, "away_team": "Intimidators", "away_code": "DK", "home_team": "Astros", "home_code": "PS" },
{ "game": 1, "away_team": "Buddies", "away_code": "TC", "home_team": "Bombers", "home_code": "CK" },
{ "game": 2, "away_team": "Swimmers", "away_code": "W1", "home_team": "Warmers", "home_code": "VS" },
{ "game": 2, "away_team": "Gamblers", "away_code": "MM", "home_team": "Pigskins", "home_code": "R6" },
{ "game": 2, "away_team": "Melonheads", "away_code": "IS", "home_team": "I.J.L.S.A.", "home_code": "AP" },
{ "game": 2, "away_team": "Marvels", "away_code": "M@", "home_team": "Mimes", "home_code": "JB" },
{ "game": 2, "away_team": "Wombats", "away_code": "DA", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 2, "away_team": "Indians", "away_code": "JJ", "home_team": "Pickles", "home_code": "MS" },
{ "game": 2, "away_team": "Giants", "away_code": "C8", "home_team": "Mets", "home_code": "MK" },
{ "game": 2, "away_team": "Intimidators", "away_code": "DK", "home_team": "Poopers", "home_code": "RR" },
{ "game": 2, "away_team": "Buddies", "away_code": "TC", "home_team": "Boys", "home_code": "EF" },
{ "game": 2, "away_team": "Bombers", "away_code": "CK", "home_team": "Angelas", "home_code": "PZ" },
{ "game": 2, "away_team": "Astros", "away_code": "PS", "home_team": "Jays", "home_code": "FJ" },
{ "game": 2, "away_team": "Lizards", "away_code": "SA", "home_team": "Bankees", "home_code": "SW" },
{ "game": 2, "away_team": "Mathematicians", "away_code": "MT", "home_team": "Knights", "home_code": "WS" },
{ "game": 2, "away_team": "Chucks", "away_code": "BO", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 3, "away_team": "Mimes", "away_code": "JB", "home_team": "Pigskins", "home_code": "R6" },
{ "game": 3, "away_team": "Grimaces", "away_code": "N8", "home_team": "Warmers", "home_code": "VS" },
{ "game": 3, "away_team": "Pickles", "away_code": "MS", "home_team": "Mets", "home_code": "MK" },
{ "game": 3, "away_team": "I.J.L.S.A.", "away_code": "AP", "home_team": "Gamblers", "home_code": "MM" },
{ "game": 3, "away_team": "Melonheads", "away_code": "IS", "home_team": "Swimmers", "home_code": "W1" },
{ "game": 3, "away_team": "Marvels", "away_code": "M@", "home_team": "Giants", "home_code": "C8" },
{ "game": 3, "away_team": "Wombats", "away_code": "DA", "home_team": "Indians", "home_code": "JJ" },
{ "game": 3, "away_team": "Jays", "away_code": "FJ", "home_team": "Boys", "home_code": "EF" },
{ "game": 3, "away_team": "Bankees", "away_code": "SW", "home_team": "Poopers", "home_code": "RR" },
{ "game": 3, "away_team": "Knights", "away_code": "WS", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 3, "away_team": "Angelas", "away_code": "PZ", "home_team": "Buddies", "home_code": "TC" },
{ "game": 3, "away_team": "Bombers", "away_code": "CK", "home_team": "Intimidators", "home_code": "DK" },
{ "game": 3, "away_team": "Astros", "away_code": "PS", "home_team": "Chucks", "home_code": "BO" },
{ "game": 3, "away_team": "Lizards", "away_code": "SA", "home_team": "Mathematicians", "home_code": "MT" },
{ "game": 4, "away_team": "Warmers", "away_code": "VS", "home_team": "Gamblers", "home_code": "MM" },
{ "game": 4, "away_team": "Pigskins", "away_code": "R6", "home_team": "Melonheads", "home_code": "IS" },
{ "game": 4, "away_team": "I.J.L.S.A.", "away_code": "AP", "home_team": "Marvels", "home_code": "M@" },
{ "game": 4, "away_team": "Mimes", "away_code": "JB", "home_team": "Wombats", "home_code": "DA" },
{ "game": 4, "away_team": "Grimaces", "away_code": "N8", "home_team": "Indians", "home_code": "JJ" },
{ "game": 4, "away_team": "Pickles", "away_code": "MS", "home_team": "Giants", "home_code": "C8" },
{ "game": 4, "away_team": "Mets", "away_code": "MK", "home_team": "Swimmers", "home_code": "W1" },
{ "game": 4, "away_team": "Poopers", "away_code": "RR", "home_team": "Buddies", "home_code": "TC" },
{ "game": 4, "away_team": "Boys", "away_code": "EF", "home_team": "Bombers", "home_code": "CK" },
{ "game": 4, "away_team": "Angelas", "away_code": "PZ", "home_team": "Astros", "home_code": "PS" },
{ "game": 4, "away_team": "Jays", "away_code": "FJ", "home_team": "Lizards", "home_code": "SA" },
{ "game": 4, "away_team": "Bankees", "away_code": "SW", "home_team": "Mathematicians", "home_code": "MT" },
{ "game": 4, "away_team": "Knights", "away_code": "WS", "home_team": "Chucks", "home_code": "BO" },
{ "game": 4, "away_team": "Bullpups", "away_code": "HM", "home_team": "Intimidators", "home_code": "DK" },
{ "game": 5, "away_team": "Pigskins", "away_code": "R6", "home_team": "Mets", "home_code": "MK" },
{ "game": 5, "away_team": "I.J.L.S.A.", "away_code": "AP", "home_team": "Pickles", "home_code": "MS" },
{ "game": 5, "away_team": "Mimes", "away_code": "JB", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 5, "away_team": "Warmers", "away_code": "VS", "home_team": "Giants", "home_code": "C8" },
{ "game": 5, "away_team": "Swimmers", "away_code": "W1", "home_team": "Indians", "home_code": "JJ" },
{ "game": 5, "away_team": "Gamblers", "away_code": "MM", "home_team": "Wombats", "home_code": "DA" },
{ "game": 5, "away_team": "Melonheads", "away_code": "IS", "home_team": "Marvels", "home_code": "M@" },
{ "game": 5, "away_team": "Boys", "away_code": "EF", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 5, "away_team": "Angelas", "away_code": "PZ", "home_team": "Knights", "home_code": "WS" },
{ "game": 5, "away_team": "Jays", "away_code": "FJ", "home_team": "Bankees", "home_code": "SW" },
{ "game": 5, "away_team": "Poopers", "away_code": "RR", "home_team": "Chucks", "home_code": "BO" },
{ "game": 5, "away_team": "Intimidators", "away_code": "DK", "home_team": "Mathematicians", "home_code": "MT" },
{ "game": 5, "away_team": "Buddies", "away_code": "TC", "home_team": "Lizards", "home_code": "SA" },
{ "game": 5, "away_team": "Bombers", "away_code": "CK", "home_team": "Astros", "home_code": "PS" },
{ "game": 7, "away_team": "Warmers", "away_code": "VS", "home_team": "Melonheads", "home_code": "IS" },
{ "game": 7, "away_team": "Pigskins", "away_code": "R6", "home_team": "Marvels", "home_code": "M@" },
{ "game": 7, "away_team": "I.J.L.S.A.", "away_code": "AP", "home_team": "Wombats", "home_code": "DA" },
{ "game": 7, "away_team": "Mimes", "away_code": "JB", "home_team": "Indians", "home_code": "JJ" },
{ "game": 7, "away_team": "Grimaces", "away_code": "N8", "home_team": "Giants", "home_code": "C8" },
{ "game": 7, "away_team": "Pickles", "away_code": "MS", "home_team": "Swimmers", "home_code": "W1" },
{ "game": 7, "away_team": "Mets", "away_code": "MK", "home_team": "Gamblers", "home_code": "MM" },
{ "game": 7, "away_team": "Poopers", "away_code": "RR", "home_team": "Bombers", "home_code": "CK" },
{ "game": 7, "away_team": "Boys", "away_code": "EF", "home_team": "Astros", "home_code": "PS" },
{ "game": 7, "away_team": "Angelas", "away_code": "PZ", "home_team": "Lizards", "home_code": "SA" },
{ "game": 7, "away_team": "Jays", "away_code": "FJ", "home_team": "Mathematicians", "home_code": "MT" },
{ "game": 7, "away_team": "Bankees", "away_code": "SW", "home_team": "Chucks", "home_code": "BO" },
{ "game": 7, "away_team": "Knights", "away_code": "WS", "home_team": "Intimidators", "home_code": "DK" },
{ "game": 7, "away_team": "Bullpups", "away_code": "HM", "home_team": "Buddies", "home_code": "TC" },
{ "game": 6, "away_team": "Chucks", "away_code": "BO", "home_team": "Warmers", "home_code": "VS" },
{ "game": 6, "away_team": "Intimidators", "away_code": "DK", "home_team": "Pigskins", "home_code": "R6" },
{ "game": 6, "away_team": "Buddies", "away_code": "TC", "home_team": "I.J.L.S.A.", "home_code": "AP" },
{ "game": 6, "away_team": "Bombers", "away_code": "CK", "home_team": "Mimes", "home_code": "JB" },
{ "game": 6, "away_team": "Astros", "away_code": "PS", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 6, "away_team": "Lizards", "away_code": "SA", "home_team": "Pickles", "home_code": "MS" },
{ "game": 6, "away_team": "Mathematicians", "away_code": "MT", "home_team": "Mets", "home_code": "MK" },
{ "game": 6, "away_team": "Giants", "away_code": "C8", "home_team": "Poopers", "home_code": "RR" },
{ "game": 6, "away_team": "Swimmers", "away_code": "W1", "home_team": "Boys", "home_code": "EF" },
{ "game": 6, "away_team": "Gamblers", "away_code": "MM", "home_team": "Angelas", "home_code": "PZ" },
{ "game": 6, "away_team": "Melonheads", "away_code": "IS", "home_team": "Jays", "home_code": "FJ" },
{ "game": 6, "away_team": "Marvels", "away_code": "M@", "home_team": "Bankees", "home_code": "SW" },
{ "game": 6, "away_team": "Wombats", "away_code": "DA", "home_team": "Knights", "home_code": "WS" },
{ "game": 6, "away_team": "Indians", "away_code": "JJ", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 8, "away_team": "Grimaces", "away_code": "N8", "home_team": "I.J.L.S.A.", "home_code": "AP" },
{ "game": 8, "away_team": "Pickles", "away_code": "MS", "home_team": "Pigskins", "home_code": "R6" },
{ "game": 8, "away_team": "Mets", "away_code": "MK", "home_team": "Warmers", "home_code": "VS" },
{ "game": 8, "away_team": "Mimes", "away_code": "JB", "home_team": "Melonheads", "home_code": "IS" },
{ "game": 8, "away_team": "Marvels", "away_code": "M@", "home_team": "Gamblers", "home_code": "MM" },
{ "game": 8, "away_team": "Wombats", "away_code": "DA", "home_team": "Swimmers", "home_code": "W1" },
{ "game": 8, "away_team": "Indians", "away_code": "JJ", "home_team": "Giants", "home_code": "C8" },
{ "game": 8, "away_team": "Bankees", "away_code": "SW", "home_team": "Angelas", "home_code": "PZ" },
{ "game": 8, "away_team": "Knights", "away_code": "WS", "home_team": "Boys", "home_code": "EF" },
{ "game": 8, "away_team": "Bullpups", "away_code": "HM", "home_team": "Poopers", "home_code": "RR" },
{ "game": 8, "away_team": "Jays", "away_code": "FJ", "home_team": "Bombers", "home_code": "CK" },
{ "game": 8, "away_team": "Astros", "away_code": "PS", "home_team": "Buddies", "home_code": "TC" },
{ "game": 8, "away_team": "Lizards", "away_code": "SA", "home_team": "Intimidators", "home_code": "DK" },
{ "game": 8, "away_team": "Mathematicians", "away_code": "MT", "home_team": "Chucks", "home_code": "BO" },
{ "game": 9, "away_team": "Marvels", "away_code": "M@", "home_team": "Warmers", "home_code": "VS" },
{ "game": 9, "away_team": "Wombats", "away_code": "DA", "home_team": "Pigskins", "home_code": "R6" },
{ "game": 9, "away_team": "Indians", "away_code": "JJ", "home_team": "I.J.L.S.A.", "home_code": "AP" },
{ "game": 9, "away_team": "Giants", "away_code": "C8", "home_team": "Mimes", "home_code": "JB" },
{ "game": 9, "away_team": "Swimmers", "away_code": "W1", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 9, "away_team": "Gamblers", "away_code": "MM", "home_team": "Pickles", "home_code": "MS" },
{ "game": 9, "away_team": "Melonheads", "away_code": "IS", "home_team": "Mets", "home_code": "MK" },
{ "game": 9, "away_team": "Astros", "away_code": "PS", "home_team": "Poopers", "home_code": "RR" },
{ "game": 9, "away_team": "Lizards", "away_code": "SA", "home_team": "Boys", "home_code": "EF" },
{ "game": 9, "away_team": "Mathematicians", "away_code": "MT", "home_team": "Angelas", "home_code": "PZ" },
{ "game": 9, "away_team": "Chucks", "away_code": "BO", "home_team": "Jays", "home_code": "FJ" },
{ "game": 9, "away_team": "Intimidators", "away_code": "DK", "home_team": "Bankees", "home_code": "SW" },
{ "game": 9, "away_team": "Buddies", "away_code": "TC", "home_team": "Knights", "home_code": "WS" },
{ "game": 9, "away_team": "Bombers", "away_code": "CK", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 10, "away_team": "I.J.L.S.A.", "away_code": "AP", "home_team": "Warmers", "home_code": "VS" },
{ "game": 10, "away_team": "Mimes", "away_code": "JB", "home_team": "Mets", "home_code": "MK" },
{ "game": 10, "away_team": "Grimaces", "away_code": "N8", "home_team": "Pickles", "home_code": "MS" },
{ "game": 10, "away_team": "Pigskins", "away_code": "R6", "home_team": "Swimmers", "home_code": "W1" },
{ "game": 10, "away_team": "Gamblers", "away_code": "MM", "home_team": "Giants", "home_code": "C8" },
{ "game": 10, "away_team": "Melonheads", "away_code": "IS", "home_team": "Indians", "home_code": "JJ" },
{ "game": 10, "away_team": "Marvels", "away_code": "M@", "home_team": "Wombats", "home_code": "DA" },
{ "game": 10, "away_team": "Angelas", "away_code": "PZ", "home_team": "Poopers", "home_code": "RR" },
{ "game": 10, "away_team": "Jays", "away_code": "FJ", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 10, "away_team": "Bankees", "away_code": "SW", "home_team": "Knights", "home_code": "WS" },
{ "game": 10, "away_team": "Boys", "away_code": "EF", "home_team": "Intimidators", "home_code": "DK" },
{ "game": 10, "away_team": "Buddies", "away_code": "TC", "home_team": "Chucks", "home_code": "BO" },
{ "game": 10, "away_team": "Bombers", "away_code": "CK", "home_team": "Mathematicians", "home_code": "MT" },
{ "game": 10, "away_team": "Astros", "away_code": "PS", "home_team": "Lizards", "home_code": "SA" },
{ "game": 11, "away_team": "Warmers", "away_code": "VS", "home_team": "Wombats", "home_code": "DA" },
{ "game": 11, "away_team": "Pigskins", "away_code": "R6", "home_team": "Indians", "home_code": "JJ" },
{ "game": 11, "away_team": "I.J.L.S.A.", "away_code": "AP", "home_team": "Giants", "home_code": "C8" },
{ "game": 11, "away_team": "Mimes", "away_code": "JB", "home_team": "Swimmers", "home_code": "W1" },
{ "game": 11, "away_team": "Grimaces", "away_code": "N8", "home_team": "Gamblers", "home_code": "MM" },
{ "game": 11, "away_team": "Pickles", "away_code": "MS", "home_team": "Melonheads", "home_code": "IS" },
{ "game": 11, "away_team": "Mets", "away_code": "MK", "home_team": "Marvels", "home_code": "M@" },
{ "game": 11, "away_team": "Poopers", "away_code": "RR", "home_team": "Lizards", "home_code": "SA" },
{ "game": 11, "away_team": "Boys", "away_code": "EF", "home_team": "Mathematicians", "home_code": "MT" },
{ "game": 11, "away_team": "Angelas", "away_code": "PZ", "home_team": "Chucks", "home_code": "BO" },
{ "game": 11, "away_team": "Jays", "away_code": "FJ", "home_team": "Intimidators", "home_code": "DK" },
{ "game": 11, "away_team": "Bankees", "away_code": "SW", "home_team": "Buddies", "home_code": "TC" },
{ "game": 11, "away_team": "Knights", "away_code": "WS", "home_team": "Bombers", "home_code": "CK" },
{ "game": 11, "away_team": "Bullpups", "away_code": "HM", "home_team": "Astros", "home_code": "PS" },
{ "game": 12, "away_team": "Pickles", "away_code": "MS", "home_team": "Mimes", "home_code": "JB" },
{ "game": 12, "away_team": "Mets", "away_code": "MK", "home_team": "I.J.L.S.A.", "home_code": "AP" },
{ "game": 12, "away_team": "Warmers", "away_code": "VS", "home_team": "Pigskins", "home_code": "R6" },
{ "game": 12, "away_team": "Grimaces", "away_code": "N8", "home_team": "Marvels", "home_code": "M@" },
{ "game": 12, "away_team": "Wombats", "away_code": "DA", "home_team": "Melonheads", "home_code": "IS" },
{ "game": 12, "away_team": "Indians", "away_code": "JJ", "home_team": "Gamblers", "home_code": "MM" },
{ "game": 12, "away_team": "Giants", "away_code": "C8", "home_team": "Swimmers", "home_code": "W1" },
{ "game": 12, "away_team": "Knights", "away_code": "WS", "home_team": "Jays", "home_code": "FJ" },
{ "game": 12, "away_team": "Bullpups", "away_code": "HM", "home_team": "Angelas", "home_code": "PZ" },
{ "game": 12, "away_team": "Poopers", "away_code": "RR", "home_team": "Boys", "home_code": "EF" },
{ "game": 12, "away_team": "Bankees", "away_code": "SW", "home_team": "Astros", "home_code": "PS" },
{ "game": 12, "away_team": "Lizards", "away_code": "SA", "home_team": "Bombers", "home_code": "CK" },
{ "game": 12, "away_team": "Mathematicians", "away_code": "MT", "home_team": "Buddies", "home_code": "TC" },
{ "game": 12, "away_team": "Chucks", "away_code": "BO", "home_team": "Intimidators", "home_code": "DK" },
{ "game": 13, "away_team": "Indians", "away_code": "JJ", "home_team": "Warmers", "home_code": "VS" },
{ "game": 13, "away_team": "Giants", "away_code": "C8", "home_team": "Pigskins", "home_code": "R6" },
{ "game": 13, "away_team": "Swimmers", "away_code": "W1", "home_team": "I.J.L.S.A.", "home_code": "AP" },
{ "game": 13, "away_team": "Gamblers", "away_code": "MM", "home_team": "Mimes", "home_code": "JB" },
{ "game": 13, "away_team": "Melonheads", "away_code": "IS", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 13, "away_team": "Marvels", "away_code": "M@", "home_team": "Pickles", "home_code": "MS" },
{ "game": 13, "away_team": "Wombats", "away_code": "DA", "home_team": "Mets", "home_code": "MK" },
{ "game": 13, "away_team": "Mathematicians", "away_code": "MT", "home_team": "Poopers", "home_code": "RR" },
{ "game": 13, "away_team": "Chucks", "away_code": "BO", "home_team": "Boys", "home_code": "EF" },
{ "game": 13, "away_team": "Intimidators", "away_code": "DK", "home_team": "Angelas", "home_code": "PZ" },
{ "game": 13, "away_team": "Buddies", "away_code": "TC", "home_team": "Jays", "home_code": "FJ" },
{ "game": 13, "away_team": "Bombers", "away_code": "CK", "home_team": "Bankees", "home_code": "SW" },
{ "game": 13, "away_team": "Astros", "away_code": "PS", "home_team": "Knights", "home_code": "WS" },
{ "game": 13, "away_team": "Lizards", "away_code": "SA", "home_team": "Bullpups", "home_code": "HM" },
{ "game": 14, "away_team": "Mets", "away_code": "MK", "home_team": "Grimaces", "home_code": "N8" },
{ "game": 14, "away_team": "Warmers", "away_code": "VS", "home_team": "Mimes", "home_code": "JB" },
{ "game": 14, "away_team": "Pigskins", "away_code": "R6", "home_team": "I.J.L.S.A.", "home_code": "AP" },
{ "game": 14, "away_team": "Pickles", "away_code": "MS", "home_team": "Wombats", "home_code": "DA" },
{ "game": 14, "away_team": "Indians", "away_code": "JJ", "home_team": "Marvels", "home_code": "M@" },
{ "game": 14, "away_team": "Giants", "away_code": "C8", "home_team": "Melonheads", "home_code": "IS" },
{ "game": 14, "away_team": "Swimmers", "away_code": "W1", "home_team": "Gamblers", "home_code": "MM" },
{ "game": 14, "away_team": "Bullpups", "away_code": "HM", "home_team": "Bankees", "home_code": "SW" },
{ "game": 14, "away_team": "Poopers", "away_code": "RR", "home_team": "Jays", "home_code": "FJ" },
{ "game": 14, "away_team": "Boys", "away_code": "EF", "home_team": "Angelas", "home_code": "PZ" },
{ "game": 14, "away_team": "Knights", "away_code": "WS", "home_team": "Lizards", "home_code": "SA" },
{ "game": 14, "away_team": "Mathematicians", "away_code": "MT", "home_team": "Astros", "home_code": "PS" },
{ "game": 14, "away_team": "Chucks", "away_code": "BO", "home_team": "Bombers", "home_code": "CK" },
{ "game": 14, "away_team": "Intimidators", "away_code": "DK", "home_team": "Buddies", "home_code": "TC" }
]
module.exports = { s1503teams, s1503schedule};